### ISSUE TITLE
import converting absolute path to relative path

### ISSUE THREAD

**Issue by avail** [mholt/caddy#1026]
for example: in my Caddyfile I have an `import /home/avail/.caddy/*.conf`, in a conf there, let's say `/home/avail/.caddy/avail.pw.conf` I have `import /etc/caddy/common.conf`, and it tries importing `/home/avail/.caddy/etc/caddy/common.conf`

**Comment by mholt** [comment]
@avail Thanks for the report. Could you please pull down the [`importfix` branch](https://github.com/mholt/caddy/tree/importfix) and see if that resolves the issue for you?

Also I think @pedronasser might be interested in reviewing this as well since the code I modified was introduced in d7698ecf1319b116171bc5deb6a357061574da08, but I am not sure why the chunk I removed was necessary, since it seems to be the cause of this bug.

**Comment by mholt** [comment]
Ping. @pedronasser - can you take a look? @avail - does that work for you?

**Comment by pedronasser** [comment]
Sorry for taking so long @mholt.
I'll take a look asap.

**Comment by avail** [comment]
@mholt sorry, I can't really test as I have no Golang experience whatsoever. :( I usually just grab the latest build from the site.

**Comment by mholt** [comment]
@avail Okay, thanks for letting me know. I'm pretty sure I was able to reproduce your issue, just waiting for Pedro to OK it.
