### ISSUE TITLE
Radix tree or trie for matching urls

### ISSUE THREAD

**Issue by brk0v** [mholt/caddy#103]
Right now there is a very naive checks for matching request url. For example in proxy module: 
https://github.com/mholt/caddy/blob/master/middleware/proxy/proxy.go#L62

This makes difficult to use such syntax: 

```
   proxy / http://127.0.0.1:8888 {
   		proxy_header Host example.com
    }

   proxy /api http://127.0.0.1:9999 {
   		proxy_header Host example.org
   }
 
   proxy /api/messages http://127.0.0.1:1234 {
   		proxy_header Host example.net
   }
}
```

What do you think about using here for matching radix or trie tree?

**Comment by mholt** [comment]
Not opposed to it - that's why the Matches() function exists: so middlewares can match paths without worrying about how they are being matched. Right now it's juts a prefix match.

The bigger question is: What kind of path matching would you like to have? Sure, we *could* use a radix tree, but what are we trying to accomplish with it?

**Comment by nemothekid** [comment]
I think what hes proposing the syntax would be the same - its just that, as it stands, prefix matching is too "dumb" to realize that it should route `/api/messages` to `http://127.0.0.1:1234`, not `http://127.0.0.1:8888` as what is done currently given OP's Caddyfile.

**Comment by mholt** [comment]
I see what you mean now, you're right. Sorry @brk0v - ignore my previous comments, they are irrelevant. Since `/api/messages` is more specific than `/`, it should route to `http://127.0.0.1:1234`, not `http://127.0.0.1:8888`.

If I understand correctly, that specificity is what we are talking about, then yes, we can look at this. It says in the docs that the order of directives in the Caddyfile doesn't matter -- that's true, but when it comes to prioritizing which paths to match, the *first* one is highest priority, and it has descending priority from there.

This doesn't have to be the way we do it - we just have to keep it fast and intuitive. I think the Go std lib's DefaultServeMux prioritizes based on the length of the match, so maybe we could imitate that behavior with the radix tree.

Am I on the right track now?

**Comment by brk0v** [comment]
Yes. 
I don't know how DefaultServeMux works so suggest a radix tree. I'll try to figure out how it works and make proof using same logic.

**Comment by brk0v** [comment]
Pull request https://github.com/mholt/caddy/pull/114

**Comment by mholt** [comment]
For the record, I feel like this change makes sense; of multiple overlapping rules, the longest path prefix should be chosen -- I can't imagine a reason that a user would write a specific path and then want a less-specific path to be matched; then the longer one never would be!

Thanks for everyone's feedback so far! Closing this issue to funnel the discussion into #619.

**Comment by mholt** [comment]
Change accepted in 345ece3850d43a487dd45d64126ff937d58d0eea. Thanks!
