### ISSUE TITLE
native Etcd support

### ISSUE THREAD

**Issue by j-mcnally** [mholt/caddy#104]
ive been working with Etcd a lot lately and it would be nice if caddy could be configured directly from it. The current solution is the same as nginx and Apache. Confd templates a new caddyfile and restarts / hups caddy. Would be nice to see our modern web server support this natively.

Zookeeper and consul would also be nice additions.

All the best.

**Comment by GeertJohan** [comment]
Would like this too :+1: 
Maybe a flag `--etcd-caddyfile-key` and `--etcd-address` and flags for ssl options etc.?
I would then just watch the given key, and the value is the caddyfile.
A change would have the same effect as editing the caddyfile on disk and restart/sighup caddy.

**Comment by mholt** [comment]
@j-mcnally @GeertJohan How about a REST API? From #107 I'm told that there is a way to make an HTTP request with etcd, which will soon be a possibility since the API is coming along quite well. Would that suffice?

**Comment by GeertJohan** [comment]
Well then I guess a SIGHUP would be a more common way to reload the config? As said in #107; [kelseyhightower/confd](/kelseyhightower/confd) can watch etcd and rewrite the config file on disk, then SIGHUP the caddy instance to signal it should reload the config file.
This way caddy doesn't have to care about all the config databases out there..
What could be useful to build in caddy, apart form SIGHUP, is a flag `-watch`, which simply watches the Caddyfile (on systems that support it, other systems Caddy should exit with error), and reloads the config when it was modified. This can also be very useful during development time.

**Comment by j-mcnally** [comment]
honestly im fine with just using confd. just thinking about positioning caddy as a first class alternative to nginx / apache in this new CoreOS / Docker / Cluster Cloud Data-Center world.

**Comment by GeertJohan** [comment]
@j-mcnally right thats what I'm saying. But confd requires caddy to reload on SIGHUP to be able to do a smooth restart, right? Otherwise it would need to hard restart caddy..

**Comment by GeertJohan** [comment]
Nevermind. I confd can write the caddyfile from etcd to disk and then `curl` to the upcomming API with the caddyfile as post body to reload the server config. That will solve this issue and make caddy compatible with etcd (through confd).

**Comment by j-mcnally** [comment]
Anyone mind if I close this in favor of the api and Confd? At least for now we get a lot for free by just using Confd.

**Comment by GeertJohan** [comment]
:+1:

**Comment by mholt** [comment]
That'll make life easier on me :smile: I just implemented the 'reload' functionality in the API. It's not wired up yet, but when it is, this command will reload the server with the latest config file from the disk:

```
curl -X POST http://localhost:10000/cmd/reload
```

And it rolls back the configuration if the reload fails, so no downtime. Great idea!

**Comment by guilhem** [comment]
@j-mcnally @mholt sorry to talk againg on this closed thread. But I think it can be good to reopen it.

I don't really understand why only work on proxy https://github.com/mholt/caddy/pull/564 https://github.com/mholt/caddy/pull/515 
I'm really interested to `caddy` but lack of remote API is clearly a no-go for the moment.

IMHO, `confd` is a very good solution for legacy software but isn't a silver bullet.
Having a confd daemon implies that you have to manage an init system in your container:
* In best world: you have systemd and use units with an auto-restart on process failure and have logs
* In some case: you are using `supervisord`... and have many problems with logs
* In most of cases: you only launch software in a `run.sh` and have no fraking what's happen in there.

Another problem is that you don't really respect `12factor` app configuration. You have a "physical" file on a Posix system who is "moving".

A good point of etcd/consul is that you can have a "generic" image without any customisation, with a read-only filesystem (who can be in memory) and customize it from another point.

Because exemple is better than many speech: https://github.com/vulcand/vulcand

**Comment by mholt** [comment]
An API is coming, that will be able to change all aspects of the server.

**Comment by guilhem** [comment]
@mholt Having an API is really a good thing for any software (`vulcand` have one).

Problem is where are you storing configuration?
If it's locally:
* Easy to test and to understand
* Hard to manage HA cluster of multiples servers
* Hard to manage re-instantiate or cold-start

The only way to manage all this kind of problems is by having a distributed kv.
It's not a hasard why many software are using `zookeeper`, `consul` or `etcd`.

**Comment by mholt** [comment]
@guilhem  So if your distributed kv is where you keep your Caddyfile, how about if you could start Caddy with a command line flag and/or env variable to have Caddy load the config from that source? Suppose it worked with etcd, consul, and others, would that be good? (/cc @j-mcnally)

**Comment by arca1n** [comment]
This would be great!

**Comment by mholt** [comment]
@arca1n It's now possible, somebody just has to write a Caddyfile loader for it. Instructions on extending Caddy are in the wiki. :wink:

**Comment by nodesocket** [comment]
👍 this would be amazing when using `proxy` for service discovery of backends.

**Comment by nii236** [comment]
> An API is coming, that will be able to change all aspects of the server.

@mholt is there a place I can find out more about this?
