### ISSUE TITLE
Authentication ,authorization(session management ), Caddy configuration for restricted routes 

### ISSUE THREAD

**Issue by hackintoshrao** [mholt/caddy#109]
Here are set of features which could make authentication and authorization pieces easier for developers 

## Social Login 
Enabling social login for easy authentication 
Caddy configuration could be something like this 

```

login facebook  {
    facebook_api_key        FB APP ID
    facebook_api_secret     FB API SECRET
    login_page_redirect     http://localhost:3000/auth/facebook
    callback_url            http://localhost:3000/auth/facebook/callback
    host                    localhost
    sucess_redirect         /
   failure_redirect         /login
}

```
After login sessions management has to be made easy , the login middle should force implementation of a User struct which will be  directly injected as session data , the session management tool like Gorilla will unable  the usage of wide variety of storage options for sessions 

## Restricted routes made easy 
Once authentication is provided it should become easier for developers to identify whether the a given request is authenticated and graceful handling of authenticated and un-authenticated cases . This is equivalent to setting up routes which will only be served if the user is authenticated and equivalent redirection for non-authenticated users 

Caddy configuration could be something like this 

```
authorize  all {
    failure /login
}
```

```
authorize /api1 /api2 /api2  {
        failure /login
} 
```

```
authorize   {
       route /api1
       failure /api1guest

} 
```

**Comment by mholt** [comment]
Cool idea. Let me hold off on deciding on it until we figure out whether to grow Caddy's middleware collection - and if so, how best to do it. In the meantime, I'll leave this open for discussion.

**Comment by Karthic-Hackintosh** [comment]
Sure .....

**Comment by markerikson** [comment]
I would love it if Caddy added additional support for some kind of authentication layer.  Our (internal-ish) app currently protects all backend services with a homegrown Python reverse proxy that also connects to an LDAP server for user/pass authentication.  We had to write that ourselves after various deployment constraints forced us to abandon using Apache for those tasks.  I would love it if there was some way to use Caddy as a replacement for that homegrown code, particularly since I'm hoping that we might be able to use Websockets in our next development cycle and I see that Caddy just added support for proxying WS connections.

**Comment by mholt** [comment]
I forgot to update this issue since we rolled out custom builds. @Karthic-Hackintosh, this is a possibility now. Perhaps you and @markerikson could come up with something that is suitable for both of you and the largest possible user base. I'll be happy to provide some feedback along the way. One thing I'd recommend initially is to try to keep it all under a single directive.

**Comment by Karthic-Hackintosh** [comment]
@mholt  , I shall start working on that and come with a proposal

**Comment by coolaj86** [comment]
In what way is it intended to limit access?

Note that if limitation is "must have a facebook account", well, that's anyone. What should this social login accomplish?

**Comment by cvvs** [comment]
@coolaj86 , I'd agree that it's mostly useless if you're just checking that a user has an <insert social media account here> unless you're just using it to provide some kind of personalized experience.

I'm interested in using oauth for authorization. In a corp environment, one could use one's companies own OAuth infrastructure and limit access to certain routes to members with specific roles, organization id, etc.  For my personal use, I could use this whitelist specific github, google, etc. users so that they're able to access certain restricted resources, or perhaps they can edit resources, where others can only read. This prevents me from having to build a full block authentication provider... which is really easy to get wrong.

**Comment by mholt** [comment]
Closing this in favor of #246 which is a little more general and also has further discussion on the same topic.
