### ISSUE TITLE
Using index files within sub-directories

### ISSUE THREAD

**Issue by mgibbs189** [mholt/caddy#11]
Hey Matt - great work so far!

Is there a way for Caddy to use index files (e.g. `index.php`) within sub-directories?

E.g.
http://local.dev/ --> Caddy will correctly use `/index.php`
http://local.dev/myfolder/  --> Caddy does not use `/myfolder/index.php`
http://local.dev/myfolder/index.php --> Works correctly, but not ideal

```
local.dev:80 {
    root path/to/document/root
    fastcgi / 127.0.0.1:9000 php
}
```

Thanks for any guidance

**Comment by thomas4019** [comment]
Hi Matt,

I just pushed a fix to the fastcgi middleware so that it now serves index files in subdirectories. You won't need to change your Caddyfile.

You could try it out by [running from the source](https://github.com/mholt/caddy#running-from-source). It would be great if you could test it and let me know if it solves your problem. Thanks for your feedback!

**Comment by mgibbs189** [comment]
Works great, thank you!
