### ISSUE TITLE
Prometheus Plugin on wrong position

### ISSUE THREAD

**Issue by ulrichSchreiner** [mholt/caddy#1119]
### 1. What version of Caddy are you running (`caddy -version`)?
0.9.1

### 2. What are you trying to do?
collect metrics with prometheus plugin

### 3. What is your entire Caddyfile?
```text
mymachine:8080 {
  tls off
  prometheus
  proxy / https://github.com
}
```
where `mymachine` is my local machine.

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy -conf caddyfile

### 5. What did you expect to see?
metrics for the http-requests

### 6. What did you see instead (give full error messages and/or log)?
no metrics at all.

The ordering of the plugins is wrong for the prometheus plugin. It should be at least at a lower position than the proxy plugin. As you can see in miekg/caddy-prometheus#17 this would solve the problem. As @miekg notes, it should be on position 0.

**Comment by mholt** [comment]
Definitely not spot 0 -- but maybe before proxy or other middleware that "handle" the requests and terminate the chain. As a general rule, keep it as late in the chain as possible.

I've moved it because I'm doing a new release, like, today, but if it's still not in the right place, have @miekg move it into a better spot with a pull request. Thanks!
