### ISSUE TITLE
Add upstream directive

### ISSUE THREAD

**Issue by lenovouser** [mholt/caddy#115]
My caddyfile gets very unorganized when I try proxy to a lot of different backend servers.

It looks kinda like this:

```
proxy / api.backend.mydomain.tld:6000 api.backend.mydomain.tld:6001 api.backend.mydomain.tld:6002 api.backend.mydomain.tld:6003 api.backend.mydomain.tld:6005 api.backend.mydomain.tld:6006 api.backend.mydomain.tld:6007 api.backend.mydomain.tld:6008 api.backend.mydomain.tld:6010 {
	policy round_robin
	websocket
	proxy_header Host {host}
}
```

It would be nice to have something similar to the NGINX **[upstream](http://nginx.org/en/docs/http/ngx_http_upstream_module.html)** directive. Maybe even with a few advancements to it. E.g. the ability to use port-ranges. Ideally I would like it to look something like this:

```
upstream api {
	api.backend.mydomain.tld:{6001:6010}
	api.backend.backup.mydomain.tld:{6011:6020} backup
}
proxy / api {
	policy round_robin
	websocket
	proxy_header Host {host}
}
```

Important options used in the NGINX upstream are:

  * **weight:** You can set it from 0 to 10. The higher the number the more load is being directed to the server. Useful if you have servers with different memory and processor configurations.
  * **backup:** Marks a server as backup. This server only gets used when the servers without the **backup** directive are not responding.
  * **down:** Marks a server down. Useful because you don't have to delete the line in case you need it again.
  * **resolve:** Looks for backend IP address changes. Useful when having a backend that gets moved a lot.

**Comment by mholt** [comment]
That's a long line, indeed. I like the port ranges idea, although I don't know how commonly that is needed. I would be interested to know if others have similar needs.

Without saying yes or no to these features either way, mind if I suggest an alternative syntax, just for the sake of discussion?

```
proxy / api.backend.mydomain.tld:6001-6020 {
    policy round_robin
    websocket
    proxy_header Host {host}
}
```

I realize that doesn't allow the 4 options you mentioned, but I do like this better than defining upstreams and stuff - since doing it the way you've proposed changes the rules of the Caddyfile.

Curious about some of the options, mostly because I haven't set up a complex architecture like you have. The **backup** option - why keep any of the backends idle when you could be using them to share the load? Any one backend is a backup to any other backend already. The **down** option -- why not just put it in a comment instead? The **resolve** option -- why does the IP address matter when you use domain names to specify the backends anyway?

Also - how will having an API with which you can set all this up change things for you? For example, a web site or CLI to manage backends and stuff. This question is slightly unrelated but I am interested in your thoughts. Thanks!

**Comment by ApfelUser** [comment]
You could do both, allow `api.backend.mydomain.tld:6001-6020` and `upstream:api` maybe.

Our **backup** servers are in "sleep" mode (Debian, Suspend) and are booted over something similar to "Wake-On-LAN" when our master server registers request (Firewall, DDoS Protection, Wake-On-LAN) . The **weight** option is also pretty important to me, due to the fact that we have servers with different capacity. Yes, the **down** option is then probably unnecessary. And the **resolve** option is for **domains** who change their IP addresses often. NGINX doesn't cache the DNS requests then. 

The API will be very useful for us, I have already talked with my mates about creating a system which e.g. automatically boots up new servers and configures them. Also the ability to administrate 30 different web servers from 1 machine over the API seems like it will make life **way** more easier. Sadly we are very busy moving from Debian 7 -> 8, so I did not have any time to test the API, but I hope to find some next weekend. And I just remember that I need to find out how to compile Caddy first. But this should be no problem if this is a standard Go application. :smile: Also I will ask some questions on how to use it in #111

**Comment by mholt** [comment]
Thanks for the explanation. Makes sense; I was thinking resolve had to do with DNS caching but wasn't sure.

At this moment I'm not quite interested in changing the Caddyfile syntax, but if I may mark this as deferred, I would like to keep track of this suggestion for later. Admittedly the API is taking up most of my time right now. I'm glad you'll find it useful - I want to make sure we get that right for you and the other users.

Don't worry - compiling Caddy is easy. Just install Go, then `go get github.com/mholt/caddy`. After you make changes to the source you can just `go run main.go` to compile and run or `go build` to just compile.

**Comment by mholt** [comment]
How about this instead, @lenovouser:

```
proxy / {
    backends {
        api.backend.mydomain.tld:6000
        api.backend.mydomain.tld:6001
        api.backend.mydomain.tld:6002
        api.backend.mydomain.tld:6003
        api.backend.mydomain.tld:6005
        api.backend.mydomain.tld:6006
        api.backend.mydomain.tld:6007
        api.backend.mydomain.tld:6008
        api.backend.mydomain.tld:6010
    }
}
```

Would that be useful? Now you don't have a really, really long line. :smile:

By the way, the API is coming soon. It's mostly finished, in fact. The release after this next release should have a basic one to start with. The API will make it trivial to add/remove backends dynamically.

**Comment by lenovouser** [comment]
@mholt 

Hm. That looks good. How about making it even more simpler by being able to specify a port range too?

```
proxy / {
    backends {
        api.backend.mydomain.tld:6000-6010
    }
}
```

**Comment by mholt** [comment]
@lenovouser LOVE IT.

Somebody make it so. I've got my hands full for a while :smile:

**Comment by lenovouser** [comment]
I'd probably prefer `to` too. Glad you like it.

**Comment by jupiter** [comment]
It seems [nested blocks are not currently supported](https://github.com/mholt/caddy/blob/master/caddy/parse/dispenser.go#L95). Do we want to add the ability to have nested blocks for this? We could break this up into smaller issues such as:

1. Add ability to specify a port range for proxy hosts list, i.e. `proxy / api.backend.mydomain.tld:6001-6020 {`
2. Add a `to` or `backend` argument to a proxy block for multiple hosts, i.e.

```
proxy / {
    to api.backend.mydomain.tld:6000-6010
    to api-backup.backend.mydomain.tld:6000
}
```

Or, we could implement the first nested block.

**Comment by mholt** [comment]
@jupiter Good question... I do hesitate to support nested blocks because more nesting means more state and complexity (something I didn't address earlier in this issue).

Indeed it would be simpler to just add a `to` keyword to the `proxy` directive to add another upstream, or set of upstreams.

Or if it looks weird to see `to` repeated multiple times, we could rename `to` to `upstream`.

**Comment by adambalogh** [comment]
Hi, I'm fairly new to this project, but I'd love to contribute! If this issue is still relevant, I'd be happy to work on it.

**Comment by mholt** [comment]
@adambalogh Yes, it is definitely still relevant :+1: Please do it! You may join us in [gitter chat](https://gitter.im/mholt/caddy) if you'd like to talk about it or have any questions.

**Comment by adambalogh** [comment]
Great! I'll start working on it.

**Comment by marc-gr** [comment]
Hi there! I'd like to start contributing! Is @adambalogh still working on this? If not, I'd like to work on it if is still relevant.

**Comment by thalesfsp** [comment]
@mholt The port range is just a must :) Here at our company, we are still using NGinx, mainly because we can use consul template to dynamic update the configuration file when we use `docker-compose scale`. I know that the dynamic backend is coming to Caddy (yeah!), but this feature is awesome too, because also we have a set of servers that is not dynamic and follow a port sequence such as `3001-3005`. The proposed syntax is nice, remember Caddy syntax, not NGinx stuff..

`proxy / api.backend.mydomain.tld:6001-6020` or
`proxy / api.backend.mydomain.tld:{6001:6010}` or <- may cause confusion because it resembles to `{$X} `
`proxy / api.backend.mydomain.tld:6001 to 6020` <- may cause confusion because devs expect `:` for ranges

**Comment by andrew-teeps** [comment]
I'd like to voice my support of a `backup` option. Sometimes a server may not be stateless and it only makes sense to use the backup in a failover situation.

Also (though a much less compelling reason) sometimes I have clients who irrationally want a backup server that isn't used during normal operation.

**Comment by mholt** [comment]
Thanks to @marc-gr this feature has been implemented. :100:

@andrew-teeps @lenovouser If you still need weight/backup preferences, it might be best to open a new issue or submit a pull request. :+1: Thanks!
