### ISSUE TITLE
Question: does caddy load plugins in specific order?

### ISSUE THREAD

**Issue by wendigo** [mholt/caddy#1168]
Hi,

I'm developing small caddy plugin (http midleware) and I wonder in which order my plugin will load and wrap other middlewares. Is there any specific order on which I can rely? Thx @mholt

**Comment by mholt** [comment]
Hey Mateusz! There's two ways to answer your question depending on what you mean.

- Plugins are _imported_ in an arbitrary order. Meaning, their `init()` functions (and thus registering them with Caddy) happen in some arbitrary order. This is by design, and makes it very convenient.

- If a plugin has a directive for the Caddyfile, the setup functions are executed in a _specific_ order, given absolutely in the server type's code. For the HTTP server, the list of directives is in [plugin.go](https://github.com/mholt/caddy/blob/8561f4278693badb8ac312665c5e566ef8ef5f6b/caddyhttp/httpserver/plugin.go#L392). This is also by design, and ensures that code is executed in the proper order when setting up the server. Because, for example, the `tls` directive needs to know what addresses `bind` has configured for each site before it sets up HTTP->HTTPS redirects.

Hope this helps! (Whatcha writing? :wink:)

**Comment by wendigo** [comment]
Got it, thx! I will share when I'll be ready 😄 Hope by the end of the week 🙏
