### ISSUE TITLE
Individual tls protocol supports for each site.

### ISSUE THREAD

**Issue by gongzhenjeef** [mholt/caddy#1203]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?

Caddy 0.9.3

### 2. What are you trying to do?

Have only one specific site allow tls1.0 protocol, while other sites remain tls1.2 only

### 3. What is your entire Caddyfile?

t.example.com {
    proxy / localhost:1111 {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-For {remote}
        websocket
    }
    tls {
        protocols tls1.2 tls1.2
    }
    log /var/log/caddy/trl.log
    errors /var/log/caddy/tre.log
}
r.example.com {
    proxy / localhost:2222 {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-For {remote}
        websocket
    }
    tls {
        protocols tls1.0 tls1.2
    }
    log /var/log/caddy/trl.log
    errors /var/log/caddy/tre.log
}

### 4. How did you run Caddy (give the full command and describe the execution environment)?

Default configuration with systemd init.

### 5. What did you expect to see?

Only r.example.com is configured to allow tls1.0 ptotocols.

### 6. What did you see instead (give full error messages and/or log)?

All sites supports tls1.0 ptotocols.

**Comment by mholt** [comment]
Hi there, thanks for the report!

The `tls` directive configures a listener, which is shared by all the sites on that port. So Caddy has to union the TLS settings for each site so that it can serve your site. For protocol versions, Caddy [configures the widest range](https://github.com/mholt/caddy/blob/2b9bbc5236fc7d026f2080b014972573076cef01/caddytls/config.go#L280).

This isn't a bug, but I could probably mention this in the docs for the tls directive!
