### ISSUE TITLE
command DNS provider

### ISSUE THREAD

**Issue by leonelwilliams** [mholt/caddy#1227]
I'd like to propose a new type of DNS provider: command. This would execute a defined (via Caddyfile or ENV) program to add or remove DNS records. This would have benefit of supporting custom implementations or bespoke DNS providers easily without much hassle

For example, I have a domain with a lot of (virtual) servers serving various sites on an internal network. I didn't want to give each server access to my entire DNS zone for security reasons so I whipped up a quick API that manages the TXT records if the server is authorized for that hostname.

**Comment by mholt** [comment]
Thanks for the idea. One issue with this is that the external command would still need to be written to be compatible with some sort of format that Caddy expects. Since it would still have to be written for Caddy, it might as well be written in Go and built as a provider just like the other ones.

So I'm not really convinced this would be useful...

**Comment by AndreKR** [comment]
I'm interested in this feature as well (and willing to implement it).

Your counter-argument is valid for public DNS providers, but not for internal APIs. Caddy certainly wouldn't benefit from `tls.dns.acmecorpsdnsmanagement`, `tls.dns.joesraspberrypi` or `tls.dns.janesdynamicdnsvps` plugins.

Being able to just call a script would be the easiest solution to couple Caddy with arbitrary DNS management systems.

**Comment by mholt** [comment]
Alright; go ahead. :) But that'll be in the [caddyserver/dnsproviders](https://github.com/caddyserver/dnsproviders) repo, not this one, so I'll just leave this issue closed.

**Comment by AndreKR** [comment]
Turns out, lego already has a provider "exec" which does exactly this. Here's a PR for the Caddy wrapper: https://github.com/caddyserver/dnsproviders/pull/32

It uses the environment variable `EXEC_PATH`. While it seems a bit strange to configure such a thing with an environment variable and not in the Caddyfile, I left it like that because a) this way the lego exec provider [docs](https://github.com/xenolf/lego/blob/master/providers/dns/exec/exec.go#L4) match the way it's done in Caddy and b) there seems to be no good way for a DNS provider to get directives from the Caddyfile.

**Comment by mholt** [comment]
@AndreKR Perfect. Although, I think the DNS provider adapters are designed so that the command could be passed in as an argument instead of an env variable if desired. I commented over on your PR.
