### ISSUE TITLE
Automatic recognition of *.json for configuration

### ISSUE THREAD

**Issue by brasilikum** [mholt/caddy#1248]
I am currently trying to automate my deployments of Caddy with Chef. Configuration from JSON would really make building the configuration easier. I have seen the [json.go](https://github.com/mholt/caddy/blob/master/caddyfile/json.go) and also, that is [has not been used yet](https://sourcegraph.com/github.com/mholt/caddy/-/blob/caddyfile/json.go#L93). 

I have not found any concrete plans about how to incorporate this into Caddy, so I will elaborate on my ideas here:

- The Caddyfile would still be the default and none of the changes to made should influence the current way Caddy is configured
- If `-conf` is not provided, Caddy would still default to `./Caddyfile` or, if not found, to `/Caddyfile.json`
- If `-conf *.json`, Caddy would try to read the config in JSON format
- If parsing from STDIN fails for the Caddyfile format, Caddy would try to parse it from JSON format.

I would like to know your thoughts on this, if it matches the overall strategy for Caddy and if I should submit a pull request implementing this behavior.

**Comment by mholt** [comment]
Instead of making a pull request in this case, make a [plugin](https://github.com/mholt/caddy/wiki/Writing-a-Plugin:-Caddyfile-Loader). :blush: All it would have to do is look for a .json file I suppose, and convert it to Caddyfile.

However, the JSON format is intended for use with the up-and-coming web UI for Caddy; there doesn't seem to be much benefit of using JSON over the Caddyfile syntax in other situations, since Caddyfile is easier to write. Why do you want to use JSON, exactly?

**Comment by fjl** [comment]
I would appreciate this as well. In my setup the Caddyfile is generated by an ansible template and I've had several issues where the 'intuitive' syntax of Caddyfile caused subtle issues because there was whitespace in the wrong place.

**Comment by brasilikum** [comment]
I really think the Caddyfile is the most intuitive format for the configuration of a webserver I have seen so far.
For automated generation and modification (partial changes) however I prefer JSON because it is more widely used an there are a lot of generators for it.
I see the downside of putting this into the core however, because there would be two formats that are not compatible, which could lead to fragmentation in documentation and discussions.

I have written a [plugin to relay requests to slack](https://github.com/zahlz/caddyslack) so I am a little familiar with plugins for caddy already. @mholt where would I tie in a plugin that executes before the parsing of the Caddyfile? Would you suggest literally writing it out to a Caddyfile so that the normal process is not modified or would you suggest replacing the Caddyfile-loader?

**Comment by mholt** [comment]
> I really think the Caddyfile is the most intuitive format for the configuration of a webserver I have seen so far.
For automated generation and modification (partial changes) however I prefer JSON because it is more widely used an there are a lot of generators for it.

Writing a Caddyfile is as easy as concatenating strings; the JSON format that Caddy accepts is just a JSON-ified Caddyfile syntax, where instead of separating tokens by spaces, they're individual elements in an array. Mainly useful for web compatibility IMO.

Hey, cool plugin. :) Mind if I tweet it? (Also do you want to add it to the Caddy download page? You don't have to at all, or right now -- maybe you could even help test the new automated build server when I have it ready.)

As for how to do the plugin, I'd recommend trying to make this a Caddyfile loader (linked to in my previous comment).

**Comment by brasilikum** [comment]
Ok, I will probably be generating a Caddyfile directly.

As for caddyslack, feel free to tweet about it. It works but I am somewhat not quite confident about it because it would maybe be a better idea to implement a modify-body-json plugin and combine it with redir and ratelimit.

I would love to see it on the downloadpage. Reading through the guidelines I thought it would classify as specific for a freemium service and therefore be unlikely to be accepted.

**Comment by mholt** [comment]
@brasilikum Fair enough -- stay tuned for the new build server which will have revised policies, may or may not affect your plugin, hopefully it does, for the better!
