### ISSUE TITLE
Setting a header based on the value of another header is non-deterministic

### ISSUE THREAD

**Issue by mwpastore** [mholt/caddy#1329]
### 1. What version of Caddy are you running (`caddy -version`)?

Caddy 0.9.4

### 2. What are you trying to do?

Set a header and proxy a request to another backend. This example is conveniently self-contained, but I am having the same and similar issues when proxying requests to Varnish, and when using FastCGI to delegate requests to PHP-FPM. 

### 3. What is your entire Caddyfile?

```text
:2015 {
  tls off
  proxy / :2016 {
    header_upstream Bar "foo"
    header_upstream Foo {>Bar}
  }
}

:2016 {
  tls off
  templates
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

Just by running `caddy`. macOS Sierra, 10.2.2, Caddy installed via Brew.

### 5. What did you expect to see?

Given the template `test.txt`:

```text
{{.Header "Foo"}}
```

And the `curl` statement: `curl http://localhost:2015/test.txt`

I expect to see:

```text
foo
```

### 6. What did you see instead (give full error messages and/or log)?

If I make the same request several times, the output sometimes appears, and sometimes does not. 

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Recreate `Caddyfile` and `test.txt` and issue the example `curl` command above a bunch of times.

**Comment by tw4452852** [comment]
This is a interesting issue. I just do some investigation and find out the reason is the order of headers:
Because we use [`http.Header`](https://github.com/mholt/caddy/blob/master/caddyhttp/proxy/proxy.go#L52) (a map actually) to store the upstream header rules, so when setup up upstream headers, the order of the rules is non-deterministic.

But your rules in your caddyfile are relevant:

```
header_upstream Bar "foo"
header_upstream Foo {>Bar}
```

it could be changed as if:

```
header_upstream Foo {>Bar}
header_upstream Bar "foo"
```

In time, the result will be only `Bar:foo`

@mholt , do you think it is necessary to maintain the correlation between the upstream/downstream header rules?

**Comment by mholt** [comment]
Hm, that is a weird one. Indeed, the ordering of the header changes is not guaranteed since the map is not ordered. There might be a clever way to keep it ordered in the code without getting too complicated... I am curious though, what's the use case for this? It's like your treating headers as variables or are just trying to reduce copy+pasting a header value on two lines? I ask because I've never seen this before in a config.

**Comment by mwpastore** [comment]
To be quiet honest, since filing this report I realized I didn't need to do what I was trying to do, so I don't have a great use case for it at the moment.

**Comment by mholt** [comment]
Okay. Thanks for the update. Thank you for your quick effort, too, @tw4452852 ! :+1:
