### ISSUE TITLE
RFC: Collect "testimonials" for web site & README

### ISSUE THREAD

**Issue by jawnsy** [mholt/caddy#1333]
It's no surprise that lots of people _love_ Caddy. It's got a great community (over 100 contributors!) and rich plugin ecosystem.  It'd be great to showcase testimonials or have a list of "powered by caddy" sites somewhere.

I mean, check out this endorsement: https://twitter.com/mikewest/status/817962064845172736

I understand that it's not possible or practical to link to everybody that says nice things about Caddy or uses it for their sites (there's just too many people!) but some highlights of prominent people, like Mike West, might be worthwhile.

Just a thought for your consideration :smile:

**Comment by mholt** [comment]
I'm glad you brought this up. I have been wanting to collect testimonials for the new website I'm working on. People can submit testimonials here: https://goo.gl/forms/0OMOuenYjxPuZNqU2

Thank you for your positive support, by the way. :+1: You and everyone else out there who share your good experience. It's encouraging, and I think people like reading about something _good_ that the modern Web is doing right, rather than the usual fights over containers and JS frameworks and stuff.

(I know Caddy has its flaws -- we'll work on those -- and weaknesses for certain uses cases -- we'll target the audience it's best at.)

**Comment by tehscorpion** [comment]
> rather than the usual fights over containers and JS frameworks and stuff
This! @mholt thanks for pointing out. Keep rollin'
