### ISSUE TITLE
Update ipfilter module

### ISSUE THREAD

**Issue by obrienmd** [mholt/caddy#1341]
I have a couple of use-cases (::1 in the ipfilter "ip" line, multiple ipfilter items in a config) that don't work in current Caddy (0.94 fresh off website), but seem to work if I build Caddy from source with the latest ipfilter.

I suppose I'm not sure how the module system works on the downloader - is there a manual process outside of source the Caddy team has to complete, or would a pull-request I can make to the website repo (the automated build system is probably beyond me at this point) to resolve this?

**Comment by mholt** [comment]
The download page is manually updated by me for every plugin. :-1: I usually bundle these together when I do a Caddy deploy but that takes half a day currently. So I'm focusing my efforts on finishing the new website which is entirely automated, everything from builds to Caddy deploys to plugin updates directly from their developers.

Unfortunately there's no other way to do it right now. You can compile Caddy from source yourself and include the plugins you want, you just have to add a line to a .go file. See how to import the plugin [on this wiki page](https://github.com/mholt/caddy/wiki/Extending-Caddy#how-to-write-a-caddy-plugin) (we'll probably have a new wiki page just for doing your own custom builds).

So, sorry for the delay. I'm just really focused on getting this new system ready. It's actually all working but the website needs an overhaul to support it and so that's what I'm doing now.

**Comment by obrienmd** [comment]
Cool, appreciate the fast response! No expectation of course, but do you have any rough ETA for the new web launch, or need any help a mediocre dev (reasonably good sysad) could pull request in?

**Comment by mholt** [comment]
I'm doing design work right now. :) I'll put out a call for help, probably testers in the next few weeks.

**Comment by obrienmd** [comment]
Cool, thanks again :)

--
Mike OBrien
253.217.7129
