### ISSUE TITLE
Trying to install a newer version of Caddy - returns "Aborting, error 0 in command:  [[ ${uname^^} == *DARWIN* ]]"

### ISSUE THREAD

**Issue by doefler** [mholt/caddy#1391]
### Version of Caddy
Caddy 0.9.1 (+e8e5595 Tue Aug 23 00:21:07 UTC 2016)

### Trying to
Install a newer version of caddy

### What I did

``` BASH
curl https://getcaddy.com | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4806  100  4806    0     0   5629      0 --:--:-- --:--:-- --:--:--  5627
bash: line 90: ${uname^^}: bad substitution
Aborting, error 0 in command:
 [[ ${uname^^} == *DARWIN* ]]

```

**Comment by Henrocker** [comment]
With which user are you trying to execute the `curl httos://getcaddy.com | bash` command?

**Comment by doefler** [comment]
I tried with my own user and with sudo in front.

**Comment by mholt** [comment]
I think this might actually be fixed at https://github.com/caddyserver/getcaddy.com but I just haven't updated the site yet. (Maybe @pepa65 would be able to check me on that) -- I just got back in town so I'll do that soon. I'm gonna close this since it's not in the right repository and also I think it might be fixed already. Thanks for the report!

**Comment by pepa65** [comment]
This has been fixed in the git repo, it's just not on https://getcaddy.com yet. Try:
https://github.com/caddyserver/getcaddy.com/raw/master/index.txt
