### ISSUE TITLE
basicauth: Remove siteRoot from htpasswd= parameter

### ISSUE THREAD

**Issue by magikstm** [mholt/caddy#1401]
Currently, it's not possible to put .htpasswd out of a website.

I would suggest removing "siteRoot" parameter from "passwordMatcher" in "caddy/caddyhttp/basicauth/setup.go" to allow it.

It's currently an undocumented feature of this parameter.

It would be a breaking change for some users (which could be adjusted by putting full path to the .htpasswd file), but it would allow .htpasswd file to be stored outside what is served by caddy.

Ref: https://github.com/mholt/caddy/blob/master/caddyhttp/basicauth/basicauth.go#L96
Ref: https://github.com/mholt/caddy/blob/master/caddyhttp/basicauth/setup.go#L77
Ref: https://caddyserver.com/docs/basicauth

If it's accepted, I could probably submit a pull request.

**Comment by mholt** [comment]
Thanks for the suggestion. I think this would be a good move... however, see my (upcoming) comment in your other issue #1402.

**Comment by elfurbe** [comment]
Since it evaluates the path as relative to root, you can strong-arm this config directive by using a series of `../../` prefixes in front of the actual location, ie:

```
servername.fqdn {
    root /var/www/html
    basicauth username htpasswd=../../../etc/caddy/htpasswd {
        realm "Realm"
        /
    }
}
```

As long as the user caddy is running under can see whatever location you hand it, it works fine. Obviously if you move the location of root, the htpasswd location might have to change as well. It's not pretty, but it solves the problem today.

If you're going to engineer a fix though, I think the right answer is to check the provided htpasswd path for a leading `/` and if it has one, treat it as absolute and if it doesn't, treat it as relative to the provided root. That's consistent with your average config file format and likely doesn't break as many current user configs.

**Comment by mholt** [comment]
I think this will be irrelevant in Caddy 2, so, closing.
