### ISSUE TITLE
markdown template auto reload for local develop

### ISSUE THREAD

**Issue by jet10000** [mholt/caddy#1445]
### 1. What version of Caddy are you running (`caddy -version`)?

0.9.5

### 2. What are you trying to do?

markdown template can't auto refresh when I change it.

**Comment by mholt** [comment]
FYI, for anyone who wants to contribute: this involves changing markdown's behavior to work like templates does, where it loads and parses the template file at request-time instead of during startup.

**Comment by francislavoie** [comment]
I'm thinking an option like `no_cache_template` to implement this would be good. Maybe you have a better idea for the option name @mholt?

**Comment by mholt** [comment]
I was wondering if we should just change markdown's logic so that it loads and parses the template at every request like `templates` does. It's not efficient for high-load servers (I mean thousands of page loads per second), but med-low loads will not even sweat it. There's another issue #1489 about optimizing this, but I'd rather changing the template file just works for now.

**Comment by mholt** [comment]
Markdown should now be loading the template at every page load (for now). Thanks, Tw!
