### ISSUE TITLE
Proxy server pushes

### ISSUE THREAD

**Issue by VanCoding** [mholt/caddy#1446]
Currently, it seems that caddy does not proxy server pushes.
So if my app relies on server push, I cannot put it behind a caddy-proxy, because the browser won't get the pushes that way.

Will you implement this in the future?

**Comment by wendigo** [comment]
You can use Preload links and Caddy will push resources to client event if using proxy.

**Comment by VanCoding** [comment]
That won't work for all applications.

I'm currently implementing a web push server, that implements the web push protocol.
The protocol makes heavy use of server push.

For example, to listen for push notifications, the listener makes a never-ending request to the server, and then the server pushes notifications via server push over that request.

**Comment by mholt** [comment]
We could look into this, but I don't know how to do it right now. I think we're going to implement auto-push first, but then maybe @wendigo and/or I could look into this?

**Comment by nilslice** [comment]
@mholt, @VanCoding - 

I had a similar question on [twitter](https://twitter.com/ponzu_cms/status/829059745755435008), and would love to see Caddy support this so more of my project's users could put their [Ponzu](https://ponzu-cms.org) apps behind Caddy and still leverage all of h2.

My problem sounds similar to @VanCoding's in which typical server push usage does not apply. Rather than using server push for resources like CSS/JS/etc to make a "page load" faster, Ponzu provides a Push mechanism to basically use the network for n+1 queries. As mentioned in the tweet, an example of this can be illustrated below:

Say you have 2 data types, `Song` and `Artist`, where each song has an artist field, referencing the `Artist` type:

```go
type Song struct {
	Title   string `json:"title"`
	Year    int    `json:"year"`
	Artwork string `json:"artwork"`
	Artist  string `json:"artist"`
}

type Artist struct {
	Title   string   `json:"title"`
	Logo    string   `json:"logo"`
	Members []string `json:"members"`
}
```   

In a Ponzu CMS app, the `Pushable` interface will allow the programmer to define which fields from the receiver struct to server push, as long as they are URLs.. (the Artist field in the Song struct would be a URL to the JSON representation of the Artist, i.e. `?type=Artist&id=42`)

So, by adding the Push method to Song, like below, a request for a Song would also send a server push for the embedded Artist endpoint too, so the artist information for that song is available to the client, without making an additional roundtrip:

```go
func (s *Song) Push() []string {
	return []string{
		"artist", // this being the json tag for the Artist field in Song struct
	}
}
```
e.g. `/api/content?type=Song&id=21` 
```json
{
"data": [{
    "title": "Where's the Revolution",
    "artist": "?type=Artist&id=42",
    "year": 2017,
    "artwork": "/api/uploads/2017/02/single-cover.png",
 }]
}
```
would send a push promise for the `data[0].artist` node as per the Push method to send down the JSON at `?type=Artist&id=42`
```json
{
"data": [{
    "title": "Depeche Mode",
    "logo": "/api/uploads/2017/01/depeche-logo.png",
    "members": ["Dave Gahan", "Martin Gore", "Andrew Fletcher"]
 }]
}
```

Currently, Caddy will not proxy the my explicit h2 server push to the client which I believe is what @VanCoding is also trying to achieve, versus the implicit server pushes done through an "auto-push" mechanism, or through the Preload headers which would require direct access to the ResponseWriter.

This certainly could be done, and may be achieved with some of Caddy's outstanding PRs for 1.8 HTTP/2 stuff.

@VanCoding - does this sound at all like the higher level of flexibility from server push you're looking for?

**Comment by VanCoding** [comment]
@nilslice yes, exactly.

As I understood it, with Go 1.7, this would not have been possible, but Go 1.8 does provide the features needed to implement this. So this seems to be the right time to ask for this :P

**Comment by wendigo** [comment]
As far as I know reverse proxy (https://golang.org/pkg/net/http/httputil/) does not support http push handling as of go 1.8. I don't know if it can be achieved straight away.

**Comment by mholt** [comment]
Seems this issue would be your best bet: https://github.com/golang/go/issues/18594

**Comment by wendigo** [comment]
Exactly @mholt. I think that best option for now is to leverage ```Link``` headers so instead of backend pushing resources - if it's running behind the proxy it should emit ```Link``` headers that will be handled by Caddy.

**Comment by nilslice** [comment]
@wendigo - that does seem to be the only option until go's h2 client and reverse proxy support reading the push_promise frames.

**Comment by mholt** [comment]
Closing for now, but labeled as deferred so we won't forget about it.

**Comment by xfalcox** [comment]
So @mholt currently caddy won't work with push in reverse proxy mode using either config or `Link` headers right?

**Comment by mholt** [comment]
If a backend responds with Link headers, Caddy will push those resources, but currently it won't send push frames from the backend.

**Comment by xfalcox** [comment]
> If a backend responds with Link headers, Caddy will push those resources

I modified Discourse to add the `Link` headers but I don't get any pushes.

My test bed is the main resource at https://forum.overwatchbrasil.org/

**Comment by xfalcox** [comment]
> I suppose the first question is if these are in the correct syntax/format?

I do believe they are :thinking: 

> Also, the server header, though easily overwritten/spoofed, is "nginx", not "Caddy" as commonly left in Caddy configurations. Are you definitely serving the site you linked from Caddy?

Yes I am, nginx is listening a sock and Caddy is the owner of 80 and 443 port.

**Comment by xfalcox** [comment]
@wendigo You said:

> Exactly @mholt. I think that best option for now is to leverage Link headers so instead of backend pushing resources - if it's running behind the proxy it should emit Link headers that will be handled by Caddy.

Does that work on latest master, or is a planned feature? I added all the `Link` headers on my response, but Caddy doesn't push.

**Comment by mholt** [comment]
@xfalcox I missed your reply; but that feature is released now; you can use Link headers upstream to initiate pushes downstream.
