### ISSUE TITLE
Parsing of errors{} directive does not match documentation

### ISSUE THREAD

**Issue by PetterS** [mholt/caddy#1494]
### 1. What version of Caddy are you running (`caddy -version`)?
Caddy (untracked dev build). Latest from go get.

### 2. What are you trying to do?
Validating the Caddyfile with caddy -validate

### 3. What is your entire Caddyfile?
```text
errors {
    log ../errors.log
    404 404.html # Not Found
    500 500.html # Internal Server Error
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy -validate

### 5. What did you expect to see?
No errors since this is an example from the documentation.

### 6. What did you see instead (give full error messages and/or log)?
2017/03/04 20:03:22 Caddyfile:5 - Parse error: Unknown directive '404'

### 7. Additional information
With this Caddyfile
```
test.example.com {
errors {
    log ../errors.log
    404 404.html # Not Found
    500 500.html # Internal Server Error
}
}
```
I get
2017/03/04 20:04:31 Caddyfile:3 - Parse error: Expecting a numeric status code or '*', got 'log'

**Comment by PetterS** [comment]
The last Caddyfile validates correctly with 0.9.5.

**Comment by mholt** [comment]
Regression introduced in https://github.com/mholt/caddy/commit/ce7d3db1be57b04975922a3988c02df8f993293f#diff-96fe4d98bc2cc4c3bcbcbd00eb5ed026L55 - /cc @julianvmodesto - do you think you can restore the "log" subdirective? We roll all logs by default but we do not enable error logging by default.

**Comment by julianvmodesto** [comment]
Hm 😳 oops, yes let's revert. Will try to help figure out what's wrong here.

**Comment by mholt** [comment]
You don't have to revert the whole change -- just put the log subdirective back. :)

**Comment by julianvmodesto** [comment]
Ahh misunderstood the bug at first, got it!

**Comment by julianvmodesto** [comment]
Taking a look again today. So we just need to revert to the old errors_setup.go (and the related log parsing for this directive) for now?

**Comment by mholt** [comment]
@julianvmodesto We need to restore the "log" subdirective so a log path can still be specified, but the rest of the behavior from your change -- as far as I understand it -- is good (the rolling logs by default if a log is enabled).

**Comment by julianvmodesto** [comment]
@mholt sorry, taking a look at this again, thanks for the poke on the other issue.

Shouldn't the equivalent valid Caddyfile be this, if error logging is wanted?

```
test.example.com {
errors ../errors.log {
    404 404.html # Not Found
    500 500.html # Internal Server Error
}
}
```

**Comment by mholt** [comment]
Thanks Julian! I'm swamped or I'd just do it right now. :)

Yeah, it's like that: the logs should go to the file that is designated in the Caddyfile, it should not ignore what the user specifies. I even set it to `stdout` (not a regular file, as you know) and it still created access.log in the current folder.

**Comment by julianvmodesto** [comment]
Oops -- @mholt meant to respond to https://github.com/mholt/caddy/issues/1529 instead of here!

**Comment by mholt** [comment]
@julianvmodesto I also have gotten some things confused. Sorry. :smile: There's two things going on here. Okay, here's what needs to happen:

- #1529 does need to be fixed. It's a separate issue from this one.
- I just realized that the syntax of the `errors` directive when a block is opened is now consistent the syntax of the `log` directive, which it wasn't before. In other words:

```
log access.log {
   ...
}
```

Is how `log` looks, but this is how `errors` used to look:

```
errors {
   log error.log
   ...
}
```

But this is how `errors` looks now:

```
errors error.log {
   ...
}
```

:point_up: I really like this new syntax better. It's consistent with `log`, it just so happens that the docs aren't updated yet because this feature isn't released yet. So this is a docs thing rather than a bug.

Indeed, the docs are only updated with new releases. The joy of running code from master!

So sorry for the confusion. We're all good here. Just #1529 needs some work, if you can still help with that! :+1:
