### ISSUE TITLE
Use cloudflare/go for crypto speedups

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#150]
This year, [CloudFlare drastically improved the speed](https://blog.cloudflare.com/go-crypto-bridging-the-performance-gap/) of P256 elliptic curves and AES-GCM and doubled the speed of RSA crypto in [their special fork of Go](https://github.com/cloudflare/go) with some tweaks to math/big.

The RSA speedups were [merged into the standard library](https://go-review.googlesource.com/#/c/9253/) and should make it into Go 1.5. This means that most users with RSA certificates will see a drop of CPU time by about half.

The ~20x speedup for AES-GCM and ECDSA are especially attractive. The change for AES-GCM landed barely too late for Go 1.5, but [it will hopefully be merged in soon after](https://go-review.googlesource.com/#/c/10484/).

Unfortunately, the spectacular elliptic curve improvements, which are for 64-bit Linux machines, were [rejected by some stubborn attorneys](https://go-review.googlesource.com/#/c/8968/) and won't make it into the std lib in the foreseeable future...

Since elliptic curve is the upcoming standard it would be unfortunate not to benefit from it on the most popular platform for production web environments.

Any thoughts on using CloudFlare's fork of Go for builds? It wouldn't be required for everyone to be on it, but it would at least be used to build Caddy for new releases.

**Comment by wmark** [comment]
I'd like to add some background. That's the trove most is from:
http://rt.openssl.org/Search/Results.html?Order=DESC&OrderBy=Priority&Query=Requestor.id%20%3D%2013977%20AND%20(Status%20%3D%20%27new%27%20OR%20Status%20%3D%20%27open%27%20OR%20Status%20%3D%20%27stalled%27)&user=guest&pass=guest

OpenSSL is under a BSD license. Anyway, please keep in mind that you cannot monkey-patch *Golang*. Which would solve everything (we could re-implement the underlying ideas).

If the BSD license is transitive or not, and if the licensing terms for *Golang* and Intel's apply to work you've compiled – that's a question for a lawyer. The answer will even differ based on your country.

For example, here in Germany none of Certicom's old patents did apply. And due to Cloudflare being the one licensing the work to $me we can use the aforementioned implementation at will.

**Comment by mholt** [comment]
Official Caddy builds starting July 1, 2015 are compiled with their fork of Go. (This is subject to change for future versions, but that doesn't seem likely.)

**Comment by wmark** [comment]
Vanilla *Go* doesn't have DHE key exchange (short: Kx). Ping me if that's the case with Cloudflare's and I will implement it.

Please note that vanilla *Go* doesn't have a side-channel resistant implementation of RSA. If that's the case with Cloudflare's a warning should be displayed if someone uses RSA certificates as well here.
