### ISSUE TITLE
systemd configuration expects networkd to exist, but this is not necessarily the case

### ISSUE THREAD

**Issue by joepie91** [mholt/caddy#1518]
(__Note:__ I'm filing this issue on somebody elses behalf.)

### 1. What version of Caddy are you running (`caddy -version`)?

0.9.5

### 2. What are you trying to do?

Setting up Caddy on Ubuntu 16.06.

### 3. What is your entire Caddyfile?

n/a

### 4. How did you run Caddy (give the full command and describe the execution environment)?

Using the standard systemd service file included in the release.

### 5. What did you expect to see?

The service starting correctly.

### 6. What did you see instead (give full error messages and/or log)?

The service failed to start, and the following error showed up in the journal:

```
Mar 15 16:49:32 [snipped hostname] systemd[1]: Network Service is not active.
Mar 15 16:49:32 [snipped hostname] systemd[1]: Dependency failed for Wait for Network to be Configured.
-- Subject: Unit systemd-networkd-wait-online.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-networkd-wait-online.service has failed.
--
-- The result is dependency.
Mar 15 16:49:32 [snipped hostname] systemd[1]: systemd-networkd-wait-online.service: Job systemd-networkd-wait-online.service/start failed with result 'depen
Mar 15 16:49:32 [snipped hostname] systemd[1]: caddy.service: Start request repeated too quickly.
Mar 15 16:49:32 [snipped hostname] systemd[1]: Failed to start Caddy HTTP/2 web server.
-- Subject: Unit caddy.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit caddy.service has failed.
--
-- The result is failed.
Mar 15 16:49:32 [snipped hostname] sudo[13076]: pam_unix(sudo:session): session closed for user root
```

The service file apparently expects `networkd` to exist, but this is not necessarily true on all systemd-using distributions. Removing it from the `Wanted` line fixed the issue.

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Set up Caddy on a systemd-using distribution that does not have `networkd` enabled.

**Comment by mholt** [comment]
Hey Joe, thanks for bringing this up! Unfortunately I don't have the bandwidth to support the community-contributed init scripts in the issue tracker: https://github.com/mholt/caddy/tree/master/dist/init#getting-help

But you are welcome to submit a PR to enhance the script or contact the authors of the script directly. I'm sorry about this. Thank you!

**Comment by joepie91** [comment]
Aha. I was looking for the initscript-related instructions because I vaguely recalled them existing, but I couldn't find them.

This should probably be referenced clearly from the CONTRIBUTING.md? Right now, it doesn't seem to be in there.

**Comment by mholt** [comment]
Good idea, I was planning on revising that document anyway. Will add it.

**Comment by joepie91** [comment]
Do you have a suggestion on where to file this? The support chat link in the README for that service file is dead, and there doesn't seem to be a separate repository listed or anything.

Or perhaps I can ping @wmark here directly? Given that the network requirement was added in f1c1ea99052a3ac752ed32ccad6b2ebc26539543.

**Comment by mholt** [comment]
You could ask on the forum or, yeah, Mark should be able to help out. :) That link should probably be updated 😁

**Comment by wmark** [comment]
It's the responsibility of a distribution maintainer to customize anything in any `dist` folders. ;-)

The `Wants=systemd-networkd-wait-online.service` should and will enable the service, if it is disabled. But if you have something conflicting, like `networkmanagerd-wait-online.service` (name similar)(Fedora Workstation has this), then yes: That doesn't get enabled. As there is no way to define an `OR` we've to live with an example *service file* that is good enough, but not perfect.

Just relying on `network-online.target` is not enough. If neither of the above services were enabled, the target is reached independently from any or all devices having received IPs (like, by DHCP or *dribbler* or whatever else).

As you shouldn't use the *NetworkManager* on a server anyway `systemd-networkd-wait-online.service` it is.

----
Please note that I do not recommend using the current version of `caddy.service`. Indeed, I strongly disagree with the concepts reintroduced by later edits.

**Comment by wmark** [comment]
If all your instance of *Caddy* listens to is `0.0.0.0` or `[::]` then you don't need the `*wait-online.service` services anyway. It's just that else a *Caddy* configured to listen on IPs that are not yet acquired will fail.

An alternative to all this is to set `IP_FREEBIND` on the listening socket of the webserver. Using C you'd:
```c
int value = 1;
if (setsockopt(fd, SOL_IP, IP_FREEBIND, &value, sizeof(v)) < 0) {
    perror("setsockopt(FREEBIND=1)");
}
```
… and with *Golang*:
```go
// +build linux

import (
    "syscall"

    "golang.org/x/sys/unix"
)

err := syscall.SetsockoptInt(fd, syscall.SOL_IP, unix.IP_FREEBIND, 1);
…
```

**Comment by joepie91** [comment]
The problem is that Ubuntu ships, by default it seems, without any kind of `systemd-networkd-wait-online.service` - which means that the service file just flat-out doesn't work on Ubuntu.

If there are such differences between distros, perhaps it'd be worth shipping distro-specific copies of the service file, since as it is now it's not exactly "works out of the box".

> Please note that I do not recommend using the current version of caddy.service. Indeed, I strongly disagree with the concepts reintroduced by later edits. If the machine in question would be subject to a security audit you would fail it.

Could you elaborate?

**Comment by wmark** [comment]
> The problem is that Ubuntu ships, by default it seems, without any kind of systemd-networkd-wait-online.service - which means that the service file just flat-out doesn't work on Ubuntu.

This is not correct:
 * http://packages.ubuntu.com/xenial/amd64/systemd/filelist

> If there are such differences between distros, perhaps it'd be worth shipping distro-specific copies of the service file, since as it is now it's not exactly "works out of the box".

The files are meant to be customized for your distro anyway.

> Could you elaborate [on why you don't recommend the current version of the service files; edit by @wmark]?

https://github.com/mholt/caddy/issues?utf8=%E2%9C%93&q=is%3Aissue%20systemd%20setcap%20commenter%3Awmark

**Comment by joepie91** [comment]
> This is not correct:

I've seen this issue on two people's systems now, both running an Ubuntu installation that they haven't messed with in strange ways (one of them is xenial). I don't know what Ubuntu is doing to their network services, but one thing is obvious: the current service file doesn't work out of the box. I don't use Ubuntu personally, and so have no idea about the specifics.

> Ubuntu 16.06 does not exist, by the way.

I might've typoed that. I was relaying information from somebody else :)

> The files are meant to be customized for your distro anyway.

Okay? But this doesn't really help for out-of-the-box deployment, which is now still too difficult. Caddy may be easy to configure, but if it's hard to install (and I don't expect distro packages to appear any time soon), then that doesn't really matter.

> https://github.com/mholt/caddy/issues?utf8=%E2%9C%93&q=is%3Aissue%20systemd%20setcap%20commenter%3Awmark

I'll have a look through that as soon as I have some spare braincycles, thanks :)

**Comment by wmark** [comment]
Please don't comment on a closed issue. :-)

> I've seen this issue on two people's systems now, both running an Ubuntu installation […]

I am truly sorry to have to address this in a blunt way: This is not true. Your initial bug report (which has been reviewed independently from any later claims) disproves it:

```
Mar 15 16:49:32 [snipped hostname] systemd[1]: systemd-networkd-wait-online.service:
  Job systemd-networkd-wait-online.service/start failed with result 'depen
```

Had it not existed, you'd not get this error. Indeed, *systemd* would not be able to schedule its start in the first place. (Service `caddy.service` would have failed due to a missing dependency instead.)

> the current service file doesn't work out of the box.

Please stop spreading FUD.

@mholt Can we lock this, please?

**Comment by mholt** [comment]
Both of you seem to agree that changes need to be made to the current revision of the script, and to that end, I'm going to ask that any further discussion on it happen in the [forum](https://forum.caddyserver.com), since this really has nothing to do with Caddy code. I made the Production Use category for discussions like this: https://forum.caddyserver.com/c/production-use

I hope that will be more productive, as I'd like to keep the issue tracker about Caddy itself, not systemd. Thanks!

**Comment by joepie91** [comment]
I've pretty much lost interest by this point. When I'm flat-out told that "this is not true" and to "stop spreading FUD" when I have two people *independently reporting to me* that it doesn't work out of the box... I don't exactly have any faith that there's any willingness to get this issue resolved.

I'm really not interested in a "technically correct" shouting match, I'm only interested in *getting the issue resolved* as well as possible.

At this rate, I'll just stop recommending Caddy to non-technical users until stable distro packaging (whether third-party or not) is a thing. I've now had to guide two people through their setup for hours, and that is not an ongoing time investment I intend to make, nor does it make sense in the bigger scheme of things compared to just instructing them to install Certbot with eg. nginx.

I don't think there's anything more for me to say on this matter, neither in this thread nor on the forums. A packaging thread [already exists](https://forum.caddyserver.com/t/packaging-caddy/61).

**Comment by alfiepates** [comment]
> Please stop spreading FUD.
>
> @mholt Can we lock this, please?

This is an awful response to a good-faith bug report from a Caddy user. 

This is not "FUD", this is an issue with a file that _ships with Caddy_, and highlights a deeper issue with the current Caddy deployment process (or in this case, lack of). 

People do not come into issue trackers just submitting bullshit/misinformation bug reports. Nobody cares enough to do that to a project like Caddy, or any project to be honest. This is a Caddy user (hell, a Caddy _advocate_, in my experience) coming across an issue whilst helping somebody else install and configure Caddy, and **opening a bug report to ensure the maintainer of the file is aware**. 

Take a second, reproduce this bug, and then _do something about it._ Don't just try and catch somebody by calling out their typos and trying to be Technically The Most Correct Ever Because That Is So Important.

Seriously. Don't be a jerk to your users. It's not a good lookc.

**Comment by wmark** [comment]
> Please stop spreading FUD.

… is no answer to the bugreport. It's one to the generalized claim »the current service file doesn't work out of the box«. Cited right above it, @alfiepates.

You misrepresent what happened here, and actually attack someone who helps users out. No claims were made by me without supporting evidence — which you happily ignore. Have *you* actually invested the time to reproduce the issue *yourself*?

1. The bug was opened, reviewed, and a detailed explanation given. That's value received for free.
2. Cherry on top, a workaround and further examples.
3. Still Sven Slootweg claimed the error existed due to missing files. — So, someone else (me) has invested even more time investigating this, and checked package manifests. Turns out the claim have **not been supported by facts.** Ridicule the reporter could have avoided by checking this easily himself *before* involving any volunteers.
4. Instead of considering the answers he got, and reproducing it on a fresh installation (VM, whatever):  
The reporter now claims the mismatch between between his previous claim and presented evidence can be witnessed by two friends.
5. At this point I could've ignored this due to the reporter not doing his part of the work, like restoring the files from the package again, or referring to new facts (scripts? or mixed up Ubuntu with a different distribution? anything?)…  
His issue has been reconsidered. **Again.** To get the issue resolved. Including the premise.
And found incompatible with **facts** the reporter **himself** presented.

Sorry, but I really do not see any obligation to investigate something the fourth time which has received plenty of attention and time, and been disproved repeatedly.

A bugreporter is expected to do his part of the work when asking someone for help and working on a remedy. Indeed, that expectation applies even when it's not about software. You'd drawn the line too, were your kindness, patience, and cooperation exploited.

**Comment by alfiepates** [comment]
> You'd drawn the line too, were your kindness, patience, and cooperation exploited.

Yeah, checking out right here, you weren't kind, patient, or cooperative. 

Stop treating your users like they're idiots.

**Comment by mholt** [comment]
All the code and scripts in this repository are contributed for the _benefit_ of the community. I am grateful for good faith efforts of all contributors: both those who maintain distro scripts for users who want one and those who help users set up Caddy in production.

I wish I had locked this issue earlier. I never like to do that. I much rather would have preferred the discussion been started afresh in the forum like I asked.
