### ISSUE TITLE
LESS compilation support

### ISSUE THREAD

**Issue by geek1011** [mholt/caddy#1521]
I have a request for a feature to support compiling LESS.

**Comment by pbeckmann** [comment]
You mean, that a part of caddy should compile your LESS-files for the websites and embed the links into the website?
If so, IMHO it's not something for the core of caddy, but more a nice idea for a plugin for caddy.

**Comment by geek1011** [comment]
I mean a plugin for caddy.

**Comment by mholt** [comment]
Hey, thanks so much for your interest in a new Caddy plugin! Since third-party plugins are developed externally (outside of this repo) and this is not really about Caddy itself, I'm going to close the issue. But you are welcome to request this plugin [in our forums](https://forum.caddyserver.com) where the idea can be discussed and someone may take it up and implement it.
