### ISSUE TITLE
Markdown code syntax highlighting

### ISSUE THREAD

**Issue by onodera-punpun** [mholt/caddy#1548]
So it would be really great if the markdown addon would also create classes for syntax highlighting, like github does it:

```bash
#!/usr/bin/bash

while true; do
    echo "hello word"
done
```

There are a few go packages that do this:

* https://github.com/sourcegraph/syntaxhighlight
* https://github.com/shurcooL/highlight_go

and specifically for md:

* https://github.com/shurcooL/github_flavored_markdown/

I think hugo also does something similar.

**Comment by mholt** [comment]
This depends on your style sheet. Why not just include some JS like https://highlightjs.org/? Why does the web server need to do this?

**Comment by onodera-punpun** [comment]
Yeah I'm actually using highlight.js now, but the downside is that syntax highlighting won't display for people who use something like noscript.

**Comment by mholt** [comment]
This is a nice idea. However, I think this might be a better fit as a plugin; the styling is still something that would have to be embedded into the site, and just linking to a CDN won't work depending where in the world you live (hint: ~1/6 of the world's population will not be able to use the feature). I hesitate to bring syntax highlighting, something very specific to mostly only developer sites, into the core of Caddy.

In any case, I still think it would be a bit strange for the server to be doing styling of the page. :) But if somebody wants to write a plugin to it because they have a certain use case (like a highly unusual majority of noscript users), feel free!

**Comment by Thunderbolt32** [comment]
The problem with highlight.js is that this library is not compatible with [rouge](http://rouge.jneen.net/) / [pygments](http://pygments.org/).

 It seems to me the most obvious alternative solution to [jekyll](https://jekyllrb.com/) and [github pages](https://pages.github.com/themes/): GIT + Filemanager + Markdown are strongly targeted by caddy and the template syntax is not as different as someone might think.
I just created a private fork of the [leap-day theme](https://github.com/pages-themes/leap-day) and have only problems with `_config.yml` and the syntax highlighter.
