### ISSUE TITLE
Feature request: self-signed certificates for upstreams

### ISSUE THREAD

**Issue by yawn** [mholt/caddy#1550]
### 1. What version of Caddy are you running (`caddy -version`)?

0.9.5

### 2. What are you trying to do?

Proxy to backends over HTTPS that use long-lived self-signed certificates. This could be accomplished by:

1. passing the public-key (encoded as PEM) as part of the upstream config OR
2. base64 std-encode the SHA2-256 hash of the public key (encoded as DER) - see the "pin" section on [sslabs](https://www.ssllabs.com/ssltest/analyze.html?d=google.com&s=2607%3af8b0%3a4005%3a808%3a0%3a0%3a0%3a200e&hideResults=off) for an example OR
3. use a custom TLS config with an artificial root CA specific to that Caddy instance 

Option 2 would be very simple and very readable. All cases would profit from tooling (e.g. create self-signed certificate key-pair, depending on the implementation including pin or including CA key-pair and matching signature on the backend key-pair), ideally provided by Caddy itself.

**Comment by mholt** [comment]
Thanks for the feature request , @yawn  - help me understand a little better. Caddy can already proxy to upstreams that use a self-signed certificate (you just have to use `insecure_skip_verify` to make the connection insecure with purpose). What is the feature you're requesting, exactly?

**Comment by yawn** [comment]
The difference is: `insecure_skip_verify` will support HTTPS but does not verify it *at all*. The proposed change would in fact verify the upstreams key by:

1. doing a manual verify of the public key in the actual TLS connection
2. the same
3. using a custom CA trust chain containing only the certificate of a local group of Caddy servers that was used to sign the self-signed certificate

This is a pretty common pattern for securing origin traffic, see for example:

* https://community.fastly.com/t/setting-up-self-signed-tls-in-fastly-and-my-origin/531 (approach 1) or
* https://blog.cloudflare.com/universal-ssl-encryption-all-the-way-to-the-origin-for-free/  (approach 3)

`nginx` for example seems to call option 1 [proxy_ssl_trusted_certificate](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_ssl_trusted_certificate).

**Comment by mholt** [comment]
What about just adding your CA to the system's trust store?

**Comment by yawn** [comment]
Mostly because maintaining your own CA is IMHO the least desirable approach. Super-easy would be putting the public-key (or it's pin) in. Creating self-signed, long-lived certificates is a very easy operation.

**Comment by mholt** [comment]
Well, when you self-sign a certificate, you're already doing so with some private key that you own; can you not tell the system that public key is trusted?

**Comment by yawn** [comment]
This might actually be technically possible (I'm not sure, I never checked). Theoretically there should not be a difference between a CA's public key and and endpoints public key (expect *maybe* for `*keyUsage` attributes but that should not matter) - ideally I'd prefer to have this data in the reverse proxy though since the trust I have for the certificates is something exclusive to this surrogate - origin relationship. 

The difference between "maintain your own CA" and just creating self-signed certificates would be that in the former case I trust one entity (the CA) that in turn creates signatures on other keys (the origin servers). In the latter case I'd trust each origin key individually.

**Comment by rgl** [comment]
any news about this?

it would be really great to be able to set the upstream trusted CAs, either at the proxy level or the http level. using something like the existing `tls load` directive. this would be better that having a blanket `insecure_skip_verify` directive.

**Comment by lukenowak** [comment]
In order to solve this issue `proxy` directive would have to be extended.

Simillary to Go's [crypto/x509](https://golang.org/pkg/crypto/x509/) `SSL_CERT_FILE` and `SSL_CERT_DIR` I would propose to add something like to proxy directive:

```
proxy {
  ssl_cert_file /path/to/ca-list-bundle.pem
  ssl_cert_dir /path/to/ca-list-directory/
}
```

Which would add those CA certificates for backend to be checked against.

I would like to also have control over using or not of system provided certificates. Maybe it shall be configured on each proxy entry, like:

```
proxy {
  ssl_cert_file /path/to/ca-list-bundle.pem
  use_only_local_cert true
}
```

So no system provided CA would be used to validate the proxy.

_Note_: Setting Go's `SSL_CERT_FILE` and `SSL_CERT_DIR` works nicely for the whole Caddy running process, but in this case each `proxy` directive is expected to be configured separately.

What do you guys think about this approach?
Is this proposal covering enough that feature?
Do you have any tips where to start (I am just starting playing with Caddy code and generally Go)?
Are `ssl_cert_file`, `ssl_cert_dir` and `use_only_local_cert` good names?
Are there any other issues which would block this one?

**Comment by francislavoie** [comment]
@lukenowak I think what we could do is just call the option `certificates` and accept one or many arguments. Check the path to determine if it's a dir or file, and handle it as such.

If you were to add a `only_local_certificates` option, then you wouldn't need `true` as an argument because the existence of the option is enough to assume it's turned on.
