### ISSUE TITLE
Test file permissions before trying to get certificate

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#1621]
Currently caddy tries to fetch a certificate from LE and then tries to save it to a directory. This is great.

However, if the system permissions are incorrect for a directory (i.e. you're in the process of installing and testing caddy) and the system service runner restarts caddy, then very quickly LE reaches its rate limit - and then caddy fails to start at all.

It would be an even better user experience if caddy did a self-test to make sure that it can actually write to the directories that it knows it's going to want to write to.

Documentation could also be updated to encourage users to use the staging provider until they've tested that everything "works". (or have a environment variable `CADDY_ENV='dev'` or flag `--dev` which would set the default staging url `https://acme-staging.api.letsencrypt.org/directory`

**Comment by mholt** [comment]
Hi AJ,

> the system service runner restarts caddy, then very quickly LE reaches its rate limit - and then caddy fails to start at all.

When testing new setups, users should _always_ test with Let's Encrypt's staging endpoint (as specified in both the [Caddy docs](https://caddyserver.com/docs/automatic-https#testing) and the [Let's Encrypt docs](https://letsencrypt.org/docs/staging-environment/)). There's already a command line flag to change the CA URL: `-ca`.

I think this is a reasonable expectation for those who have advanced setups (i.e. those using a process manager or separate users or something) such that we don't need to add extra complexity to Caddy for this.

Thanks for the suggestion!

**Comment by francislavoie** [comment]
Just to clarify @mholt why not check for write permissions before starting regardless? I think that would be a good sanity check. If you can't write, then there's really no point in doing ACME because it's guaranteed to fail. Checking for write permissions is quite trivial, I don't think that would add complexity.

**Comment by mholt** [comment]
@francislavoie Why bother? Same error either way, less code this way. What guarantees that being able to write now means we can write later? Just get the error at the time of write.

**Comment by tobya** [comment]
Would it be useful to specify in the docs what the LetsEncrypt staging endpoint is 
eg update the docs to 

Testing, experimenting, and advanced setups
-----
To test your Caddy configuration, make sure you use the` -ca` flag to change the ACME endpoint to their staging URL `https://acme-staging.api.letsencrypt.org/directory` or your own development URL.  Otherwise you are likely to hit rate limits which can block your access to HTTPS for up to a week. This is especially common when using process managers or containers. Caddy's default CA is Let's Encrypt, which has a staging endpoint that is not subject to the same rate limits.

The link provided in the docs just goes to the LetsEncrypt homepage rather than the stageing page.
