### ISSUE TITLE
Ability to provide HTTP 1.1 clients a different version of a file they've requested  

### ISSUE THREAD

**Issue by lozandier** [mholt/caddy#163]
A feature that would be of value until HTTP/2 is more prevalent is the ability in Caddy files to declare a alternate version of specific files (inc. providing a glob pattern)  when requested by HTTP 1.x clients

The likely most common type of files would be html files; a version that utilizes former HTTP best practices such as minification, concatenation, & spriting instead of a version catering the the advantages of HTTP/2 to omit such things.

**Comment by mholt** [comment]
I'm trying to think how this would work. Have any ideas how to express this in the Caddyfile?

**Comment by mholt** [comment]
Also, it's worth noting that most major browsers already support most of HTTP/2. Any actions here I think will just be a stop-gap until people update their browsers (which isn't an issue for most people). If this turns out very easy to implement, we can consider it, so I'd still be interested in how you'd like the Caddyfile to look for this feature, otherwise I'm inclined forego this.

Plaintext HTTP will always be HTTP 1.1 (unless major vendors choose to support HTTP/2 over plaintext) but there are already ways to serve one site over HTTP and a different one over HTTPS using the Caddyfile.

**Comment by lozandier** [comment]
Yeah, I've been stuck with how it would look like to match the intuitiveness of the current API of the caddy file that's also friendly to designers & bloggers. 

Perhaps something like the following snippet demonstrates?
```
http1_redirects {
  original_file alt_file
  original_path/ alt_path/
}

```

**Comment by mholt** [comment]
I think you're on to something. This could be an add-on Caddy package that simply does redirection or rewriting... Probably rewriting, which is internal.
