### ISSUE TITLE
-validate doesn't validate if -conf is not provided, starts server instead

### ISSUE THREAD

**Issue by pekeler** [mholt/caddy#1640]
### 1. What version of Caddy are you using (`caddy -version`)?
0.10.0

### 2. What are you trying to do?

```
root@demo:~/www# caddy -validate
Activating privacy features... done.
http://foo.com
https://foo.com

^Croot@demo:~/www# caddy -validate ./Caddyfile 
2017/05/01 22:23:57 args:2 - Parse error: Unknown directive './Caddyfile'
root@demo:~/www# cat Caddyfile | caddy -validate
Activating privacy features... done.
https://foo.com
http://foo.com

^C
```

### 6. What did you expect to see?

"Caddyfile is valid" or something like that.

### 7. What did you see instead (give full error messages and/or log)?

It was starting up the server (see above).

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Ubuntu 17
```
curl https://getcaddy.com | bash -s hook.service,http.minify
mkdir www
cd www
touch Caddyfile
```

**Comment by tw4452852** [comment]
What's your `Caddyfile`'s content? Also, you should set your config with `-conf`.

**Comment by pekeler** [comment]
Why would the content matter?

```
http://foo.com {  
    redir https://foo.com 
}
https://foo.com {
    gzip
    proxy / localhost:3000
    proxy /socket.io localhost:3002 { 
        header_upstream Host {host} 
        header_upstream X-Real-IP {remote} 
        header_upstream X-Forwarded-For {remote} 
        websocket 
    }
}
```

"Caddyfile" is the default name, so why should I set `-conf`? I just tried and `caddy -conf Caddyfile -validate` works as expected, printing:
```
Activating privacy features... done.
Caddyfile is valid
```

**Comment by tw4452852** [comment]
> "Caddyfile" is the default name, so why should I set -conf?

Yes, I mean you forgot `-conf` if you set your config explicitly, like this: `root@demo:~/www# caddy -validate ./Caddyfile `

**Comment by mholt** [comment]
Tw is right: the way to use `-validate` is just `-validate`. It doesn't take any arguments. Passing an unflagged argument ("./Caddyfile") causes Caddy to treat it as [short Caddyfile](https://caddyserver.com/docs/cli#short-caddyfile) which it's not.

In other words, you use `-validate` without arguments and you can still use `-conf` to specify another Caddyfile. The first execution you had was right.

> Why would the content matter?

Because if there's a bug in Caddy, we want to know whether it's in the code path for either valid or invalid Caddyfiles (or both).

**This is a bug with the hook.service plugin.** Remove it and `caddy -validate` will work as expected. I recommend filing an issue there! https://github.com/bruhs/caddy-service/issues

**Comment by pekeler** [comment]
> Tw is right: the way to use -validate is just -validate. It doesn't take any arguments. Passing an unflagged argument ("./Caddyfile") causes Caddy to treat it as short Caddyfile which it's not.

You guys are both missing the point. `caddy -validate` doesn't work, either. Passing an argument was just me trying other ways of using `-validate`.

> This is a bug with the hook.service plugin

Aha! Now that seems likely, as I was seeing some other weirdness with that plugin. Thank you! I will file an issue there.
