### ISSUE TITLE
Caddy does not stop issuing cert requests to LetsEncrypt even on error

### ISSUE THREAD

**Issue by ohir** [mholt/caddy#1681]
Caddy 0.10.3
In case of simple misconfiguration preventing Caddy from writting new certs under CADDYPATH
Caddy restarts then tries to get certs again - wreaking havoc both for LE and unfortunate user.

It would be way better to automatically let Caddy attempt first with LE stagging area and check all needed permissions first before doing real cert request. Or at least check if Caddy is able to write
obtained certs into last part of CADDYPATH (sites/my.domain.tld).

```
Activating privacy features...2017/05/21 17:00:00 [INFO][my.domain.tld] acme: Obtaining bundled SAN certificate
2017/05/21 17:00:04 [INFO][my.domain.tld] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/AScG67GHycutdataBQRtfGFd
2017/05/21 17:00:04 [INFO][my.domain.tld] acme: Authorization already valid; skipping challenge
2017/05/21 17:00:04 [INFO][my.domain.tld] acme: Validations succeeded; requesting certificates
2017/05/21 17:00:07 [my.domain.tld] failed to get certificate: acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: too many certificates already issued for exact set of domains: my.domain.tld
```

**Comment by mholt** [comment]
Hey @ohir, 

You can use Let's Encrypt's staging endpoint to test things out very easily:

```
$ caddy -ca "https://acme-staging.api.letsencrypt.org/directory"
```

And myself and [the docs recommend always doing this for testing and experimenting](https://caddyserver.com/docs/automatic-https#testing).

While it may seem convenient to first try to write to the path, just because it can write to the path one moment does not mean it will be able to later. I recommend, if setting up a custom system configuration like this, that you are careful to use the staging endpoint and set up the system properly.

Thanks for your question!
