### ISSUE TITLE
Incorrect content type for ttf fonts

### ISSUE THREAD

**Issue by watermelonjuice** [mholt/caddy#1729]
### 1. What version of Caddy are you using (`caddy -version`)?
0.10.3

Caddy is setting content-type:application/octet-stream for ttf fonts. Correct content-type would be:
font/ttf
application/ttf
application/x-ttf
application/truetype
application/font

**Comment by francislavoie** [comment]
You can use https://caddyserver.com/docs/mime to fix this for yourself

```
mime {
    .ttf application/ttf
}

**Comment by watermelonjuice** [comment]
Yes but the whole point of caddy is that is comes with good default configuration.

**Comment by mholt** [comment]
I agree, but @francislavoie's workaround will have to do for now. Content-type sniffing is performed by the Go standard library, and TTF is not one of the format it sniffs for. (There are hundreds, no, thousands of formats -- implementing a scheme for each one is not trivial.) I'm not sure of a simple way to extend this functionality at this time, since the [sniffing algorithm is unexported](https://golang.org/pkg/net/http/#DetectContentType).

**Comment by mholt** [comment]
@watermelonjuice Is the octet-stream content-type causing malfunctions?

**Comment by watermelonjuice** [comment]
Yes it breaks cloudflare gzip

**Comment by mholt** [comment]
Had an interesting discussion about this on the Gopher Slack. Basically, fixing this would involve changing the standard lib, either just add support for TTF, or a bigger change to make the list of sniff signatures extensible. The other option is to implement our own sniffer but that's a huge maintenance burden. File extensions to determine MIME aren't recommended by the spec but I can't think of another simple workaround for now, and that will have to do. Sorry. :-/

I'm open to suggestions on how to handle this but so far I haven't found or heard of a solution I like.

I'll close this but mark the issue as "deferred" which is a tag I sometimes revisit on closed issues because I don't know how to deal with them right now and/or they aren't a "big deal" in the sense that the workaround we have works for now.

**Comment by watermelonjuice** [comment]
Can we open an issue upstream?

**Comment by mholt** [comment]
@watermelonjuice You are certainly welcome to; I have no idea how the Go members will recommend handling it, it will be interesting to see what they prefer/suggest.

**Comment by watermelonjuice** [comment]
https://go-review.googlesource.com/c/47553/
