### ISSUE TITLE
Add python-urllib2 mitm detection

### ISSUE THREAD

**Issue by kyhwana** [mholt/caddy#1741]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.4

### 2. What are you trying to do?
Detect MITM using exitmap ( https://github.com/NullHypothesis/exitmap )

### 3. What is your entire Caddyfile?
```text
https://url {                                                                                                                    │···························································································
root /root/caddyroot                                                                                                                             │···························································································
log  / access.log "{combined} {mitm}"                                                                                                            │···························································································
                                                                                                                                                 │···························································································
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
./caddy caddy.conf

### 5. Please paste any relevant HTTP request(s) here.

    try:
        data = urllib2.urlopen("https://url",
                               timeout=10).read()

### 6. What did you expect to see?
mitm logging should show unlikely. This is being run from my personal windows 10 laptop using Ubuntu/Bash for Linux VPNed to a personally run trusted VPN endpoint that shouldn't have any HTTPS MITM between it and the https://url site.

### 7. What did you see instead (give full error messages and/or log)?
IP - - [03/Jul/2017:05:58:28 +0000] "GET / HTTP/1.1" 404 14 "-" "Python-urllib/2.7" likely

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

```
User agent: "Python-urllib/2.7"
Python version (inside ubuntu/bash for windows 10): Python 2.7.12 (default, Nov 19 2016, 06:48:10)

ClientHello Bytes:
0000   16 03 01 02 00 01 00 01 fc 03 03 38 38 a3 bb fb
0010   28 d7 9a ad 95 9a 6a 20 c9 d9 3e cd 05 d6 6c e3
0020   1a 42 04 e7 4e a3 63 93 67 bc 24 00 00 94 c0 30
0030   c0 2c c0 32 c0 2e c0 2f c0 2b c0 31 c0 2d 00 a5
0040   00 a3 00 a1 00 9f 00 a4 00 a2 00 a0 00 9e c0 28
0050   c0 24 c0 14 c0 0a c0 2a c0 26 c0 0f c0 05 00 6b
0060   00 6a 00 69 00 68 00 39 00 38 00 37 00 36 c0 27
0070   c0 23 c0 13 c0 09 c0 29 c0 25 c0 0e c0 04 00 67
0080   00 40 00 3f 00 3e 00 33 00 32 00 31 00 30 00 88
0090   00 87 00 86 00 85 00 45 00 44 00 43 00 42 c0 12
00a0   c0 08 c0 0d c0 03 00 16 00 13 00 10 00 0d 00 9d
00b0   00 9c 00 3d 00 35 00 3c 00 2f 00 84 00 41 00 0a
00c0   00 ff 01 00 01 3f 00 00 00 18 00 16 00 00 13 70
00d0   61 6e 64 6f 72 61 2e 6b 79 68 77 61 6e 61 2e 6f
00e0   72 67 00 0b 00 04 03 00 01 02 00 0a 00 1c 00 1a
00f0   00 17 00 19 00 1c 00 1b 00 18 00 1a 00 16 00 0e
0100   00 0d 00 0b 00 0c 00 09 00 0a 00 23 00 00 00 0d
0110   00 20 00 1e 06 01 06 02 06 03 05 01 05 02 05 03
0120   04 01 04 02 04 03 03 01 03 02 03 03 02 01 02 02
0130   02 03 00 0f 00 01 01 00 15 00 ca 00 00 00 00 00
0140   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0150   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0160   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0170   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0180   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0190   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
01a0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
01b0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
01c0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
01d0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
01e0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
01f0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0200   00 00 00 00 00
```
unmodified User-Agent string, browser version, OS/platform details, the raw ClientHello bytes, and any other relevant build information.

**Comment by mholt** [comment]
Thanks @kyhwana for the report! As the docs state, we only support major browsers. Trying to support every HTTP client, especially ones where User-Agent headers can be easily changed (and more frequently are than in browsers) makes this a huge maintenance burden. We'd have to keep up to date with the configuration of Python's TLS stacks. (I am hesitant to even add support for the Go net/http package since, even though it is self-contained, adding more clients to track takes a lot of work to keep updated!)

I don't know anything about Python's TLS stack. But unless we recognize the user agent (which in this case, we don't), we'll show an "Unlikely" (if boolean) or "Unknown" (if string) result for unrecognizable user-agents, with only a few exceptions. One common one is if the client advertises the Heartbeat extension, then we immediately flag it as a MITM since no major browsers have _ever_ implemented the Heartbeat extension. This is the case with your ClientHello: it advertises extension 15, which is heartbeat.

At this time I am not particularly interested in expanding the detection features to more than just browsers, but if we do, now we have enough information to begin adding support for Python at least!

Hope you don't mind if I close the issue now, but feel free to continue the discussion if you'd like.
