### ISSUE TITLE
Replacement for caddydev

### ISSUE THREAD

**Issue by xuqingfeng** [mholt/caddy#1768]
Since [caddydev](https://github.com/caddyserver/caddydev) is no longer there, how can I test custom plugin easily(without modifying caddy's source code)?

**Comment by mholt** [comment]
Good question - there's not a replacement at this point; we might work on one in the future but right now, all you have to do is modify one line of code. That is much easier than installing and maintaining a separate program to do that for you. I know that @abiosoft is experimenting with https://github.com/abiosoft/caddyplug. But otherwise, I recommend just editing the file by hand for now.
