### ISSUE TITLE
rewrite if match {file} doesn't work like expected

### ISSUE THREAD

**Issue by onodera-punpun** [mholt/caddy#1794]
### 1. What version of Caddy are you using (`caddy -version`)?
`Caddy 0.10.6 (+e7f08bf Sat Jul 29 13:43:27 UTC 2017)`

### 2. What are you trying to do?
Trying to rewrite requests like `/Sn3d.jpg` to `/uploads/Sn3d.jpg` using `if {file} match...`.
So files that are exactly 4 randomized characters long, with an optional extension.

The following works:
```
rewrite {
    regexp ^/[[:alnum:]]{4}(?:\.[[:alnum:]]+)?/?$
    to /uploads/{file}
}
```

but using the a `{file}` or even `{path}` match equivalent doesn't work:
```
rewrite {
    if {file} match ^[[:alnum:]]{4}(?:\.[[:alnum:]]+)?$
    to /uploads/{file}
}
```

It seems that the `$` somehow causes this? It might also be the case that I'm a complete noob at regexp, hehe.

### 6. What did you expect to see?
A rewrited request

### 7. What did you see instead (give full error messages and/or log)?
A 404.

**Comment by mholt** [comment]
@onodera-punpun I'm seeing this too, but am unable to proceed because frankly I'm stuck. 

@abiosoft: this is strange, have you seen this before? I'm using this rewrite given above:

```
rewrite {
    if {file} match ^[[:alnum:]]{4}(?:\.[[:alnum:]]+)?$
    to /uploads/{file}
}
```

And when I `fmt.Println(rules)` in setup.go, just before `return rules, nil` [here](https://github.com/mholt/caddy/blob/e7f08bff38988c3049b7fda301c52a681af63cd8/caddyhttp/rewrite/setup.go#L105), this is the output:

```
[%!v(PANIC=runtime error: invalid memory address or nil pointer dereference)]
```

Indeed, printing out `rules[0]` shows the panic too. However, if you print rules[0] using `fmt.Printf("%#v\n", rules[0])`, you get a NON-NIL value:

```
&rewrite.ComplexRule{Base:"/", To:"/assets/{file}", Exts:[]string(nil), RequestMatcher:httpserver.requestMatchers{httpserver.IfMatcher{ifs:[]httpserver.ifCond{httpserver.ifCond{a:"{file}", op:"match", b:"^[[:alnum:]]{4}(?:\\.[[:alnum:]]+)?$", neg:false}}, isOr:false}, "/"}, Regexp:(*regexp.Regexp)(nil)}
```

(Granted, the Regexp and Exts fields are nil, but... that shouldn't break the whole thing, right?)

Can you look into this? I don't think I've ever seen this before.

**Comment by onodera-punpun** [comment]
By the way, is `if` or `regexp` more efficient than one or the other?

**Comment by slightfoot** [comment]
@matt Challenge Excepted, and fixed above.

@onodera-punpun It looks like the regex is not accepted. But I don't see why it wouldn't be. Looks valid and follows the syntax guidelines from https://golang.org/pkg/regexp/syntax/

Test I created: https://play.golang.org/p/EU1QlV91Bx

**Comment by slightfoot** [comment]
@onodera-punpun I've removed the `^$` from the regular expression and tested it in my local Caddyfile and it works. I have a singular file test.txt in uploads and a request to `localhost/test.txt` works and returns the file content.

```
localhost:80 {
	root ./
	rewrite {
	    if {file} match [[:alnum:]]{4}(?:\.[[:alnum:]]+)?
	    to /uploads/{file}
	}
}
```

**Comment by slightfoot** [comment]
aaahhh
I found the bug.

**Comment by slightfoot** [comment]
Ok, So we are left with questions on how to fix this.

1. We modify replacer to instead return the `{4}` replacement area instead of and empty value. This might help people see that they have misspelled a replacement word. But also might reveal config details. Also, doesn't stop a regex including say `{file}` in itself. Does this pose other issues?
2. Add some sort of escaping to Replacer. Does this complicate our Simple configuration? Extra things to remember?
2. Simply update IfMatcher's conditions to detect if the conditional function is `matchFunc` and not run Replacer on it. But then we can't insert replacement areas into regex? Is this desirable? Would it break current configurations?

> Replacer's key matching: https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/replacer.go#L218
> IfMatcher Conditions: https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/condition.go#L138

**Comment by mholt** [comment]
Does the Replacer need to be invoked for `match` operations? I can see why this is a problem, maybe we should not use Caddy placeholders in regular expressions.
