### ISSUE TITLE
Golang: caddy dependency management

### ISSUE THREAD

**Issue by zaolin** [mholt/caddy#1834]
Hey,

I know there are at least 5 different go package management solutions outside.
Maybe it would be possible to try https://github.com/golang/dep. It's fast
changing but it claims to be ready for production use. I am not sure if you already
thought about it. Currently the caddy CI is broken because of the quic-go package.

Best Regards, Philipp

**Comment by abiosoft** [comment]
Caddy has all dependencies checked in since https://github.com/mholt/caddy/pull/1651.

**Comment by zaolin** [comment]
yep but no replacement for package management in my opinion.

**Comment by mholt** [comment]
Thanks for the question. The vendor folder works well enough, and we use gvt to manage it. The CI tests on Windows are failing I think because `go get -t ./...` does not honor the vendor folder. (We don't vendor test dependencies anyway.) In Go 1.9, ./... will respect the vendor folder and I don't think it'll be a problem.

**Comment by elcore** [comment]
Hello Matt, 

I think we should switch to dep in the near future, as it will be part of the Go toolchain :smile:
