### ISSUE TITLE
PrivateDevices=true as recommended in the Systemd unit file causes latest caddy to silently fail

### ISSUE THREAD

**Issue by leehambley** [mholt/caddy#1853]
Skeleton issue to find out if this belongs here or at systemd. ~~I see that there's no configuration option~~, and no "maybe this is risky" in the commit message where the line was introduced.

https://github.com/mholt/caddy/blob/c026e2b734f2ecc2f23fd91cd858018473a2a6c9/dist/init/linux-systemd/caddy.service#L34

Issues I opened in other places with more information:

- https://serverfault.com/questions/871635/error-running-otherwise-working-caddy-under-systemd-v232
- https://caddy.community/t/error-running-otherwise-working-caddy-under-systemd-v232/2638

How should we proceed?

**Comment by mholt** [comment]
Hi! Thanks for posting this in a few places since you're unsure where it should go. I think that here is not the place, however. This isn't about Caddy as much as it is a configuration question about systemd. So I'm not sure how to help you, since I don't know much/anything about systemd. I'll close the issue, but please follow up in the forums if you find an answer!
