### ISSUE TITLE
Caddy is adding trailing slash to reverse proxy requests

### ISSUE THREAD

**Issue by janwerner** [mholt/caddy#1871]
Caddy is adding a trailing slash to a reverse proxy request. IMO, a trailing slash should only be passed upstream if it is part of the configuration (i.e.  proxy / 10.0.7.21:8080/sub-dir/)

### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.8

### 2. What are you trying to do?
Reverse proxying

### 3. What is your entire Caddyfile?
```text
sub.domain.com {
  proxy / 10.0.7.21:8080/sub-dir
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
/usr/bin/caddy --conf /etc/Caddyfile --log stdout

### 5. Please paste any relevant HTTP request(s) here.
http://sub.domain.com

### 6. What did you expect to see?
Content of 10.0.7.21:8080/sub-dir

### 7. What did you see instead (give full error messages and/or log)?
Content of 10.0.7.21:8080/sub-dir/ (with a trailing slash, causing a 404 error in this case)

**Comment by tobya** [comment]
Thank you for the issue.  Is this happening if you do a curl request also?  What response do you get to

    curl https://sub.domain.com

**Comment by janwerner** [comment]
Hi,
thank you for taking the issue. Here is the output to ` curl https://sub.domain.com`:


    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 404 Not Found</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 404 Not Found</h1>
            <p>Sorry, the requested URL <tt>&#039;https://sub.domain.com/youtube-dl/&#039;</tt>
               caused an error:</p>
            <pre>Not found: &#039;/youtube-dl/&#039;</pre>
        </body>
    </html>

**Comment by lbguilherme** [comment]
This is working as intended. Look:

By the spec, the resource being requested is never empty. So if you make a request to `https://sub.domain.com`, the client itself will make the request for `https://sub.domain.com/`. You can see this behavior with `curl -v 

`` 

If you make a request to `https://sub.domain.com/a` it is

**Comment by lbguilherme** [comment]
This is working as intended. Look:

By the spec, the resource being requested is never empty. So if you make a request to `https://sub.domain.com`, the client itself will make the request for `https://sub.domain.com/`. You can see this behavior with `curl -v https://sub.domain.com`

```
> GET / HTTP/2
> Host: sub.domain.com
> User-Agent: curl/7.53.1
> Accept: */*
```

So it does make sense for caddy to proxy it to `sub-dir/`, this is what it is told to do. You could however argue that would be good if caddy sees requests to `/` and treat them as if they where for na empty resource. But then, it would be odd that `https://sub.domain.com/` goes to one place and add a single letter `https://sub.domain.com/a` sends a request with two additional chars.

For most places it is responsability of the backend to treat requests ending with a slash as requests without it. In fact if you make a request for a static file such as `https://sub.domain.com/file.txt/`, it will be treated as equal to `https://sub.domain.com/file.txt`. The best approach here, IMHO, is for the backend of the proxy to treat `https://sub.domain.com/sub-dir/` as the same as `https://sub.domain.com/sub-dir`.

**Comment by mholt** [comment]
I agree with Guilherme, I think it's the responsibility of the program processing the request to figure out whether the final slash is valid or not and then adjust accordingly. As he said, Caddy will redirect clients to the proper, canonical URL when accessing static files.

So in this case, you'd have to make an HTTP request without your HTTP client adding the trailing slash. So, arguably, the error here is not with Caddy, but is with the HTTP client or the backend in this case.

[RFC 3986](https://tools.ietf.org/html/rfc3986#page-22):

> If a URI contains an authority component, then the path component
>  must either be empty or begin with a slash ("/") character.
> ...
> A path is always defined for a URI, though the
>  defined path may be empty (zero length).

So uh, I'm not exactly sure what to make of this yet. I feel like we've encountered this before and decided to have it be this way for a reason but I can't recall where (or for sure, if we did) yet...

**Comment by janwerner** [comment]
Thank you very much for you detailed answers. I will ask the app's developer then and ask him to ignore trailing slashes.

**Comment by thedodd** [comment]
**Please, guys, caddy is an awesome project, and I have been a faithful user,** but this is definitely an issue which you will see is wrong the moment you look at your filesystem path.

@lbguilherme the example that you gave is just slightly unfortunate, because it is the one example where a trailing slash may be forced and it still has an identical meaning. Requesting for the root of the domain with or without a trailing slash is still the same thing — it is a request for the root directory. However, this is strictly not the same for deeper URIs. 

The origin of the URI is based on the filesystem. `/` represents a directory. Without a trailing slash, the request would be pointing to a file (or file-like object). It is more complex than this, to be sure, with REST-based systems and virtual filesystems; but, the point holds. This is the origin of the pattern.

It **should be** up to the developer to ensure that their clients are actually pointing to the correct locations, and that if they need to redirect, or return a 404, such cases are properly handled. That is intuitively obvious. It **should not be** up to the developer, however, to handle unnecessary logic forced by a reverse proxy.

Let us consider a standard file server. We must now update all of its logic to first check if there is a directory matching the requested path (because the `/` at the end of the URI represents the root of the specified directory), and if it does not resolve to an actual directory (an OS error), then it must strip the trailing slash and look for a file matching that newly constructed path.

You can test this right now by going to any POSIX compliant OS and executing the following:

```bash
# Let's check out our .bashrc file (must not be a symlink).
ls -la ~/.bashrc # Awesome, this gives us expected output.

# Now with a forced trailing slash.
ls -la ~/.bashrc/ # Hmm ... `Not a directory (os error 20)`
```

I hope I have been able to draw attention to this issue without being too incendiary. Thanks for all of the awesome work so far. I hope we can correct this issue.
