### ISSUE TITLE
enable registering tls.Config.GetCertificate middleware

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#188]
I want to be able to create a secure static web hosting middleware that would work in this way

1. Check `/srv/www/<<hostname>>`
2. Next on fail
3. On success, serve

The issue is this would also require integration with `tls.Config.GetCertificate` (i.e. to use letsencrypt)

* Something like `Startup` and `Shutdown`

I'm working on a demo of the functionality here: https://github.com/coolaj86/golang-https-example

**Comment by coolaj86** [comment]
A starting point would be to change the `tls.BuildCertificatesForHostname` (or whatever it's called) to use `GetCertificate`

**Comment by mholt** [comment]
@coolaj86 I'm working on this right now. Go first calls GetCertificate, then uses NameToCertificate, then just uses the first element of Certificates if the first two don't return a cert.

So far I'm writing a wrapper function that will pass in both the ClientHello info and the already-built map[string]*tls.Certificate to the middleware's own "GetCertificate" so that the middleware can check the existing certificates if it wants to. (Of course, mutating the map presents a race condition... but I intend it to be used read-only.) This function will return `(tls.Certificate, error)`.

How does that sound?

**Comment by mholt** [comment]
^ Ignore all that. I've restructured the way Caddy does HTTPS.

Haven't forgotten about this, but I need to restructure the way Caddy does HTTPS one more time.

**Comment by mholt** [comment]
I'm not sure if this is still needed, now that Caddy can load an entire directory of certificates and also obtain certificates at handshake-time from Let's Encrypt.

I will close this for now, but if there is still real value in having the ability to hook into the GetCertificate callback, feel free to comment and I will reopen this to consider it again. The 0.9 rewrite (which is what all this work has been leading up to the past few months) makes it trivial to add new hooks that can be plugged into like that.

Thanks!
