### ISSUE TITLE
Where can we make documentation fixes?

### ISSUE THREAD

**Issue by edbrannin** [mholt/caddy#1940]
The README says:

> If you want to contribute to the documentation, please submit pull requests to caddyserver/website.

...but https://github.com/caddyserver/website is a 404.  Where should we go to help improve the docs?

---

Root cause: The `log` & `error` docs have some duplicate content that's really only suited for one or the other.  Examples in the [log](https://caddyserver.com/docs/log) docs:

- I haven't gone code-diving, but this part seems only meaningful for the `error` module.

    > `visible` to write the error (including full stack trace, if applicable) to the response (NOT recommended except for local debugging)

- The default logging location is `access.log` according to one paragraph, and `stderr` according to another.

**Comment by francislavoie** [comment]
Unfortunately during the rewrite of the website and restructuring of the "products", that repo had to be made private. For now, @mholt will make the changes himself. I also hope we get the docs back as a public repo to lighten the load on @mholt to maintain that.

**Comment by lmcmenemie** [comment]
:+1:

**Comment by omz13** [comment]
@matt, Is there an easy way to submit changes for the documentation? Could you at least modify the README? Just asking as I have a few nits and clearly it would be preferable to submit a pull request...

**Comment by francislavoie** [comment]
@omz13 that's the wrong Matt, it's @mholt :wink:

**Comment by omz13** [comment]
@francislavoie - Oops, fat fingers on my end. Thanks for spotting it.

**Comment by mholt** [comment]
There isn't right now, so just comment here I guess and I'll get around to it. Unless it's a big change, open a separate issue.

**Comment by lmcmenemie** [comment]
This one's been bugging me for a while. ^^

This sentence on [/docs](https://caddyserver.com/docs) doesn't make sense on narrow screens where the navigation moves under the main content.
![caddydocs](https://user-images.githubusercontent.com/1199268/37995082-401b015e-320b-11e8-875f-23d243ab43ff.png)

**Comment by mholt** [comment]
Ah, right. I will see what I can do about that.

**Comment by omz13** [comment]
A few nits to correct if possible:

For [tls](https://caddyserver.com/docs/placeholders), can you kindly add that ```self_signed``` results in a certificate being generated that only has a lifespan of 7 days, and it is NOT automatically renewed (because it is intended for development and testing and not for production use!)

For [placeholders](https://caddyserver.com/docs/placeholders) can you include ```tls_protocol``` and ```tls_cipher``` that were added in #2062 and released in v0.10.12

For [fastcgi](https://caddyserver.com/docs/fastcgi) can you add that for secure connections, the environment variable HTTPS is set, and as per #2062, also SSL_PROTOCOL and SSL_CIPHER, in a manner compliant with apache's mod_ssl.

For [errors](https://caddyserver.com/docs/errors) can you add that when using ```file```, it really is a a static file and that it is not possible to chain a templated file.

For [cli](https://caddyserver.com/docs/cli) could you perhaps explain a bit more the process to upgrade caddy via ```USR2```. For ```USR1```, can you add that caddy is only restarted if the reloaded configuration has no errors (but correct me if I'm wrong!)

**Comment by mholt** [comment]
@omz13 Done - thanks! Will go out with the next site update.

**Comment by mholt** [comment]
And I've fixed the items mentioned in the @edbrannin's OP. Thanks!
