### ISSUE TITLE
Non standard ssl port issue

### ISSUE THREAD

**Issue by bigtan** [mholt/caddy#195]
I try to make caddy a frontend for my apache2 server which will host a wordpress site.

I configure the apache with ssl on non standard port which is port 444, which means I can view my website through https://mydomain.com:444. It works well.

Then I make caddy listen port 443 and configure it to proxy https://mydomain.com:444 and I set the Host to mydomain.com, as I expected, when I enter the url https://mydomain, caddy will accept it and pass it to https://mydomain.com:444 and the apache server will finish the request and return the content with a host of mydomain.com. But caddy report an error `502 Bad Gateway` and the error from the `errors` told me `[ERROR 502 /index.php] unreachable backend`

I was confused about that.

I try to remove the ssl from caddy to apache server, it works by some degree, but the apache server return the host mydoaim.com in http scheme, which will lead to a warning in browsers such as chrome.

Help wanted.

Yours

**Comment by bigtan** [comment]
I think the key point is, whether caddy support `proxy / https://mydomain.com:444`, Maybe it is not.

**Comment by mholt** [comment]
Do you see any output in the console like this?

```
2015/07/20 12:26:15 http: TLS handshake error from 127.0.0.1:55519: remote error: bad certificate
```

Anyway, I was able to duplicate the error, but I'm using a self-signed certificate for testing purposes. In the browser you can bypass the warning, but Caddy is not programmed to bypass certificate errors.

As for the Host in the response, I may need to tweak some proxying headers. Let me know about the console error messages and if your certificate is trusted or self-signed.

**Comment by bigtan** [comment]
Not at all. I didn't see such errors. All the errors I say is that the backend unreachable. 

BTW: I use COMODO ssl certificate. And the site works well from the Internet when access by https://mydomain.com:444. And when I change the `proxy / https://mydomain.com:444` to `proxy / https://www.google.com` it works well too.

**Comment by mholt** [comment]
Well, I'm stumped. I can't reproduce this error. If you'd like, I could use your same domain name as you are using and try to see what's going on. You may email your Caddyfile to me or we can set up a time for a chat on my private server.

**Comment by mholt** [comment]
Also, what version of Caddy are you using?

**Comment by bigtan** [comment]
The latest release version.

**Comment by mholt** [comment]
@bigtan Okay. Well, this is really bothering me. I'd like to see exactly what you're seeing (since I can't seem to reproduce the same problem). Would you like to show me? Feel free to start a private chat at [matt.chat](http://matt.chat) and if I'm not online, send me an email or something and we can schedule a chat if you'd like.

**Comment by pschlump** [comment]
I think that I am having a similar problem.  This is with SSL termination at the Caddy server.
Caddyfile:
https://localhost:2023 {
	tls ./key/cert.pem ./key/key.pem
	log ./log/access.log
	root ./www
	jsonp /status.json
	proxy /api/status http://localhost:8204/ {
		proxy_header X-Caddy-When-TLS server-{when}
	}
}
Request in Chrome on Mac result in a file download of an empty file and an error on the server of:

      2015/09/11 11:08:09 http: TLS handshake error from [::1]:60201: tls: first record does not look like a TLS handshake

I am using self signed certificates for Caddy.

This may be a different problem.

**Comment by mholt** [comment]
@pschlump Your proxy backend is explicitly defined as plaintext http: `http://localhost:8204/` - so I doubt a HTTPS connection is being made.

@bigtan I know it's been, like, 5 months, but are you still having this problem? :smile:

**Comment by vibhavp** [comment]
I was able to reproduce this too. 
Caddyfile and the faulty URL: https://gist.github.com/vibhavp/d50e5bd1f7147a6e7e71

Here's the error log:
06/Mar/2016:20:10:39 +0530 [ERROR 502 /openidcallback] unreachable backend
192.168.1.1 - [06/Mar/2016:20:10:39 +0530] "GET /openidcallback?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198038988384&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198038988384&openid.return_to=https%3A%2F%2Fvibhavp.duckdns.org%3A8080%2Fopenidcallback&openid.response_nonce=2016-03-06T14%3A40%3A32Z2kCZcG3RAl0wbFUAsnK7b68fgzM%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=9kFCjPl5%2BW9izO%2FpK31PteM3X7c%3D HTTP/2.0" 502 16

However, visiting this URL again works:

192.168.1.1 - [06/Mar/2016:20:20:18 +0530] "GET /openidcallback?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198038988384&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198038988384&openid.return_to=https%3A%2F%2Fvibhavp.duckdns.org%3A8080%2Fopenidcallback&openid.response_nonce=2016-03-06T14%3A40%3A32Z2kCZcG3RAl0wbFUAsnK7b68fgzM%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=9kFCjPl5%2BW9izO%2FpK31PteM3X7c%3D HTTP/2.0" 500 47


(that 500 is due to a faulty query, and not caddy)

**Comment by mholt** [comment]
@vibhavp Could you open a new issue and follow the bug report template? Strip out anything unnecessary for reproducing the bug, and we'll see if that makes it any easier. Make sure you give us enough specific info to reproduce it easily. Thanks!
