### ISSUE TITLE
Shorthand :<port> syntax stopped working

### ISSUE THREAD

**Issue by benjamin-demarteau** [mholt/caddy#2035]
### 1. What version of Caddy are you using (`caddy -version`)?
```
➜  ~ caddy --version
Caddy 0.10.11 (unofficial)
```

### 2. What are you trying to do?
Run a development server using Caddy.

### 3. What is your entire Caddyfile?
```text
:8001
tls self_signed
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
```
caddy
```

### 5. Please paste any relevant HTTP request(s) here.
```
➜  ~ curl https://localhost:8001
curl: (35) error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```

### 6. What did you expect to see?
A 404 error

### 7. What did you see instead (give full error messages and/or log)?
```
curl: (35) error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

```
caddy -conf <(echo ":8001\ntls self_signed")
```

### 9. What I'm actually complaining about

Caddy used to work correctly when binding to a port without a domain (`:8001` would bind to both localhost and my network name allowing others in the office to access the webserver, it has stopped working in the last release. You have to specify `localhost:8001` instead, which is not what I want, and it still binds correctly but only provides valid responses if querying localhost:
With `:8001`
```
➜  ~ curl -k https://bede.yelido.net:8001
curl: (35) error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
➜  ~ curl -k https://localhost:8001
curl: (35) error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
With `localhost:8001`
```
➜  ~ curl -k https://localhost:8001
404 Not Found
➜  ~ curl -k https://bede.yelido.net:8001
curl: (35) error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```

**Comment by mholt** [comment]
Ah, yes, this is one of the edge-case, minor, breaking changes that is intentional in 0.10.11. Caddy now raises a TLS alert when a certificate is not available for a hostname, when SNI is used. Raising a TLS alert in that case is the more correct thing to do -- however, in your case I can see why it raises an eyebrow.

We need to look at _why_ there is no certificate available. Before this version, you just got lucky in that Caddy was serving up a "default" certificate because it couldn't find one that matched. (The certificate was made for "" but needs to match "localhost". The "bug" I suppose is that Caddy should fall back to certificates keyed by "" in the event there are no other matches, since the only way that could happen is if using a self-signed or manually-managed certificate -- trusted CAs won't issue certificates with an empty hostname.)

When SNI is used by the client, there must be a certificate available (or obtainable) for that hostname, otherwise Caddy serves a TLS alert. If SNI is not used, Caddy will try to serve a "default" certificate. But we may remove this fallback behavior in the future as SNI becomes more popular.

Anyway, I've just made a change locally that will fall back to a certificate with an empty hostname and it does what you expect. I can push that soon and you can build from source to try it out. How's that sound?

**Comment by benjamin-demarteau** [comment]
That's sounds perfect, thanks for the quick diagnostic and answer!

**Comment by skorokithakis** [comment]
Hmm, why not have the default behavior be that Caddy always serves a certificate if self_signed is used? That's what I would expect, I'm using `self_signed` because I always want a cert, any cert.

**Comment by mholt** [comment]
@skorokithakis We more or less do that with my latest commit to #2037 -- feel free to give it a try!

**Comment by skorokithakis** [comment]
Will do, thanks!

**Comment by benjamin-demarteau** [comment]
The issue is probably more complicated that I think it is, but since caddy already generates and signs certificates on the fly and we provided `self_signed`, I would think it should apply, just without the roundtrip to get it signed by LE.
