### ISSUE TITLE
Placeholder for Caddyfile Snippets

### ISSUE THREAD

**Issue by firedrow** [mholt/caddy#2042]
I love the new Snippets feature in 10.11, but I would like to suggest the ability to use placeholders in the Snippets feature for Caddyfile.  It would be great to setup a generic block for all/most of my sites with 

```
gzip
tls my@email.com
log {hostonly}_access.log
error {hostonly}_error.log
```

So my access and error logs are split up by subdomain.

**Comment by francislavoie** [comment]
I'm pretty sure that placeholders can't be used at that point in the application because they're only defined after the Caddyfile is parsed. What could be possible though is have arguments for the snippet. Syntax for that would need to be defined. As-is, snippets are just syntax sugar for copy-pasting chunks of directives.

**Comment by eauchat** [comment]
It would really be great, as @francislavoie says it to be able to pass arguments to snippets.   
For example, in the following example, passing arguments like path, and port number would allow to simplify a lot the caddyfile, having snippets like the following:

```
(forwardToVmName) {
    proxy <variablePath> vmName:<variablePort> {
        transparent
        insecure_skip_verify
        ...
    }
}
```

**Comment by francislavoie** [comment]
@eauchat it would probably be better to open a new issue as a formal feature request for this

**Comment by eauchat** [comment]
@francislavoie 
> @eauchat it would probably be better to open a new issue as a formal feature request for this
done: new issue #2408
