### ISSUE TITLE
Caddy server shown by nmap despite -Server being set

### ISSUE THREAD

**Issue by MatthewVance** [mholt/caddy#2043]
### 1. What version of Caddy are you using (`caddy -version`)?
0.10.10

### 2. What are you trying to do?
Surpress server header

### 3. What is your entire Caddyfile?
```text
bind server_name:443

tls self_signed {
                protocols tls1.2
}

proxy / localhost:8080 localhost:8081 {
                policy round_robin
                health_check /
                transparent
                except /static
                max_conns 1024
}

root ./app/public

ext .html

# use gzip compression if the client supports it.
gzip

mime {
                .js application/javascript
                .pptx application/vnd.openxmlformats-officedocument.presentationml.presentation
}

log / ca-app/logs/access.log {
                rotate_size     5      # Rotate after the log file reaches this size (in megabytes)
                rotate_age      90      # Keep rotated files for this many days
                rotate_keep     40      # Keep at most this many log files (older files get pruned)
                #rotate_compress        # compress rotated log files. gzip is the only format supported.
}

errors ca-app/logs/error.log {
                404 ./static/exceptions/404.html            # Not Found
                500 ./static/exceptions/500.html            # Internal Server Error
                * ./static/exceptions/default_error.html    # catch-all error page
                rotate_size     5      # Rotate after the log file reaches this size (in megabytes)
                rotate_age      90      # Keep rotated files for this many days
                rotate_keep     40      # Keep at most this many log files (older files get pruned)
                #rotate_compress        # compress rotated log files. gzip is the only format supported.
}

header / {
                # Enable HTTP Strict Transport Security (HSTS) to force clients to always
                # connect via HTTPS (do not use if only testing)
                # Strict-Transport-Security "max-age=31536000;"
                # Enable cross-site filter (XSS) and tell browser to block detected attacks
                X-XSS-Protection "1; mode=block"
                # Prevent some browsers from MIME-sniffing a response away from the declared Content-Type
                X-Content-Type-Options "nosniff"
                # Disallow the site to be rendered within a frame (clickjacking protection)
                X-Frame-Options "DENY"
                # Hide server header field
                -Server
                # Disable caching since https
                # The cache should not store anything about the client request or server response.
                Cache-Control "no-store"
                Pragma "no-cache"
}

# Better manage server connectivity in the face of buggy or malicious clients.
timeouts {
                read   10s # Maximum duration for reading the entire request, including the body.
                header 10s # The amount of time allowed to read request headers.
                write  10s # The maximum duration before timing out writes of the response.
                idle   2m # The maximum time to wait for the next request (when using keep-alive).
}

# Limit the HTTP header and body sizes to reasonable values
# Increase if legitimate traffic results in HTTP 413 errors
limits {
                header 4kb
                body   / 500kb
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
.\caddy.exe --conf=".\app\Caddyfile"

### 5. Please paste any relevant HTTP request(s) here.
nmap -p 443 -T4 -A -v server_name

### 6. What did you expect to see?
Caddy server information to be hidden.

### 7. What did you see instead (give full error messages and/or log)?
NMAP showed  "http-server-header: Caddy"
![caddy-nmap](https://user-images.githubusercontent.com/2671546/36507523-8f5d11fa-171f-11e8-9e7e-74aa6ce02c53.png)

However, http response did not include the Caddy server header.
![caddy-response](https://user-images.githubusercontent.com/2671546/36507555-ac4747a4-171f-11e8-9950-2fea21eceb84.png)

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Run Caddy with `-Server` in header and then check it via `nmap -p 443 -T4 -A -v server_name`.

header / {
                -Server
}

**Comment by whitestrake** [comment]
Well, the `Server` header definitely isn't being sent.

What does `nmap` actually use to point the finger at Caddy, exactly? I can't find any references to Caddy in their source code, and I'm not familiar enough with the program itself to make any judgements.

As far as I know, the only part of the response from Caddy that includes the word "Caddy" is the self-signed certificate itself.

**Comment by mholt** [comment]
The Server header does get set in the HTTP response, I think is what he's saying, but not the HTTPS response. It's a side-effect of how HTTP->HTTPS redirects are done. As a workaround, you can define the HTTP variant of your site and do the redirect yourself and also include the `-Server` header configuration there.

Closing this since it's a duplicate of #1926, actually.

**Comment by whitestrake** [comment]
@MatthewVance 

I looked in to this a little bit further since I was sure you were on to something. I was certain it wasn't a duplicate of #1926, since in my testing I used no HTTP->S redirection.

Here's what I reproduced the issue with:

```
https://localhost:18443 {
  tls self_signed
  header / -Server
}
```

While I was pulling my hair out over `nmap`, `openssl`, `curl`, and Caddy logs, @mholt helpfully suggested that undefined hostnames on the listener might be the culprit... And he was spot on. When checking `127.0.0.1` instead of `localhost`:

```
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 421
< content-type: text/plain; charset=utf-8
< server: Caddy
< x-content-type-options: nosniff
< content-length: 57
< date: Tue, 20 Mar 2018 00:50:01 GMT
<
421 Site 127.0.0.1:18443 is not served on this interface
* Curl_http_done: called premature == 0
* Connection #0 to host 127.0.0.1 left intact
```

So we have "leaked" the `server` header, because the hostname is undefined and therefore not configured to strip that header.

After testing with:

```
https:// {
  tls self_signed
  header / -Server
}
```

And the flag `-https-port 18443`, turns out `nmap` is now unable to detect the httpd version:

```
PORT      STATE SERVICE     VERSION
18443/tcp open  ssl/unknown
```

So to conclude, while it wasn't strictly the same issue as #1926, it's highly related - instead of leaking the header via automatically-configured HTTP listener, it was leaking via undefined hostnames.

**Comment by SodaWithoutSparkles** [comment]
I came across the issue myself today with caddy `v2.6.2`. I tried the solution...

```
https:// {
  header -Server
}
```
...which did not work for me. It turns out I have to delete `:443` from my default site...

```
(common) {
        header {
                -Server
                ...
        }
}
:443, server_name1, server_name2 {
        import common
        ...
}
```

...and replace it with `https://`. It now looks something like this...

```
https://, server_name1, server_name2 {
        import common
        ...
}
```

Also, I have added this for port 80...

```
http:// {
  header -Server
}
```
`nmap` now cannot identify Caddy. 
![image](https://user-images.githubusercontent.com/64138578/210779252-73a400ee-4994-4e82-b032-7bc8287493e8.png)

_I'm sorry if this pings anyone. I encountered this issue and went to google for answers. Since this answer is so old, I want to document my solution for a newer version_

**Comment by francislavoie** [comment]
FWIW, knowing which software is serving content is not a security risk in any way. If it was, we wouldn't include the header at all.

**Comment by SodaWithoutSparkles** [comment]
I think it is worth it, to a certain extent. The server information could be used to fingerprint specific server(s), and/or launch an attack on specific servers with a known vulnerability. This happens rarely tho. I just want to provide less information to my clients.

**Comment by francislavoie** [comment]
That's not true. If attackers wanted to determine which software is being used, they could watch timing patterns or TLS handshake byte structures to make assumptions. 
The `Server` header doesn't make it any easier.

The typical issue is that some software's `Server` header includes version information, but Caddy's doesn't report any version information. It doesn't reveal _any_ information at all that an attacker couldn't otherwise trivially determine.

I reiterate, if there was a legitimate concern of information leakage from having the `Server` header in responses, Caddy would not be setting the header. But there is no risk. It does help with debugging in situations where you want to make sure you're hitting the actual server you think you are, so we do include it.

**Comment by mholt** [comment]
Yeah. Even showing version information isn't a security vulnerability :man_shrugging:

Server headers are absolutely useful for broad Internet measurements, which are valuable; and are helpful with everything from debugging and troubleshooting to even benign curiosities.

Attackers will get the information they want or need whether you set the Server header or not. Especially since the Server header can lie. Actual behavior does not lie, so instead of asking "Hey are you vulnerable?" they'll just skip that and try and exploit.
