### ISSUE TITLE
Adding an option to pickup between 1000 and 1024 (bi) in unit byte

### ISSUE THREAD

**Issue by hdid** [mholt/caddy#206]
I'm using caddy for browsing directories and it seems that caddy uses 1000(ⁿ) bytes in calculating files size.
Is it possible that add an option to choose 1000 or 1024 calculation (kibi, mebi, gibi,...) in "browse" mode?

**Comment by mholt** [comment]
Yeah, we can do that.

@pyed What do you think? I ask because you use the browse feature a lot. All we need to do is change the function call here from Bytes to IBytes: https://github.com/mholt/caddy/blob/a585379bbb1876b8c67dbfef844a5b10e6b97e48/middleware/browse/browse.go#L124-L126

Perhaps the template should be able to choose (like with a `HumanISize` function?) or maybe the user's locale from the request headers? Or maybe via query string. There are several ways to do this. What would you think is best?

**Comment by pyed** [comment]
I don't see the need of having this as an options, using `IBytes` SGTM ¯\_(ツ)_/¯

**Comment by hdid** [comment]
Thank you for update.

**Comment by mholt** [comment]
@hdid This is going out today on the next release. Thanks for the suggestion!
