### ISSUE TITLE
Support Exact Match with Static Directive

### ISSUE THREAD

**Issue by ckeeney** [mholt/caddy#2060]
I use Caddy as a static file server in front of a few different backend servers including a php-fpm, django, and wordpress server.

the `status` directive has syntax `status code path`, where the [docs](https://caddyserver.com/docs/status) say 

> **`path`** is the base request path to match.

I am running Caddy containers in Google Kubernetes Engine, and the default health check for web services is that a request to `/` returns a `200`-`399` response.  I have some containers that only handle traffic at `/some-path/*`.  `status 200 /` returns an empty-response 200 for all paths including `/some-path/foo`.  If there was a way to specify that this is an exact match, the `status` directive would nicely answer health checks.

**Comment by Whitestrake** [comment]
The status package uses a `httpserver.ConfigSelector`, so this should be doable by giving `Rule` a custom `Match` function, right?

Incidentally, a workaround in the meantime - since `rewrite` executes before `status` - is to rewrite under the exact circumstances you want, to some unlikely URI (e.g. `/rewrite-status-200`) and then use `status 200 /rewrite-status-200`. Rewriting on an exact path can be done with `if {path} is /`.

**Comment by ckeeney** [comment]
Thanks for the workaround suggestion.  I solved it by just dropping an empty `index.html` file in my root.

**Comment by Whitestrake** [comment]
I am looking into writing an `ExactMatcher` (to put next to the [existing PathMatcher](https://github.com/mholt/caddy/blob/13dfffd203102fe21b454df756d9e4296fe75cfd/caddyhttp/httpserver/path.go#L61-L62)?), and then using that instead of the `PathMatcher` whenever an exact match is required.

How do we want to signify the need for an exact match? I was thinking `status 404 /secrets exact` or `status 404 { /secrets exact }`?

**Comment by ckeeney** [comment]
I don't have a strong opinion on the syntax right now, but does Caddy allow for relative paths in the status directive?  Hopefully not, but if so, I'm not sure how your syntax would work.  It seems it would cause a collision with someone wanting to literally match the path `exact`.  

If there is any such collision, I think requiring an absolute path and using your syntax is clean.  I can't imagine a real-world use case for the problematic relative paths I'm describing, but I know removing a feature is not something we could take lightly.

**Comment by Whitestrake** [comment]
It wouldn't collide. The word `exact` would need to be the last argument on each line and would require each previous argument to be present, e.g. `status 404 exact exact`. Although, that would never work, as `r.URL.Path` should never equal `exact`, only perhaps `/exact`.

**Comment by Whitestrake** [comment]
Alternately, https://github.com/mholt/caddy/pull/1948 would provide the required capabilities, and even uses `status` as an example.

**Comment by ckeeney** [comment]
Your syntax is definitely cleaner, but I agree #1948 solves this issue as well.

As I said before, I'm not too picky about the syntax as long as the feature is supported one way or another.  If #1948 gets merged in, I think this issue could be closed.

**Comment by mholt** [comment]
This should be a non-issue in Caddy 2.
