### ISSUE TITLE
Support ACMEv2, LetsEncrypt Wildcard certificates

### ISSUE THREAD

**Issue by sinni800** [mholt/caddy#2067]
This just in, wildcard support is live!

https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

The used ACME library, lego, apparently doesn't support ACMEv2 yet, an open issue exists: https://github.com/xenolf/lego/issues/457. This issue should track ACMEv2 support in the used ACME library for now

**Comment by francislavoie** [comment]
@Lemmmy see the dns provider plugins such as https://caddyserver.com/docs/tls.dns.cloudflare, lots of DNS vendors support APIs for configuration now. Wildcard certs would probably only work with Caddy if you have one of these set up. Otherwise it would probably have to use On-Demand TLS https://caddyserver.com/docs/automatic-https#on-demand, correct me if I'm wrong @mholt ?

**Comment by mholt** [comment]
Yes - the DNS challenge will be required to obtain a wildcard certificate, but this is [easy to set up](https://caddyserver.com/docs/automatic-https#dns-challenge) and is entirely automated, so don't worry. Just a line in the Caddyfile and some environment variables with your DNS provider account credentials.

On-Demand TLS is an orthogonal concept/feature. DNS challenge is _how_ to obtain the certificate, and on-demand TLS is _when_ to obtain it. You can use both together or not at all. But both would have to be enabled, as they're not default. (They also serve what we consider to be advanced use cases, so it's OK to not be on by default.)

**Comment by sinni800** [comment]
So, will wildcard certs be bound to *.domain blocks, is that going to be the way to use this?

**Comment by mholt** [comment]
@sinni800 

> So, will wildcard certs be bound to *.domain.tld blocks implicitly, as long as DNS verification is configured?

Yes

**Comment by tbure** [comment]
why  not set caddy generate Wildcard certificates is  default?

**Comment by mholt** [comment]
@tbure Read this: https://gist.github.com/joepie91/7e5cad8c0726fd6a5e90360a754fc568

**Comment by francislavoie** [comment]
To add onto that, requires using the `dns` plugins to let Caddy prove that the user has control of the domain. Not something that can be _fully_ automatic to the same level as using the HTTP challenge, so I don't think it can ever be the default.

**Comment by skorokithakis** [comment]
Will there be some support to add the `tls { dns <whatever> }` stanza to the top-level config scope for wildcard certificates? Since they only need to be generated once, it would be a bit cumbersome/useless to have to specify the same stanza per subdomain, but I'm probably missing how this will actually work when Caddy does get support for wildcard certs.

**Comment by mholt** [comment]
@skorokithakis The Caddyfile doesn't have any "global" scope, but you can use snippets to share common config across sites. The announcement blog post has an example of doing just this. (I've already written it, because it will probably go out this week!)

**Comment by skorokithakis** [comment]
Ah, fantastic, thanks @mholt!
