### ISSUE TITLE
COSP Must staple support

### ISSUE THREAD

**Issue by rugk** [mholt/caddy#2081]
https://scotthelme.co.uk/ocsp-must-staple/

It would be nice if you could support that in Caddy. Basically it is just a small change in the CSR, you give to the CA.
But for security reasons, it has a big impact, as it basically is the only way to use OCSP in a way, in which it makes sense.

Of course, it must be opt-in, as with that feature you depend on the uptime of the CA's OCSP resolver. (small downtimes are okay thanks to server caching, but longer ones can cause problems.) 

Also please, don't do it like other webservers (nginx, Apache), which only fetch OCSP at the start of the first request -> so that the first request to the server fails, and you need to reload the page to get a connection without an error.

**Comment by mholt** [comment]
Caddy does support it. :)  See [the tls docs](https://caddyserver.com/docs/tls) for `must_staple`.

Caddy's OCSP stapling implementation is already widely-known to be the best and most robust on the market.

See: https://gist.github.com/sleevi/5efe9ef98961ecfb4da8#gistcomment-2336055

Also see: https://gist.github.com/AGWA/1de6c26be5396f7cbce7ee016302d684

More:

- https://twitter.com/caddyserver/status/957505516535599104
- https://twitter.com/sleevi_/status/950298487593291776
- https://twitter.com/mholt6/status/865686542232178688
- https://twitter.com/sleevi_/status/854535507174449152

**Comment by rugk** [comment]
Uups, sorry, just did not find an issue for that. Great, in any case!

**Comment by fazlurr** [comment]
Hello, i had some problem with Caddy v1.0.3

I know this issue maybe solved on the new versions
But for some reason, we cannot upgrade our caddy version yet, cause it will cause some downtime on our production server

The problem is, every time  Caddy process the OCSP staple, our Caddy server become stalled, like freezing for 2-3s, sometimes even longer.
But if we soft reload the Caddy service, it will run smooth again.
I thought it's because our Caddy service handle TLS for all our customers domain, and when the OCSP staple is occuring, the Caddy service become stalled.

Is there anyway to make OCSP staple process not affecting our server's performance? without the need to upgrade to v2?

Thank you

**Comment by mholt** [comment]
I haven't looked at Caddy 1 code in about two years, and I haven't really heard of that issue. Upgrading to Caddy 2 will likely solve the problem though since I've never heard of that with Caddy 2, and we have way more Caddy 2 users. Caddy 1 is no longer supported.
