### ISSUE TITLE
Extend ipmask directive to error logs

### ISSUE THREAD

**Issue by Gunni** [mholt/caddy#2084]
Note that this is a feature request, not an issue or bug.

### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.11 (unofficial)

### 2. What are you trying to do?
Have consistent logs with no privacy violations.

### 3. What is your entire Caddyfile?
Relevant part:

```
log / stdout "\"when\": \"{when_iso}\", \"id\": \"{request_id}\", \"src_prefix\": \"{remote}\", \"scheme\": \"{scheme}\", \"proto\": \"{proto}\", \"host\": \"{host}\", \"status\": \"{status}\", \"path\": \"{path}\"" {
	ipmask 255.255.0.0 ffff:ffff:ffff:ffff::
}

errors stderr

request_id
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`/usr/bin/caddy -conf /etc/caddy/caddy.conf -log stdout -root /tmp -quic -agree`

systemd runs it, journald catches stdout and stderr.

### 5. Please paste any relevant HTTP request(s) here.
ssllabs scan, and a normal browser, see logs

### 6. What did you expect to see?
Error logs should filter ips, and to be frank, be formattable...

### 7. What did you see instead (give full error messages and/or log)?
    2018/03/26 03:29:49 http: TLS handshake error from [2001:db8:1020:4202::ac10:826b]:59062: EOF
    "when": "2018-03-26T04:05:54Z", "id": "813a9f4a-ed5d-47ee-adf2-bbde289f59f3", "src_prefix": "2001:db8:58c::", "scheme": "https", "proto": "HTTP/2.0", "host": "example.com", "status": "304", "path": "/"

### 8. How can someone who is starting from scratch reproduce the feature as minimally as possible?
Put the above config on any domain block that doesn't already have them.

**Comment by mholt** [comment]
Thanks for opening the issue!

I'm not sure we can change that particular log example you show, since the Go standard library generates it internally. You should open this issue in https://github.com/golang/go.

I'm afraid that when it comes to the Caddy process log, your best bet for now is to just purge them often if you are required to do that because of privacy laws (make sure they actually apply to you first!).

We can revamp the logging to be entirely under our control and discard any of the Go standard library's logs, but it's not on my roadmap anytime soon, especially not for free. If a business has this need and is willing to pay for it to be expedited, I can get it done.

**Comment by Gunni** [comment]
The reason i filter ips out is not due to laws, just my preference due to never needing them. I did seriously consider skipping them completely but kept them in out of habit, but filtered the host part.

Could you not, for example wrap the function that prints those messages with a search and replace for ips or similar? Maybe a start?

**Comment by mholt** [comment]
Caddy 2 (currently in beta) has filters that can be applied to all the logs, including the ability to mask IP addresses.

**Comment by mholt** [comment]
This has been merged and is going out with Caddy 2 beta 7 today. Check out the docs in the wiki and give it a try! You can mask IP addresses with a fine degree of control for any modules and logs.

**Comment by mholt** [comment]
@Gunni This has been merged and is going out with Caddy 2 beta 7 today. Check out the docs in the wiki and give it a try! You can mask IP addresses with a fine degree of control for any modules and logs.
