### ISSUE TITLE
Caddy server not serving QUIC

### ISSUE THREAD

**Issue by purplehorse** [mholt/caddy#2194]
I'm setting a caddy server (-quic) with caddyfile:

```
:11220 {
  tls self_signed
}
```

And I have quic enabled in chrome. But when I try to access to the server:

![image](https://user-images.githubusercontent.com/39902415/41029239-794322a2-697b-11e8-8d7d-0cd80d1d3128.png)

All I get is TLS 1.2 when I should get QUIC

**Comment by midzer** [comment]
This might be related to https://github.com/mholt/caddy/issues/2049

**Comment by mholt** [comment]
We also haven't updated the QUIC library in a while, since it adds too much code bloat: https://github.com/lucas-clemente/quic-go/issues/1353 -- once that gets resolved though, I suspect we can get it updated! (It needs regular updates since Chrome only works with basically the latest version.)

Will close this for now, since not much we can do about it at this point.

**Comment by marten-seemann** [comment]
QUIC requires an SNI, so you'll need a domain name for this, it won't work when connecting to an IP address.

**Comment by mholt** [comment]
Ah, good to know. :) Thanks!

**Comment by kalitine** [comment]
Same issue for me. I'm using:

Ubuntu 18.10
Caddy: 0.11.1
Chrome 73

I run caddy with the command:
```
caddy -quic -conf caddy.conf
```

My `caddy.conf` file is: 
```
localhost:443

root dist/hackathon-prototype

tls ssl/localhost.crt ssl/localhost.key
```

The certificate is valid, i.e. `https://localhost` is working without security warnings, but Chrome still receives files over http2 instead of QUIC, despite that the response contains: `alt-svc: quic=":443"; ma=2592000; v="44,43,39"` header.

**Comment by whalehub** [comment]
@kalitine It's working fine for me personally. Can you verify if port 443/udp is opened in your firewall and then try again? That it what initially caused it for me not to work because I assumed it worked over TCP like TLS 1.3.

**Comment by kalitine** [comment]
@whalehub Thanks, but I'm using a fresh install of Ubuntu without any firewall. I'm out of idea. It looks like a did nothing special, just a fresh Ubuntu system and default parameters. The only difference I see is that I'm serving from the localhost, but I managed the certificate to work with http2 and tls1.2 without problem.

**Comment by whalehub** [comment]
@kalitine Can you post the public portion of the certificate here so I can have a look at it?

**Comment by kalitine** [comment]
In a nutshell I became a (tiny) Certificate Authority, by generating a private key and a root certificate, imported the root certificate into Chrome. Then I created a server certificate which I signed with my CA key. Here is the screenshot of what Chrome shows me. Is that what you asked?

![certificate](https://user-images.githubusercontent.com/6207427/50784276-75697b00-12ad-11e9-94be-72ab372b5d98.png)

![certificate_2](https://user-images.githubusercontent.com/6207427/50784280-77cbd500-12ad-11e9-9c2b-9c73fc70f7f9.png)

**Comment by whalehub** [comment]
@kalitine That would be why QUIC is not working for you. It requires a valid certificate, e.g. one that is not self-signed.

**Comment by kalitine** [comment]
@whalehub so there is no way to test Caddy over QUIC on localhost?

**Comment by whalehub** [comment]
@kalitine Yes, that is correct.

**Comment by whalehub** [comment]
@kalitine I don't know the technical specifics, but everything I find online tells me that QUIC simply doesn't work withs self-signed certificates. Here's another source I found which says the same thing: https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:config:enable_quic:lsws_configuration
