### ISSUE TITLE
add plugins

### ISSUE THREAD

**Issue by Wqrld** [mholt/caddy#2248]
Is it possible to add plugins to caddy after it has been compiled? And if not would i just be able to install caddy again to add plugins?

**Comment by francislavoie** [comment]
This kind of question belongs here: https://caddy.community/

But to answer it, currently no, there's no way to add plugins after compiling, because Go statically compiles its binaries. Since Caddy is basically just a single binary, it usually works to replace the old binary with the new one with the plugins you need.
