### ISSUE TITLE
Print actual binded addr on start

### ISSUE THREAD

**Issue by shazow** [mholt/caddy#231]
Base case, print something along the lines of: `Listening on :2015`.

Right now the *input* is printed, but not the actual binded address. Namely, if you use `port=0` (ie. pick a random available port), then it still prints port 0 which is incorrect.

Some related ideas that may be better off as separate issues, but would love some feedback before advancing:

- If the default should be to bind to all devices for both ipv4 and ipv6, then `:2015` may be a better default than `0.0.0.0:2015`.
- It would be nice if the derived listening *host* was also printed. That is, if we're listening on all available addresses, then we could do a `net.LookupHost(host)` of the current hostname, and that will give us the list of local addresses which the server will be accessible from (useful for finding the appropriate ethernet device address to share with others when on a LAN). This could look something like:

```
$ caddy -port=0
Listening on:
* http://192.168.1.105:12345/
* http://[fe80:42a6:50ff:fe0a:b4c8]:12345/
```

**Comment by mholt** [comment]
This is a good idea. We've changed this behavior a few times (in theory, to make it better) but I think with time and suggestions like this, we'll eventually refine it and narrow it down to just the right behavior. (See #208 and #28, for example.)

Since host resolution can take time, I would like there to be some immediate output when the listener is starting so the user knows that it's working, then the host lookups would be printed whenever they finish...

So would this be useful and accurate in automated environments as well? I'll ping @peterbourgon as well since we had a good discussion in Slack about this and he might have a better idea.

**Comment by shazow** [comment]
Yes, you're right the hostname lookup could add an undetermined amount of latency (can't find a way to set a timeout for DNS lookups).

The other two bits should be fairly safe:

- Getting the actual host/port rather than the input is a matter of doing `.Addr().String()` on the `net.Listener` which we're already setting up manually anyways.
- Changing from `0.0.0.0:2015` default to `:2015` should be fully backwards compatible.

**Comment by peterbourgon** [comment]
- +1 to printing the actual bound port rather than 0, if specified — but who would bind a server to listen on 0? I can't really imagine a legit use case...
- +1 to default binding on `:2015` instead of `0.0.0.0:2015`, this is what the stdlib advocates anyway.
- No opinion on listing bound addresses in the log when you don't specify a specific IP or hostname. I'm not 100% sure, but you shouldn't need to net.Lookup, you can just list net.Interfaces and get addresses from that.

**Comment by shazow** [comment]
> +1 to printing the actual bound port rather than 0, if specified — but who would bind a server to listen on 0? I can't really imagine a legit use case...

The use case is when you don't want to worry about the default port already being taken (e.g. already running a caddy server for a different task) or just want a random port. It's usually what I prefer to do when I spin up a quick http server for somebody to download something off my machine on the local network.

**Comment by mholt** [comment]
I think we're almost ready to make the changes, but just a question @shazow before going forward on this. Would printing this (from your example):

```
Listening on:
* http://192.168.1.105:12345/
* http://[fe80:42a6:50ff:fe0a:b4c8]:12345/
```

be misleading? For example, that machine's hosts file may have an entry that changes the host lookup, but the rest of the Internet accesses it differently (or not at all). In other words, is it worth relying on these lookups? I remember now that was one reason we did away with the hostname lookup and just printed whatever the user specified in their input.

**Comment by shazow** [comment]
Maybe that should be an option?

So my primary usecase for this is showing novices how to quickly share some file on the local network. Typically I'd be like "ok type `ifconfig` then browse through the half-dozen devices and try to find the number that looks most like a LAN ip address" which is... well, lol. Half the time people think the netmask is the ip address, even if they manage to pick the right network device.

I want to be able to give instructions like "type `caddy browse printnet` (or something) and paste one of the URLs it gives."

**Comment by mholt** [comment]
I tagged this as "in progress" because @evermax and I are looking at a good way to handle this according to the feedback so far. :+1:

**Comment by mholt** [comment]
This will probably be best resolved when Caddy has an API and a GUI -- it'll make this type of stuff super easy for web server newbies.
