### ISSUE TITLE
I start caddy server ,I can not find the QUIC in Chrome

### ISSUE THREAD

**Issue by whitekyo** [mholt/caddy#2361]
### 1. What version of Caddy are you using (`caddy -version`)?
0.11

### 2. What are you trying to do?
QUIC

### 3. What is your entire Caddyfile?
```
https://yc.com:443 {
 gzip
 tls /Users/zhengjinguang829/Downloads/caddy_v0.11.1_darwin_amd64_personal/cert.pem /Users/zhengjinguang829/Downloads/caddy_v0.11.1_darwin_amd64_personal/key.pem
 root /Users/zhengjinguang829/Downloads/caddy_v0.11.1_darwin_amd64_personal/ 
}
(paste Caddyfile here)
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
./caddy -conf Caddyfile -port 443 -quic

### 7. What did you see instead (give full error messages and/or log)?
<img width="923" alt="2018-11-22 10 49 22" src="https://user-images.githubusercontent.com/5258260/48878983-e14e6c00-ee44-11e8-94aa-df51a490ccc9.png">
<img width="923" alt="2018-11-22 10 49 22" src="https://user-images.githubusercontent.com/5258260/48879003-f4613c00-ee44-11e8-8f26-37a781094d51.png">
<img width="500" alt="2018-11-22 10 51 23" src="https://user-images.githubusercontent.com/5258260/48879004-f4613c00-ee44-11e8-825d-e583c05412b4.png">
<img width="481" alt="2018-11-22 10 51 31" src="https://user-images.githubusercontent.com/5258260/48879005-f4f9d280-ee44-11e8-9bb6-6630ca109bd7.png">

**Comment by francislavoie** [comment]
Looks like you're using a self-signed cert and not a CA-signed certificate. Also, it's a really bad idea to set your site root as the same directory containing your private key. Your private key needs to stay private, otherwise you're breaking any semblance of security.

I suggest you ask in the Caddy forums here, as this doesn't seem to be an issue with Caddy but rather a question about usage. https://caddy.community/

**Comment by whitekyo** [comment]
@francislavoie  thank you for your answer .
