### ISSUE TITLE
The getConfig function in caddytls/handshake.go appears to handle wildcards incorrectly.

### ISSUE THREAD

**Issue by ryancdotorg** [mholt/caddy#2495]
Note: I've ignored the template because I do not use Caddy, I merely noticed this while looking at the source.

I noticed in `caddytls/handshake.go`, there is [some code](https://github.com/mholt/caddy/blob/448edcca8e29f0f1f6cae40a35c41f522b61020e/caddytls/handshake.go#L66) that tries to match the name supplied via SNI with a wildcard certificate.

This code could result in a `*.example.com` certificate being used for a client requesting `foo.bar.example.com` resulting in a handshake failure for any reasonable client.

This is documented in [RFC 6125](https://tools.ietf.org/html/rfc6125#section-6.4.3).

If the current behavior is intentional, a comment next to that code explaining why would be helpful.

**Comment by mholt** [comment]
>  I've ignored the template because I do not use Caddy

Sorry, but it will be hard for us to produce a fix unless you can demonstrate the problem in a way that is reproducible. If you kindly provide some evidence to support your claims, we will have a better understanding of the bug and can fix it.

**Comment by tobya** [comment]
@ryancdotorg by my reading of this code I dont see how it could match foo.bar.example.com .  Perhaps you could explain why you came to this conclusion.

**Comment by ryancdotorg** [comment]
I seem to have misinterpreted the code. I still think the behavior is incorrect, isn't likely to cause an issue in practice as is.

```go
	// then try replacing labels in the name with
	// wildcards until we get a match
	labels := strings.Split(name, ".")
	for i := range labels {
		labels[i] = "*"
		candidate := strings.Join(labels, ".")
		if config, ok := cg[candidate]; ok {
			return config
		}
	}
```

In this code, `name` is whatever the client sent via SNI. Say it is "foo.bar.example.com", Caddy will look for configs matching "\*.bar.example.com" (valid), "\*.\*.example.com" (client SHOULD NOT match per RFC 6125), "\*.\*.\*.com" and "\*.\*.\*.\*".

I would replace this code with something like

```go
	// try replacing the first label with with a wildcard
	if idx := strings.Index(name, "."); idx >= 0 {
		if config, ok := cg["*" + name[idx:]]; ok {
			return config
		}
	}
```

**Comment by tobya** [comment]
I think you are misunderstanding the code and would be interested if you had found somewhere that this code has acted in the way you suggest.

The code is actually checking the config for `*.example.com'.   It builds strings like `*.example.com` and `*.*.com` and sees if they match host strings in the config file rather than the other way around. 

given the caddyfile
````
*.example.com {
  root c:\websites\root1
}
````
This code will match
> https://foo.example.com

but will not match (as I think you are suggesting it will)

> https://foo.bar.example.com

**Comment by ryancdotorg** [comment]
with
```
*.*.example.com {
  root c:\websites\root1
}
```

it will match `https://foo.bar.example.com/` which will then fail validation in most clients.

You're correct that it will never try to match the `*.example.com` config, I was mistaken when I thought that.

**Comment by mholt** [comment]
This is [how the Go standard library does it](https://golang.org/src/crypto/tls/common.go#L903) (from which we borrowed the logic):

```go
// try replacing labels in the name with wildcards until we get a
// match.
labels := strings.Split(name, ".")
for i := range labels {
	labels[i] = "*"
	candidate := strings.Join(labels, ".")
	if cert, ok := c.NameToCertificate[candidate]; ok {
		return cert, nil
	}
}
```

It's not really a big deal, because like you said clients should reject those certificates anyway. Thus, the only certificates that _should_ have names like this would be internally-issued (or non-publicly-trusted) certificates. So, we can tidy up this portion of our code to only allow a single, left-most-label wildcard I suppose. But it might break some people using it internally, although I agree that's bad practice, and I don't mind turning that off.

However, your understanding of the Caddyfile is not quite correct. The matching logic is more nuanced than you make it seem. This Caddyfile:

```
*.*.example.com
```

does not really obtain a certificate for `*.*.example.com` -- nor will it serve up such a certificate unless told to do so manually.

Before matching certificates are even searched for, Caddy first has to use the SNI value to find a matching TLS configuration to use. In that sense, there is no harm in matching `*.*.example.com` and in fact we must do this or there are likely to be bugs. Once a TLS config is matched, _then_ a certificate is matched, which can use the stricter logic.

Pull requests welcomed, as I may not be able to get to this quite immediately.

**Comment by ryancdotorg** [comment]
I wasn't aware this was inherited from stdlib, and I've spoken with the maintainer about it - he said you'd mentioned it to him as well.

Thank you for tracking that down.
