### ISSUE TITLE
Need more "http.rewrite if and" examples

### ISSUE THREAD

**Issue by GreatFireWall** [mholt/caddy#2631]
Why this not work?

```
xxx.com, www.xxx.com {
    gzip
    header / Strict-Transport-Security "max-age=31536000;"
    proxy /api a:5000 {
        transparent
    }
    proxy /mysql b:8080 {
        transparent
    }
    rewrite {
        if {path} not /api and {path} not /mysql
        to {path} /
    }
}
```
`Error during parsing: Wrong argument count or unexpected line ending after '/mysql'`

**Comment by mholt** [comment]
Thanks for your question, and I'm thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for specific, development-focused discussions, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
