### ISSUE TITLE
How to reverse proxy subdomain

### ISSUE THREAD

**Issue by tranducit95** [mholt/caddy#2645]
Caddyfile
```
api.domain.local:443 {
    root /var/www/project-api/public
    fastcgi / php-fpm:9000 php {
        index index.php
    }

    rewrite {
        to {path} {path}/ /index.php?{query}
    }

    gzip
    browse

    log /var/log/caddy/access.log
    errors /var/log/caddy/error.log

    tls self_signed

    #tls {
    #  dns cloudflare
    #}
}

admin.domain.local:443 {
    root /var/www/project-web/dist

    ext / .html
    rewrite / {
        to {path} /
    }

    gzip
    browse

    log /var/log/caddy/access.log
    errors /var/log/caddy/error.log

    proxy /api api.domain.local:443 {
        transparent
    }

    tls self_signed
}

```
I want when the request to `admin.domain.local/api/*` => `api.domain.local/api/*` how can I do that?

**Comment by abiosoft** [comment]
Why not use `redir`?

**Comment by mholt** [comment]
Thanks for your question, and I'm thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for specific, development-focused discussions, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
