### ISSUE TITLE
[idea] 'secure' directive

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#312]
Just an idea for discussion for now:

I'm not sure on exactly what this should look, but I'd like to see a `secure` directive that turns on reasonable-default headers for CSP, iframe blocking, block POSTs from hitting the backend unless CORS is actually enabled, https keypinning, etc, etc, etc.

Obviously there are a million things that could be heavily configured, but for people that actually know what they're doing they could simply turn off the feature that offends them and handle it in their own application layer.

```
# turn it all on
secure
```

```
secure {
  iframe-block off
  csp-img-src off
}
```

Note that turning off CSP for images would not actually remove it from the header, but instead modify the header to include `https://`, `blob:`, and `data:`.

Just make it easier for people who don't understand web security to get the minimal protection.

**Comment by captncraig** [comment]
Something like https://github.com/martini-contrib/secure may be a good starting point to look at.

**Comment by netaisllc** [comment]
FYI, **Negroni** is the successor to Martini, same "security start kit" idea there, using this Go http middleware:  
 https://github.com/unrolled/secure

**Comment by captncraig** [comment]
Looking at that lib, it is a good candidate. It has no dependencies other than std lib, and exposes a really simple handler interface (even one with a next handler!).

All that is really needed to turn it into a caddy plugin is:

1. A caddyfile parser / config builder to make the options.
2. A small wrapper shim to convert the caddy middleware function format into that package's handler format. 

Not a huge job at all.

**Comment by mholt** [comment]
Thanks for the link @netaisllc 

I think that's cool, but with Caddy, quite a few of those options are unnecessary, since Caddy takes care of the SSL/HTTPS stuff, or the option just adds a header which is already a breeze with the `header` directive (and more clear). I'd prefer we not duplicate functionality that is already in Caddy and super easy to do.

**Comment by netaisllc** [comment]
@mholt Totally agree.  (I provided the link because it refers to 'newer' stuff, given that Martini has been softly superseded by its own author by Negroni. Wanted any reviewers to be up-to-date.)

**Comment by tehscorpion** [comment]
@netaisllc the middleware looks like it adds no value to caddy right now. because as i see it right now it just adds headers which is already possible. How about https://github.com/SpiderLabs/ModSecurity/tree/libmodsecurity using with commercial/free rules.
Someone actually started the go bindings already https://github.com/senghoo/modsecurity-go.

**Comment by mholt** [comment]
@coolaj86 - and the other participants in this issue - thanks for your comments! There is some good stuff here, so I have linked to this issue from [a thread in our community forum](https://forum.caddyserver.com/t/requested-plugins-ideas-for-developers/127?u=matt) where we are aggregating ideas/requests for Caddy plugins.

If you want to continue discussing the plugin before development begins on it, feel free to start a new topic on the forum. :+1: Hope to see you participate with us there!
