### ISSUE TITLE
Hide markdown file extensions in the URL

### ISSUE THREAD

**Issue by Siecje** [mholt/caddy#314]
I'm starting with the markdown structure in the examples repo

https://github.com/caddyserver/examples

I don't want ```.md``` to be in the URLs.

I added ```ext .md``` to the Caddy file
```
localhost:8080
ext .md
```

The links from the index page still contain .md and both are available.

**Comment by mholt** [comment]
The ext middleware doesn't change anything in files; it just rewrites requests so that if it gets a request for /blog/post, for example, it looks for a file called /blog/post.md.

The Caddy website uses this. It links to pages, like /download, even though the actual file is /download.html. You can use either, but the clean URL is certainly nicer. :)

**Comment by Siecje** [comment]
The index page has links with .md

**Comment by mholt** [comment]
You can remove them. Are you talking about the index template? It is too naive to know that you want to strip extensions, but you can very easily; something like this: `{{$.StripExt .URL}}`

**Comment by Siecje** [comment]
Thanks that works!

How would you remove the ```http://localhost:8080/hello-world.md``` page?

So that there is only one canonical URL.

**Comment by mholt** [comment]
The way I do it is by simply not linking to the file with its extension.
