### ISSUE TITLE
Re-create log files if deleted

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#329]
If a log file is deleted from disk while Caddy is running, Caddy should re-create it. This can be detected if there is an error when printing to the log.

This should apply to the process log, access logs, and error logs.

Logs that write to stdout/stderr should just silently fail if those disappear, I guess. Not sure what would be better.

**Comment by captncraig** [comment]
I'm not sure what situations could lead to an error on write, but we should probably make sure to open it with preference to append vs overwriting it if it exists when we try to re-open it.

If something somehow swapped it out underneath us I wouldn't want to blow away the existing file and recreate it. In reality I think this situation should be pretty rare, but best to consider it.

**Comment by My1** [comment]
it is pretty funny seeing you creating a suggestion to your own repo @mholt but I agree...

**Comment by pwFoo** [comment]
Yes, log files should be (re-)created if not exists.

**Comment by mholt** [comment]
Okay, well, log files are re-created if they don't exist, but if they get deleted while Caddy is running that might be a problem? But implementing an error check for every log line is not on my timetable right now, and I haven't heard of this being an actual issue so I'm going to shelve it as "don't delete the log files while Caddy is running" kind of thing.

**Comment by wjkohnen** [comment]
Just seeing this because you closed this. On UNIXlike filesystem you can remove or change the _directory entry_ of a file (a.k.a. delete or move) while it is opened. Files and directory entries on UNIX are related, but different things. You can even create files that don't have any entry, see O_TMPFILE. 

Log rotation usually takes advantage of this: 

1. move the log file
2. let the process close the log file. There is no race condition, because the process kept writing to the file with the new name until now. 
3. let the process re-open the log file with old name. 
4. do something with renamed log file (compress)

The only synchronisation needed is while re-opening, which is trivial if you already have a central writer. Traditionally processes just implement re-opening logfiles via SIGHUP signal and let other processes deal with logfile management (see [logrotate](https://github.com/logrotate/logrotate)). 

I don't know how this works on Windows, though.

**Comment by motiejus** [comment]
I second @jwkohnen: it would be great if Caddy re-opened the logs on SIGHUP; that way I could hook into logrotate without requiring a caddy restart.

**Comment by francislavoie** [comment]
@motiejus you're commenting on an issue from nearly 6 years ago. This is no longer relevant, as it was for Caddy v0.

Please open a new issue if you have a problem.
