### ISSUE TITLE
proxy pass assistance 

### ISSUE THREAD

**Issue by jungle-boogie** [mholt/caddy#365]
Hello,

I have a simple nginx config as follows:

     server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            proxy_pass http://10.132.5.134:8080/;
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

Can Caddy do something similar with the proxy setup as is?

**Comment by mholt** [comment]
Your equivalent Caddyfile would be:

```
localhost:80
proxy / http://10.132.5.134:8000 {
    proxy_header X-Real-IP {remote}
    proxy_header Host {host}
}
```

This can be obtained from the [proxy docs](https://caddyserver.com/docs/proxy).

It's been a while since I've done much with the proxy middleware -- I'm not sure, off-hand, if the Host header needs to be set explicitly, but I do believe X-Forwarded-For is already set for you. (Feel free to double-check if that works for you.)

**Comment by jungle-boogie** [comment]
Thanks so much!

Is the code for caddyserver.com on github? If so, can I make a PR with this example?

**Comment by mholt** [comment]
It's here: https://github.com/caddyserver/caddyserver.com

You're certainly welcome to submit a PR, but keep in mind there's a couple similar examples already; is this one different enough that it merits its own example? (Just don't want to overwhelm the reader.)
