### ISSUE TITLE
LE: Please make RSA key size configurable

### ISSUE THREAD

**Issue by kseistrup** [mholt/caddy#382]
Thanks for supporting Let's Encrypt.  However, it would be nice to be able to configure the RSA key sife.  Currently the key size is hard coded to 2048 bits:

```go
rsaKeySizeToUse = RSA_2048
```

**Comment by CrawX** [comment]
I implemented a way to configure the keysize on a per-host basis but after a brief discussion with @mholt , he proposed changing the keysize for all hosts via a command line parameter for example.

Whats the case here? Would it be necessary to adjust it on a per-host basis, would that make sense? How should the keysize be configured?

**Comment by kseistrup** [comment]
I would be happy if changing the keysize for all hosts in one fell swoop were implemented, and thumbs up if a per-host basis were implemented.

For a per-host basis implementation I imagine something like this:
```sh
www.example.com {
  root /path/to/pages
  rsakeysize 4096
}
```

**Comment by mholt** [comment]
Per-host key size is going to be much more complex than just a command line flag for all hosts. What is the specific, common use case for a per-host custom key size?

**Comment by kseistrup** [comment]
I don't personally have a use case for per-host configuration of keysize, I'd be perfectly satisfied with a command line option to set the keysize for all hosts.  Well, almost: having the same keysize for all hosts is perfectly fine with me, but I would like to be able to set this size in the config file (along with `-agree` and `-email`).

**Comment by mholt** [comment]
Why do you need it in the config file, though? I'm just having trouble justifying the added complexity (because I looked into doing it once) without a real solid, repeatable use case.

**Comment by mholt** [comment]
Speaking of upcoming ECC support: https://github.com/letsencrypt/boulder/commit/1cacde22ee3aab5254954748ac97251f3854df03

**Comment by jungle-boogie** [comment]
why would we not want it to default to the largest key size?

**Comment by mholt** [comment]
For most purposes, that's overkill. Computation is expensive on low-power devices. Raspberry Pi and some mobile phones in particular are very slow, especially with RSA. ECC is faster, but the point of ECC is to be faster. Higher key sizes increase both transmission time and computation latency.

**Comment by jungle-boogie** [comment]
good points.
I'd rather caddy be able to support ecda and it looks like that's happening with lets encrypt!

**Comment by kseistrup** [comment]
@mholt I don't see why being able to put something in a config file should make things complex, it could be as simple as
```sh
$ caddy -config CONFIGFILE [CADDYFILE [CADDYFILE …]]
```
where CONFIGFILE has a simple `key = val` syntax. So all you need is a parser routine to parse a config file and another parser routine to parse the caddy files.

When I say I want `-agree` and `-email` in a config file rather than on the command line, it's because of two things: (1) command lines tend to get very long and unwieldy over the lifetime of a program as new features are added, and if you — e.g., in test situations — have to restart caddy often, it is tedious to have to type very long command lines, and (2) there are certain kinds of information that doesn't belong on a command line, such as email addresses and passwords and other sensitive information, because such information can be gleaned (think `ps`) by anyone who has a shell account on the machine that runs caddy, whereas I can protect config files by restricting their readability.

**Comment by CrawX** [comment]
The way I understand it, caddy's goal is to replace the "default" http server on 80/443 for most systems and not sit behind another reverse-proxy, especially because of the letsencrypt-functionality here.
When thinking about it like this, my personal opinion is that there should be as many configurables as reasonably possible, this includes settings for the generated letsencrypt keys. It makes even more sense when ECC arrives; IMHO the user should be able to choose between RSA and ECC on a per-host basis, e.g. for different compatibility constraints on different vhosts.

The only other way for a user to change these options is to do it externally: Create letsencrypt certificates via some other method and use them with caddy. But as caddy supports that natively, I don't think that makes sense.

When ECC works, there should be at least two options: one for the algorithm and one for the keysize. I imagine them being either in the tls {...} block or being in a subblock in tls. I don't think setting it globally is the way to go here, maybe as a quick fix before ECC is done.

**Comment by elcore** [comment]
I believe we can close this: #706

"That change looks really nice though. I'm restructuring all that stuff, but I can accept a PR of it and just resolve the conflict later on my end" - @mholt (Gitter)
