### ISSUE TITLE
The order of directives

### ISSUE THREAD

**Issue by lilee** [mholt/caddy#409]
Now the caddy directives's order is hard code. 

I think the directives should be ordered as the directives write in the Caddyfile

**Comment by captncraig** [comment]
Do you have an example of a case where you would like it changed? Can you share a caddyfile snippet? 

Initially this sounds like an ok idea, but it is complicated by the fact that there are built-in directives that don't go in the caddyfile. 

My worry is that often I put the "most important (to me)" directives first in my Caddyfile, not necessarily considering the ordering consequences. Having them hard-coded allows the caddy and plugin authors define a relatively "safe" ordering.

**Comment by mholt** [comment]
Thanks for the suggestion @lilee.

But I disagree.

Consider this Caddyfile:

```
example.com

markdown
log access.log
header -Server
```

Here the site owner intends to log all requests and, as a security precaution, remove the "Server" header.  But markdown handles requests for Markdown files, and it doesn't pass requests down the middleware chain because it already wrote to the response (with the rendered Markdown body). If other middleware like the core file server at the end of the chain tried to write the response, it'd be a major malfunction.

As such, requests for markdown files wouldn't be logged and the header would never be stripped. Similar bad things happen with error and gzip middlewares. Each directive is carefully placed in the chain where it belongs.

**Comment by lilee** [comment]
As I mentioned in the issue #408, I want ```my_middleware``` to be handled before ```proxy```. Because ```my_middleware``` will provide some context for ```proxy```

**Comment by mholt** [comment]
That's fine; when you create a new middleware you can put its directive higher in the list than `proxy` and it will be handled before it.

**Comment by lilee** [comment]
@mholt but I think hardcode is not flexible

**Comment by mholt** [comment]
If there's anything else to discuss on this, feel free to re-open and clarify, but I think we answered your question.
