### ISSUE TITLE
Interactive prompting for email address?!

### ISSUE THREAD

**Issue by peterbourgon** [mholt/caddy#433]
I start Caddy via the runit supervisor, and use CloudFlare to handle my https/SSL stuff. To upgrade, I download a new binary and restart the process. The most recent version of Caddy now automatically assumes I want to use Let's Encrypt (?!) and prompts me interactively for my email address when I start the binary (?!?!?) which obviously confuses my supervisor and causes all my sites to be down.

~~Most importantly, how do I turn this "feature" off?~~ @xenolf on Slack told me how to put `tls off` in each of my server blocks, which did the trick. Thanks!

Further, server software should _never_ prompt interactively for input when run with default/normal parameters! And support for third party integration should be _opt-in_, not opt-out—even if it is a "flagship feature"!

I'm kind of flabbergasted that Caddy behaves this way. How do you believe people are running this software? As I'm clearly doing things that the core devs believe is abnormal...

**Comment by mholt** [comment]
Hey Peter, thanks for your comments.

With version 0.8, Caddy enables HTTPS by default if you don't do it manually or explicitly turn it off. This means it uses Let's Encrypt to generate certificates for you. Let's Encrypt has a service agreement which clients must prompt the user about at least once, and Caddy acts in compliance with this requirement. Once an agreement has been established, it remembers that for future runs. This is documented in [automatic HTTPS](https://caddyserver.com/docs/automatic-https) and mentioned on the [Caddyfile docs](https://caddyserver.com/docs/caddyfile) for those setting up site configurations for their first time.

Disabling TLS is documented in [tls](https://caddyserver.com/docs/tls).

> Further, server software should never prompt interactively for input when run with default/normal parameters!

I disagree. You probably don't use `yum` or `apt-get` then, since those require you to pass `-y` to disable the interactive prompt. Ways to bypass Caddy's one-time prompt are clearly documented on the [CLI page](https://caddyserver.com/docs/cli).

> And support for third party integration should be opt-in, not opt-out—even if it is a "flagship feature"!

Sorry, but we're not going to take that risk with this project. With Caddy, plaintext HTTP is opt-in. Privacy is default.

**Comment by peterbourgon** [comment]
>  You probably don't use yum or apt-get then, since those require you to pass -y to disable the interactive prompt. 

yum and apt are not server software.

>  With Caddy, plaintext HTTP is opt-in. Privacy is default.

That's fine, if it's frictionless. As it stands now, by default, running Caddy requires an account with a third-party service provider. That's _crazy_. If that's not self evident, then agree to disagree indeed :\

**Comment by mholt** [comment]
> yum and apt are not server software.

Really? I use them on servers all the time, and in automated provisioning scripts too.

> That's fine, if it's frictionless. As it stands now, by default, running Caddy requires an account with a third-party service provider. That's crazy. If that's not self evident, then agree to disagree indeed :\

Trust me, it's as frictionless as it gets. The terms are still annoying, but we have to do it. Anyway, you can disable it or bypass them with ease. Yours are the first comments I've heard about this integration in a negative light, so it's valuable feedback to see the other side of the issue; thanks.

**Comment by peterbourgon** [comment]
Independent of the technical details, thank you for reasonably responding to my admittedly ornery comments. I was frustrated after taking several sites down and used unnecessarily emotional language in this issue. Mea culpa.

**Comment by mholt** [comment]
Sorry about the downtime; this was definitely a big, breaking release. I try not to do those very often :smile: Once we hit 1.0, they shouldn't ever happen on the 1.0 branch, so we can look forward to that!

**Comment by AndreKR** [comment]
I was bitten by this, too, especially since crappy Upstart doesn't provide any log output by default.

I think it should be mentioned on both https://caddyserver.com/docs/getting-started and https://caddyserver.com/docs/automatic-https somewhere at the top that you should put `tls some@email.address` in your Caddyfile as soon as you add a hostname. The same should also be mentioned on https://caddyserver.com/docs/caddyfile in the "Addresses" section.

**Comment by mholt** [comment]
@AndreKR If you don't want to be prompted for an email address, you can certainly do that, or you can also use the `-email` command line option. But in all frankness, the LE email has nothing to do with the Caddyfile _or_ getting started with using Caddy your first time.

**Comment by AndreKR** [comment]
It seems kind of like a first world problem, but if the goal is to be very very user friendly, then the sequence of events is a bit unfortunate:
* I walk through the Getting started guide, running Caddy manually.
* Since at that point no hostname is configured, it will not try to set up LE and show no prompt.
* I might now play around with a Caddyfile, but even then it's very unlikely that I would put a hostname other than `localhost` in it, so still no prompt.
* Now I'm satisfied with Caddy, so I want to set it up on a server. So I go looking for a start script, find one in the download and set it up - from this point on prompts don't work anymore. It won't occur to me to run it manually with a Caddyfile because only after I have the start script I know where to put the Caddyfile.
* Now I put my hostname in the Caddyfile and nothing works anymore.

At no point in this process I got the chance to see the prompt with my own eyes, so that's why I think it really needs to be in the documentation in a prominent place.

**Comment by peterbourgon** [comment]
While I'm a lot less emotional about the situation now, I would reiterate that it's still flabbergasting and incoherent to me that server software could require an interactive prompt to start up.

**Comment by mholt** [comment]
@AndreKR 

> At no point in this process I got the chance to see the prompt with my own eyes, so that's why I think it really needs to be in the documentation in a prominent place.

That's a good point, we've been kind of learning what users' workflows are like as they use Caddy, and you should be pleased to know that with the new site, the new beginner's tutorial already covers this so that users see a prompt.

@peterbourgon I asked some LE folks about the email address requirement, and it is in fact optional now; only used to send reminder emails or contact a site owner in case of problems. This is different than it was 2 years ago when you first raised the issue.

So I think we can let the email address be "optional" now, rather than "recommended but optional".
