### ISSUE TITLE
How to disable the automatic https.

### ISSUE THREAD

**Issue by bohanyang** [mholt/caddy#454]
DISABLE!!

**Comment by mholt** [comment]
Why? Sounds like a terrible idea.

But you can do any of the things mentioned at the top of the page about [automatic HTTPS](https://caddyserver.com/docs/automatic-https).

**Comment by My1** [comment]
for web-facing servers true, but for local-only domains (happens more than often enough e.g. in company networks) you cant really get an auto-TLS working.

**Comment by talentlessguy** [comment]
Any updates on this? I removed caddy and systemctl service but it keeps redirecting to https :/

**Comment by My1** [comment]
browser caches can be annoying. open dev-panel via F12, switch to network tab, check disable cache, and then enter your address normally while making sure not to choose an autocorrect from below as that usually is HTTPS.

bonus debuggability by setting preserve logs on

**Comment by francislavoie** [comment]
A 5 year old issue is not the best place to get help.

Next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by My1** [comment]
that IS certainly true.

**Comment by talentlessguy** [comment]
@My1 thanks! it helped

I spent half an hour thinking that my server is doomed to be broken but after clearing cache everything went fine

**Comment by My1** [comment]
you don't wanna know how often I had that, especially on redirects where you cannot just ctrl+F5 cache clearing is a royal pain

**Comment by tomachinz** [comment]
I think I need it as some of the servers I'd like to front-end also use https. eg webmin, portainer, syncthing, nextcloud etc.

**Comment by francislavoie** [comment]
@tomachinz This is a 6 year old issue. Please don't comment on such old, closed issues. It's possible to disable auto-https, you can set `auto_https off` in global options: https://caddyserver.com/docs/caddyfile/options, or just by prefixing your site address with `http://`.

But in your case, you probably don't want to disable Auto HTTPS, because typically the purpose of putting Caddy in front of those services is to make use of Caddy's best-in-class certificate management facilities. If you must, you can proxy to those services over HTTPS; see the docs for the `reverse_proxy` directive: https://caddyserver.com/docs/caddyfile/directives/reverse_proxy

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). Don't forget to fill out the thread template so we can help you!
