### ISSUE TITLE
Can the downloads page have a latest url?

### ISSUE THREAD

**Issue by j-mcnally** [mholt/caddy#46]
Would be nice if there was a url for latest build.

Right now I see like

/0.5.0/download.tar.gz

would be nice to have

/latest/download.tar.gz

This would ensure the heroku buildpack and docker container can always get the latest code without having to constantly update the buildpacks etc....

Thoughts?

**Comment by mholt** [comment]
It's a good idea. How concerned are you about breaking changes? (i.e. major version bumps)

**Comment by j-mcnally** [comment]
I dont know.... The main concern would be caddy being updated via the buildpack on a deploy right?

I think this is a valid concern but not sure how to address via heroku since build packs can't target branches / refs / or tags

**Comment by j-mcnally** [comment]
perhaps supporting a  `.caddyversion` file in the repo to pin to a version would fix this.

**Comment by mholt** [comment]
Hm, I don't see that GitHub supports anything like this so I might have to roll my own anyway.

How about a major version in the URL? Something like: /download/1/latest or /download/2/latest

**Comment by j-mcnally** [comment]
Works for me, i'm still going to support some sort of setting for the user to specify a pinned version i think, but would be super helpful to be able to get the latest somehow. Even if its just a text file with a url in it.

**Comment by mholt** [comment]
I'm working on this - also, does it have to be .tar.gz? I'd rather just do .zip :smile:

**Comment by j-mcnally** [comment]
Zip is fine :)

**Comment by mholt** [comment]
Alrighty - these should always give you the latest: https://caddyserver.com/...

- /download/win64
- /download/win32
- /download/mac64
- /download/mac32
- /download/linux64
- /download/linux32
- /download/linuxarm
- /download/freebsd64
- /download/freebsd32
- /download/freebsdarm
- /download/openbsd64 
- /download/openbsd32

If you'd prefer something else, let me know. And if these ever will change (maybe due to a new deployment strategy or something) I'll give the notice an in issue or something.

Thanks for the suggestion!
