### ISSUE TITLE
multiple Ports with HTTPS-Capability

### ISSUE THREAD

**Issue by computerlyrik** [mholt/caddy#474]
Given Caddyfile
```
myhost.com  {
...
}
https://myhost.com:5000  {
...
}
```

Gives only a HTTPS-Connection on 443 with a redirect from 80.
HTTPS on Port 5000 fails silently (!) and does only serve HTTP.

While debugging, I removed the first entry. **Then** the HTTPS-Encryption on Port 5000 works - with a redirect from 80.

It seems, caddy has problems due to the port 80 reservation or sth. How do i prevent this?

**Comment by mholt** [comment]
Yeah, patch is coming which fixes this. The parser originally interpreted scheme and port as the same thing, but in 0.8, that logic got more complicated but the parser wasn't upgraded to support it. It's already fixed locally so that the parser will interpret scheme and port separately; should be pushed before too long.

**Comment by computerlyrik** [comment]
Hehe..just wrapped around the Caddyfile with variables like `host_port`. Felt weird ... so exited where we are getting next :)

**Comment by computerlyrik** [comment]
Did you think about using some declarative standard like `json` or `yml` for writing the Caddyfile?

**Comment by mholt** [comment]
Yes, see https://caddyserver.com/blog/deliberate-caddyfile-syntax
