### ISSUE TITLE
Issues with TLS certificates using Opera Mini

### ISSUE THREAD

**Issue by ragrum** [mholt/caddy#477]
I was trying to access the Caddy blog under HTTPS (https://caddyserver.com/blog/) using Opera Mini, but I got the following error message:

````
You tried to access the address
https://caddyserver.com/blog/caddy-0_8-released , which is currently unavailable. Please make sure that the web address (URL) is correctly spelled and punctuated, then try reloading the page.
Secure connection: fatal error (1066)
https://caddyserver.com/blog/caddy-0_8-released
Unable to verify the website's identity (OCSP error).
The response from the online certificate validation (OCSP) server was too old.
```

I guess it's using the Let's Encrypt functionality to serve the blog, that's why I think it could be an issue.

**Comment by mholt** [comment]
Ah, I'm actually aware of this, but it's the first report I've heard of a browser breaking because of it. A patch will be on its way soon. See https://github.com/mholt/caddy/commit/30c949085cad82d07562ca3403a22513b8fcd440

**Comment by mholt** [comment]
@ragrum So actually, this might be a problem with Opera Mini implementing OCSP incorrectly. See http://www.opera.com/blogs/security/2014/10/security-changes-opera-25-poodle-attacks/#comment-1644749998 (or any other similar Google search results). Basically, upon a browser getting an expired OCSP value, they should request a new one themselves. But maybe Opera Mini is not doing that?

Anyway, I'm still improving the OCSP stapling in Caddy for 0.8.1 to fetch a new OCSP response at NextUpdate rather than only when the status changes. This will still leave a brief window where OCSP status is old, but in those few occasions the browser should request a new one on their own.

**Comment by ragrum** [comment]
@mholt I see, thanks for sharing that link, and looking into the issue, I'll keep and eye on the Caddy blog after Caddy `0.8.1` is released, and see if the problem continue.

For what it's worth:

**Browser:** Opera Mini 13.0.2036.98649
**OS:** Android 5.1
**Device:** Moto G (1st gen)

**Comment by mholt** [comment]
This is fixed locally; changes will be available on master as soon as I push.
