### ISSUE TITLE
Caddy Distribution extracts files to current directory

### ISSUE THREAD

**Issue by madebyjeffrey** [mholt/caddy#511]
When I downloaded the Caddy distribution, it extracts:

    caddy  CHANGES.txt  LICENSES.txt  README.txt

Everything should be extracted to a caddy directory, to avoid pollution of the current directory. The vast majority of tar.gz files put things in their own directory, such that it is expected that it works like this.

**Comment by mholt** [comment]
Have you tried the `-C` flag?

```
tar -xzf caddy.tar.gz -C my_folder
```

**Comment by madebyjeffrey** [comment]
I am aware of that flag, the issue is that extracting files from a tarball to the current directory is out of step from the general practice and expectations of users.

**Comment by mholt** [comment]
If I put it in a directory and users want to extract to somewhere else, they need to use `strip_components=1`, which is, in my opinion, an even worse user experience.

**Comment by mholt** [comment]
You can also extract just the binary with `--file=caddy` I think.

**Comment by madebyjeffrey** [comment]
May I suggest putting some visible instruction as a cue so one knows it is not going into its own directory? 

I have extracted tar files in a download directory before that litters it with various files, and finding out which ones to clean it up is always a pain.

**Comment by mholt** [comment]
Sure, although I will probably not change the Caddy docs since using tar is out of the scope of the Caddy project. Maybe in the wiki, but we don't have a page for downloading caddy (the wiki is meant more for developers).

In your case, I would recommend to always specify a directory to extract to or extract only the desired file(s) to keep your download folder clean. :smile:
