### ISSUE TITLE
Feedback/Discussion: Stats

### ISSUE THREAD

**Issue by captncraig** [mholt/caddy#577]
I've started an implementation of stats, but wanted to gather feedback before I get too much deeper.

## why not [expvar](https://github.com/mholt/caddy/pull/285)?

expvar is nice for ad-hoc data, but I find it is not the best for structured metrics. If you want to export to a time series database you really need a format more tailored for the use case than arbitrary json.

## go-metrics

[go-metrics](https://github.com/rcrowley/go-metrics) is a widely used go package for tracking metrics. If we use this package to store metrics, any caaddy package (core or plugin) can add metrics to the default registry and they will be accessible for output.
The only package anybody needs to reference directly is go-metrics.

It can support major metric types we would need:

- Counters for ever-increasing values (number of requests)
- Samples for time data (request time)
- Gauges for momentary data (memory / goroutines)

### both!

On a configurable timer, the stats module will snapshot all registered metrics into a data structure:

```
type Measurement struct{
   Metric string // metric name (caddy.request_count)
   Tags map[string]string // host=myserver, server=foo.com, path=getUser
   Values map[string] int64 // Can have multiple values per measurement (Sum,99th,95th,Count), or just a single "Value". Handled differently by each tsdb.
   Timestamp time.Time    
}
```

a web endpoint can be set up to display json of the latest snapshot, or we can send it to time series databases by implementing pushers for influx, graphite, opentsdb, prometheus, ...

`type Pusher interface{ Send(batch []Measurement) error }`

## Tags

I believe in multi-dimensional metrics. Almost every tsdb supports tagged metrics, or can be adapted from the tag model. go-metrics doesn't directly support tags in the registry, but since it is just keyed on
a name we can encode tags in the metric name: `caddy.request_count{server=foo.com,path=getUser}`, or `caddy.status_codes{server=foo.com,code=200}`. 

## Stat Module

The stat module will have two main purposes:

1. Sit toward the front of the middleware chain and collect request counts, timings, statuses, error counts, etc.
2. Gather metrics and send to tsdbs, as well as host raw data for pull consumers.

Just adding `stats` as a directive should be enough to get a server collecting stats. One or more server blocks can add additional fields:

```
stats /stats { #can pull data from /stats
    interval 15s #global, should only be defined once
    send influx https://myInfluxServer:8086  
}    
```

## Metrics to collect

Initially, the stat module will collect:

- `caddy.requests{server=foo.com,path=/}` - counter of total requests by server and path.
- `caddy.status_codes{code=200,server=foo.com,path=/}` - conter of total requests by response code, server and path
- `caddy.errors{server=foo.com,path=/}` - total errors by server and path
- `caddy.response_time{server=foo.com,path=/}` - timings per server/path. Will include count,avg,99th,95th,stdDev,etc.
- server uptime, basic mem and gc stats, goroutine count, etc.

Other possibilities include:

- proxy stats and timings per upstream
- byte throughputs from server core
- https certificate lifetime information
- ip block counts

### A note on paths:

In the above examples I grouped by "path". What people consider a group of paths they want to measyure could vary wildly. Default is always `/` if e can't match anything.
Other rules may be given to match a common path or method or maybe more.

`path /foo foo #alias /foo* as foo`

`path /user GET getUser`
`path /user PUT,POST,PATCH saveUser`

Can we reuse any match logic from other directives?

If other directives below me on the stack want to add metrics a way to pass context up and down the stack might be really useful so I can communicate the path to them.

## Visualization

My initial intent is to rely on external facilities for graphing and such. I can share some common grafana dashboards for useful things from various data sources.

Down the road we may want a built-in data page with graphs and such, either from the external db or from some kind of embedded cache of the data. Not sure what that would be.

### Feedback?

I feel like this is a good direction to get what I want out of caddy, but I would love feedback for how others would want to use it. Am I missing something big? Is there a different direction this could/should go?

**Comment by faddat** [comment]
+1 to the whole thing, because it is another step torwards maturity

And then -- +1 specifically to proxy uses.  I am using caddy exclusively as a proxy, and I'd love me some stats!

**Comment by captncraig** [comment]
Yeah, part of the design is that proxy can add stats per backend and stuff and it will just show up; and won't cause problems if  stats is no loaded.

**Comment by captncraig** [comment]
You can see my partial implementation at https://github.com/captncraig/caddy-stats btw. Working push to influx already.

**Comment by SuperQ** [comment]
The one down side to go-metrics is the limitations of `strict.separated.by.dots` data model.  The Prometheus metrics library allows arbitrary key/value labeling with no restrictions for the label value (UTF-8).

**Comment by juliusv** [comment]
A couple of thoughts (bias warning, Prometheus author):

* `caddy.status_codes{code=200,server=foo.com,path=/}` seems to be a superset of `caddy.requests{server=foo.com,path=/}` and `caddy.errors{server=foo.com,path=/}`. So I'd suggest omitting the latter two, as you can derive them from the first (at least if you have a query engine that allows you to select and aggregate over dimensions - that's maybe the question here).

* Quantiles/percentiles have limited usefulness since they are [not aggregatable](http://latencytipoftheday.blogspot.de/2014/06/latencytipoftheday-you-cant-average.html) (neither over instrumented dimensions, nor over multiple instances of a server). What you usually want is histograms with cumulative buckets [like in Prometheus](http://prometheus.io/docs/concepts/metric_types/#histogram). Those allow you to compute percentiles during query time and aggregate and slice and dice at will (at least in Prometheus). But then you probably need to let the user define bucket sizes that work well for the latency distribution of their workload. See also http://prometheus.io/docs/practices/histograms/. However, client-side percentiles are really only useful if you have very few servers to look after, as you cannot display hundreds of e.g. 90th percentile lines in a single graph in a useful way, and you cannot aggregate over them either.

* Normally I would also suggest using the Prometheus client library for all metric tracking and exposure (like in Kubernetes, etcd, cAdvisor, ...) because it supports a dimensional data model natively and has lots of bells and whistles. But if you want to reuse the tracked data for third-party systems like InfluxDB/OpenTSDB, that's doable, but a bit hacky currently to get it out of the Prometheus client library again (hopefully going to improve soon - /cc beorn7).

**Comment by juliusv** [comment]
To be more specific about how to currently get metrics state out of the Prometheus Go client library again (for use in third-party systems): you call a `prometheus.Metric`'s `Write(*dto.Metric) error` method: https://godoc.org/github.com/prometheus/client_golang/prometheus#Metric

The only thing that might put people off about that is that the DTO that gets filled in by that method is a protobuf object (https://github.com/prometheus/client_model/blob/master/metrics.proto#L66-L74), instead of a more Go-idiomatic object with domain-specific accessor methods for the various metric types. So it requires using the usual protobuf accessor methods instead.

**Comment by beorn7** [comment]
I (maintainer of https://github.com/prometheus/client_golang) am currently working on a lot of piled up things that should make it into the client library. I have to admit that exposing to other monitoring systems is not a priority right now. However, what _is_ a priority is a clearer separation between internal collection of metrics on the one hand, and exposition of the metrics on the other hand. So it should be relatively easy to write alternative exposition backends. So anybody could do it because of the clear separation. You will to read from Prometheus protobuf, though… ;)

**Comment by captncraig** [comment]
Thanks for the feedback @juliusv.

- Yes the request_count metrics are redundant with the status code ones. I have considered removing the counts. the errors though, are not so clear cut. The downstream middleware will return a status code and an error. There are guidelines for how to use that, but I am not clear on the possible scenarios. What if I get a 200 and an error? What if I get a 500 and no Error? The proxy doesn't appear to transfer the status code back up, and always has a 0 status code. The error counter errors independently of status code, and could diverge from just counting 5xx.

- I agree , the percentiles are a bit tricky to work with. It looks ok for high volume servers, but with low volume servers the exponential decay samples don't change very much. I considered reseting them every time I sample the data, but that would lead to a lot of zeros in those low volume servers as well. I would love some additional help in that area. Buckets are nice, but as you said, require more config. I've just been graphing all of my servers' 95th percentile on a single graph, but I only have 3 servers reporting.

- The reason I chose go-metrics for the core storage is because it feels rather lightweight and backend-agnostic. I don't want to lock into a single tsdb, and I don't want to include a heavy dependency if caddy core starts recording metrics. People without the stats plugin should be impacted as little as possible. I looked at the prometheus lib, and it looks like it duplicates most of the metric storage/tracking facilities I was getting out of go-metrics, so I decided against it. I was planning to make a simple exporter that uses the plain-text protocol to feed prometheus. 

Happy to receive any help or advice you have to offer.

**Comment by captncraig** [comment]
@SuperQ I've been hacking around that limitation of go-metrics by storing arbitrary strings using the fairly standard metric/tag format of `metricName{tag=val,tag2=val2}`. It works ok, but feels like a hack.

**Comment by miekg** [comment]
Hi, I was a bit impatient and took  [caddy-stats](https://github.com/captncraig/caddy-stats) and created [caddy-prometheus](https://github.com/miekg/caddy-prometheus) which exclusively uses prometheus to export metrics.

It's pretty barebones, hardly test, but probable enough for my use case.

**Comment by captncraig** [comment]
sigh. I was hoping go-metrics would be a pretty backend-agnostic storage mechanism, but maybe that isn't the case. 

I'd really rather not require caddy users use a particular metrics system to get any value. I can only see two real good ways to accomplish this goal.

1. Store metrics in a common format and write custom pushers to various tsdbs. That is what I was trying to accomplish with go-metrics. Perhaps the prometheus client could serve this purpose too, but it seems like there is still some work needed. 

2. Define an interface for each backend to implement at a slightly higher level. You call something like `IncrementCounter(metric_name, 42)` and the plugin is responsible for storage *and* pushing to the backend. I don't really like this so much because not every backend has a real metric storage mechanism. 

At this point I am still more inclined to export to prometheus from the common storage rather than make the native storage mechanism prometheus based.

**Comment by miekg** [comment]
(I've used go-metrics in SkyDNS, at the time [a year ago?] it changed weekly and would break lots of stuff. I've stopped using it and just used prometheus-client)

Also I like prometheus :) And I don't trust monitoring systems where the client (=thing being monitored) is responsible for sending the metrics upstream.

Looking at the line count of caddy-prometheus (190 lines) I don't see why this needs to be abstracted so multiple monitoring system can use it. I.e. if influx support costs the same amount, why not create a simple middleware for that as well?

Having said all that, I don't mind if caddy-prometheus remains a third-party middleware. I just wanted to have metrics *today*, which I now have :-)

**Comment by captncraig** [comment]
If it was an isolated middleware I would agree with that sentiment. But it gets tricker when caddy core things like the raw listeners or the proxy modules want to add stats output, which I think could be really useful. There needs to be some global notion of how stats work. They would have to handle multiple possible scenarios which is more complex. I was hoping that go-metrics would be a common place anybody could write to, and output to anything. If thats not the case, I have a problem.

**Comment by captncraig** [comment]
Perhaps I should look more into the ability to attach alternate backends to prometheus client's storage mechanism.

**Comment by miekg** [comment]
I see, yes having other modules use this is a not possible. But maybe the problem you are solving has more to do with having middlewares communicate with each other than metrics.

Could we not just have something that gathers metrics and does nothing wrt to exporting it. I.e. a core module where each middleware (or whatever) can submit a name and value to. The name/value pair is then distributed to each montoring middleware. I.e. for incoming request you'll add something like
this to your middleware: `metrics.Incoming(r *http.Request)` and that's it.

**Comment by juliusv** [comment]
@captncraig Cool, let us know if we can help experimenting with the Prometheus route. Just a minimal example of how one would read back the state of a Prometheus counter, so you get an idea:

```go
package main

import (
  "fmt"

  "github.com/prometheus/client_golang/prometheus"
  dto "github.com/prometheus/client_model/go"
)

func main() {
  myCounter := prometheus.NewCounter(prometheus.CounterOpts{
    Name: "foo_metric_total",
    Help: "A test metric.",
  })

  myCounter.Add(42)

  m := &dto.Metric{}
  myCounter.Write(m)

  fmt.Println("Current counter value:", m.GetCounter().GetValue())
}
```

**Comment by mholt** [comment]
I know we have a prometheus add-on now (thanks @miekg!) -- so did we conclude that it's basically not worth it to try to implement a generic stats add-on, that each one should be custom to the provider?

**Comment by mholt** [comment]
@captncraig - and everyone else in this issue - thanks for your comments! I'm going to close this since we have the prometheus plugin now (which I realize does not satisfy all the needs raised in this issue), but I have linked to this issue from [a thread in our community forum](https://forum.caddyserver.com/t/requested-plugins-ideas-for-developers/127) where we are aggregating ideas/requests for Caddy plugins.

If you want to continue discussing the plugin before development begins on it, feel free to start a new topic on the forum. :+1: Hope to see you participate with us there!

**Comment by olivierlambert** [comment]
Hi @mholt 

Any pointer if I want to create a [Telegraf](https://github.com/influxdata/telegraf) plugin for Caddy?

Telegraf is in Go too, so I suppose it will be easy.

**Comment by miekg** [comment]
github.com/miekg/caddy-prometheus

What I really would like to see/know is how to get metrics out about TLS cert expiration.

**Comment by olivierlambert** [comment]
@miekg Do you mean that reading the Prometheus plugin code it will be easy to get the same thing in Telegraf?

**Comment by miekg** [comment]
I think it will help

**Comment by olivierlambert** [comment]
I'll take a look, thx.

**Comment by mholt** [comment]
^ I second that. The Caddy wiki is a good place to start: https://github.com/mholt/caddy/wiki
