### ISSUE TITLE
Simple Upload/Download?

### ISSUE THREAD

**Issue by srk** [mholt/caddy#580]
How hard would it be to implement a module with simple upload/download capability, like, for example:
https://github.com/biorisk/httpfolder ?

**Comment by mholt** [comment]
I think this is the same suggestion as #344 -- although it specifically talks about editing file names, the same add-on would do well to allow uploads, moving files, etc. I think they should be combined. It would need solid authentication and probably forbid plaintext HTTP usage.

"Download" is implicit in the capability of the web server so that's already done ;)

Anyone is welcome to make such an add-on, of course.

**Comment by srk** [comment]
Thanks for the speedy reply!
Extremely useful software, by the way, especially with the Let's Encrypt integration.
Now my wish list only has 'integrate with ngrok or localtunnel.me' on it.

**Comment by mholt** [comment]
(Going to close this since I don't plan on building this, but anyone finding this is welcome to.)
