### ISSUE TITLE
Feature-request: regex matching for Caddy directives

### ISSUE THREAD

**Issue by alexandreteles** [mholt/caddy#587]
Would be amazing if all Caddy directives had support to use regex. Ex.:

```
example.com {
  root /srv/www
   proxy ~ \.(css|js|png|jpg|mp3|mp4) https://your_bucket.s3.amazonaws.com/ {
    proxy_header       Host $s3_bucket
    proxy_header       Authorization ''
  }
}
```

or

```
example.com {
  root /srv/www
   internal ~ \.(sqlite|db)
}
```

It can effectively be used to set headers based on what is being served, hide files based on their extension, make proxy redirections smarter, etc.

Related to #378

**Comment by mholt** [comment]
Regular expressions have the following conflicts with the Caddy philosophy/goals:

- Go regex are slow (but [the Thompson NFA scales much better over large inputs than PCRE](https://swtch.com/~rsc/regexp/regexp1.html))
- Regex are confusing and nigh unreadable, leading to unnecessarily long lines and densely-compacted logic
- Writing a regex is essentially scripting, which we want to avoid; you shouldn't have to script your server config
- Regex encourage (or at least allow) sloppy web application design

We're not here to reinvent nginx. Caddy does things differently.

We're planning on something more intuitive and useful than matching paths with regular expressions. This mechanism would allow directives to be triggered by nearly any aspect of the request (excepting its body, probably), not just the path. Stay tuned...

In the meantime, ideas are certainly welcome, since we haven't started implementing this yet.

**Comment by alexandreteles** [comment]
> @mholt said:
> We're not here to reinvent nginx. Caddy does things differently.

Yes, I do know that. I'm just trying to point something that isn't a edge case and can slow down Caddy adoption. Until we come to a solution for this, what is the Caddy way for doing what is pointed in the examples?

**Comment by abiosoft** [comment]
As @mholt pointed out, we are working on a better way for matching paths. However, I think this is currently achievable with combination of rewrite (which supports regex) and proxy.

**Comment by alexandreteles** [comment]
> @abiosoft said:
> with combination of rewrite (which supports regex) and proxy

Can we do something like that:

```
example.com {
  root /srv/www
  rewrite {
    r ~ \.(css|js|png|jpg|mp3|mp4)
    to /s3proxy/{path}
  }
  proxy /s3proxy https://your_bucket.s3.amazonaws.com/ {
    proxy_header       Host $s3_bucket
    proxy_header       Authorization ''
  }
}
```
It's not a beautiful solution, but do you think that something on these lines will work?

**Comment by abiosoft** [comment]
That should work.
I thought `~` only indicates to nginx you're using regex so that line should be ` r \.(css|js|png|jpg|mp3|mp4)`.
```
example.com {
  root /srv/www
  rewrite {
    r \.(css|js|png|jpg|mp3|mp4)
    to /s3proxy/{path}
  }
  proxy /s3proxy https://your_bucket.s3.amazonaws.com/ {
    proxy_header       Host $s3_bucket
    proxy_header       Authorization ''
    without /s3proxy
  }
}
```

**Comment by mholt** [comment]
Thanks for the suggestion! Closing this issue to funnel the discussion into #619.
