### ISSUE TITLE
Redir + rewrite

### ISSUE THREAD

**Issue by pracucci** [mholt/caddy#592]
Hello,
I would like to rewrite `/admin*` to `/index.html` and redirect `/` to `admin`. I created the following Caddyfile:

```
localhost:9000 {
    root ./build
    redir / /admin 301
    rewrite /admin {
        regexp .*
        to     /index.html
    }
}
```

The problem is that a request to `/` redirects to `/admin` (correct), but then a request to `/admin` redirects to `admin` leading to a redirects loop (wrong).

What am I missing?

Thanks for any help,
Marco

**Comment by traeblain** [comment]
This works:
```
localhost:9000 {
    root ./build
    redir {scheme}://{host}/ /admin 301
    rewrite /admin {
        regexp .*
        to     index.html
    }
}
```

Assuming you want everything in /admin to show what is in the index.html file of the root directory.

**Comment by pracucci** [comment]
We tried it but unfortunately didn't work. How can I provide you more useful information?

**Comment by abiosoft** [comment]
`/ -> /admin` and `/admin* -> /index.html`.
But `/admin` is also a valid match for `/admin*`.

What I am seeing here is `/` to `/index.html`.

Is there anything I'm missing ?

**Comment by pracucci** [comment]
Sorry guys, we did need a quick & dirty local server, but since we weren't able to configure `/` redirect along with rewrite (due to our poor knowledge about how Caddy works) we did switch to another webserver. For this reason, I'm going to close the discussion. Thanks anyway for your help: we really appreciated it!

**Comment by mholt** [comment]
@pracucci  What'd you end up using and how did you solve it?

**Comment by pracucci** [comment]
@mholt we just switched to few lines of node.js + express code. Our use case was actually super simple and we already had quite experience on node.

**Comment by thomasheller** [comment]
> I would like to rewrite /admin* to /index.html and redirect / to admin.

That sounds like you specify an infinite loop from `/admin` to `/` and from `/` back to `/admin`. Do you mean to redirect `/` to `/admin` and `/admin` to `/admin/index.html` instead?

The second redirect from `/admin` to `/admin/index.html` should happen automatically without extra configuration. The first redirect from `/` to `/admin` however seems problematic, because `/` is works like a catch-all redirect and is apparently applied to everything under `/`.

Depending on what you're trying to achieve, this might be a duplicate of #1427, in which case you could possibly use the workaround I mentioned there. Even though @pracucci switched to Node I'm trying to resolve this, because someone else (including myself) might be looking for a solution here in a similar situation.

**Comment by pracucci** [comment]
> That sounds like you specify an infinite loop from /admin to / and from / back to /admin. Do you mean to redirect / to /admin and /admin to /admin/index.html instead?

I did mean redirect `/` to `/admin`, and serve `index.html` when `/admin` was requested (not redirect to `/admin/index.html`.

**Comment by thomasheller** [comment]
You can probably use the following Caddyfile to avoid the redirect loop (see  #1427):

```text
localhost:9000 {
  root ./build
  redir 301 {
    if {path} is /
    / /admin
  }
  rewrite /admin {
    regexp .*
    to /index.html
  }
}
```
