### ISSUE TITLE
How about the performance vs nginx?

### ISSUE THREAD

**Issue by lunny** [mholt/caddy#60]
It's a new great product about Golang. But I want to know how about the proformance with nginx?

**Comment by mholt** [comment]
That's ultimately for you to decide. Web servers are complex enough that benchmarks measure configuration and the host system itself more than code performance. That is, for benchmarks which measure req/sec.

There are unit-level benchmarks which are much more telling, but these can be less useful when you want the big picture.

However, because this is a common question, I've published some [very unscientific benchmarks on the FAQ page](https://caddyserver.com/docs/faq) (near the bottom). I've repeated the tests with a few differences every time and the results on my system are fairly consistent: Caddy and nginx are comparable in speed, although nginx is a little faster. This is expected. Caddy is fast enough for most sites, and with time, Caddy can be made faster with internal tuning.
