### ISSUE TITLE
OCSP Stapling not working with Let's Encrypt

### ISSUE THREAD

**Issue by myReaper** [mholt/caddy#605]
Hi,

it seems like OCSP Stapling is not working correctly in current 0.8.1 release (with ipfilter on Debian 8 x64 -or am i missing any dependency here?):

```
web@server:~$ caddy -version
Caddy 0.8.1
web@server:~$ cat Caddyfile
host.server.com

  root public_html/

  gzip

  ipfilter / {
    rule       block
    country    SOMECOUNTRIES
    database   GeoLite2-Country.mmdb
  }

  header / {
    Strict-Transport-Security "max-age=63072000; includeSubdomains; preload"
    X-Frame-Options "DENY"
    X-Content-Type-Options "nosniff"
  }
```

```
root@server:~# cipherscan host.server.com
..................
Target: host.server.com:443

prio  ciphersuite                  protocols              pfs                 curves
1     ECDHE-RSA-AES128-GCM-SHA256  TLSv1.2                ECDH,P-256,256bits  prime256v1,secp384r1,secp521r1
2     ECDHE-RSA-AES256-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits  prime256v1,secp384r1,secp521r1
3     ECDHE-RSA-AES128-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits  prime256v1,secp384r1,secp521r1
4     AES256-SHA                   TLSv1,TLSv1.1,TLSv1.2  None                None
5     AES128-SHA                   TLSv1,TLSv1.1,TLSv1.2  None                None

Certificate: trusted, 2048 bits, sha256WithRSAEncryption signature
TLS ticket lifetime hint: None
OCSP stapling: not supported
Cipher ordering: server
Curves ordering: server - fallback: no
Server supports secure renegotiation
Server supported compression methods: NONE
TLS Tolerance: yes
```

caddy is running as user "web", Let's Encrypt certificates have been generated correctly (and are working properly).

Best Regards
Michael

**Comment by mholt** [comment]
OCSP stapling is hard. :unamused: There's a [known bug in 0.8.1](https://community.letsencrypt.org/t/solved-ocsp-server-sometimes-has-malformed-response-of-5-bytes-or-unauthorized/10568/12?u=mholt) that I'm working on, but it's intermittent and you might be one of the unlucky ones to see it manifested.

Basically it's a race condition but over the network. Caddy 0.8.1 generates a certificate then immediately requests OCSP to staple, but the OCSP server might not be quite ready yet. But the initial response, [even if an error](https://github.com/letsencrypt/boulder/issues/1485) is cached by Akamai for some period of time, meaning that future requests also result in no stapling.

Caddy 0.8.2 (which is coming along quite well) will fix this by requesting OCSP in the background a few seconds after the initial issuance, and trying again every hour or so as needed.

**Comment by mholt** [comment]
After working on this for a couple days, I think the best thing is to just keep it the same (get OCSP immediately when the certificate is stored in memory), except I'm changing the way that OCSP is updated.

Currently, OCSP is updated hourly and only if the certificate already has a staple. I'm changing this logic so that OCSP will be requested even if it does not already have a staple. This means that OCSP requests that fail at first will (probably) be working in an hour... at least, once that caching issue is fixed upstream.

Keeping everything else the same is a much simpler implementation, since the process from beginning to end doesn't have to carry that state with it (whether to obtain OCSP immediately or asynchronously). Even if we did implement that, the initial few handshakes wouldn't have OCSP anyway, and those are the ones that matter when testing to see if it works, or serving new visitors, etc.

So, thanks for raising the issue. Over time, Caddy's OCSP implementation will continue to improve and be cleaned up as the code is optimized and things related to ACME start to settle down. Meanwhile, I've made the fix I described above and I think that will do for now.

**Comment by maxigas** [comment]
I am running caddy core 1.8.3 (Arm/core only) and OCSP stapling problem with Let's Encrypt persists:

https://www.ssllabs.com/ssltest/analyze.html?d=relay70.metatron.ai

**Comment by wmark** [comment]
@maxigas It's now reading: »OCSP stapling	Yes«. — If you believe the issue still exists then please open a separate ticket. Thanks!

**Comment by maxigas** [comment]
@wmark I also see »OCSP stapling Yes« but also the following error:

`OCSP STAPLING ERROR: OCSP response expired on Fri Apr 15 03:00:00 PDT 2016`

I open a separate issue as you suggested: #792
