### ISSUE TITLE
caddy init

### ISSUE THREAD

**Issue by piotrkubisa** [mholt/caddy#609]
First, I want thank you for doing outstanding job to developing and maintaining the Caddy. Keep it up! +1

Did not find the issue, so I was curious what do you think about quick-start command `caddy init` bundled with the caddy?

Currently, for small side projects I usually use a template of Caddyfile which I store in dotfiles repository and copying it via `cp ~/Caddyfile  ~/Code/side-project/` or just creating new by reading awesome caddy's documentation

**Comment by mholt** [comment]
> First, I want thank you for doing outstanding job to developing and maintaining the Caddy. Keep it up! +1

Thank you, it's only possible because of donations and sponsors. It's literally how I'm paying the bills right now :wink:

> Did not find the issue, so I was curious what do you think about quick-start command caddy init bundled with the caddy?

I think of `init` as a subcommand that's necessary when a program doesn't run without some boilerplate or config. But Caddy can run without any config files, so I don't think `caddy init` is necessary. Sounds like your `cp` workflow works pretty well for you. :+1:

Thanks for your feedback!
