### ISSUE TITLE
Multiple writes to response upon panic with gzip

### ISSUE THREAD

**Issue by 1lann** [mholt/caddy#616]
*This issue only occurs if you don't use the `errors` middleware, as `errors` catches panics by itself and is below the gzip directive, which allows errors to be written to gzip.*

Due to the gzip directive being below the server (The one located at `server/server.go`), in some cases some data can be written to gzip, but then a panic could occur in a deeper directive and will be caught by the `recover()` in `server/server.go`. As a result, the error code is appended to the already written gzip data, and the HTTP status and Content-Type remain unchanged.

Here's an example conversation:
```
$ curl -v --compressed localhost:9001
* Rebuilt URL to: localhost:9001/
*   Trying ::1...
* Connected to localhost (::1) port 9001 (#0)
> GET / HTTP/1.1
> Host: localhost:9001
> User-Agent: curl/7.43.0
> Accept: */*
> Accept-Encoding: deflate, gzip
> 
< HTTP/1.1 200 OK
< Server: Caddy
< Date: Fri, 19 Feb 2016 16:59:57 GMT
< Content-Length: 45
< Content-Type: application/x-gzip
< 
?       n????Internal Server Error
* Connection #0 to host localhost left intact
```
Note that the HTTP status is `200 OK`, and the Content-Type is `application/x-gzip`.

This issue does not occur if your client does not support gzip:
```
$ curl -v localhost:9001
* Rebuilt URL to: localhost:9001/
*   Trying ::1...
* Connected to localhost (::1) port 9001 (#0)
> GET / HTTP/1.1
> Host: localhost:9001
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< Server: Caddy
< X-Content-Type-Options: nosniff
< Date: Fri, 19 Feb 2016 17:07:29 GMT
< Content-Length: 22
< 
Internal Server Error
* Connection #0 to host localhost left intact
```

**Comment by mholt** [comment]
Hm, interesting problem. First question is, why is it panicking? I'd much rather fix that, since I think that's the real problem here.

Perhaps the server's panic handler could inspect the response header; if "Encoding" is set to something with "gzip" then maybe it should not write a response...

**Comment by 1lann** [comment]
The panic isn't in gzip itself, I intentionally caused the panic by using a bad template for browse.
Example:
```
{{.Truncate "a" -4}}
```

However this issue can occur with any panic with a middleware whose directive is lower than gzip's.

**Comment by mholt** [comment]
We might have to restructure our error handling logic to fully fix this.

**Comment by mholt** [comment]
The reason this happened is because the gzip handler was higher in the chain than the default error handler, which is down at the server's base handler. Using the `errors` directive fixes the problem because the errors middleware writes the error page before the gzip's writer is closed.

So, good news @1lann, Caddy 0.9 will check for `gzip` in a site's configuration when it starts up. If `gzip` is present but not `errors`, then it will silently chain in `errors` - this has no visible side-effects except fixing the bug. This is fixed now, and I will push those changes sometime soon.

I've also added `X-Content-Type-Options: nosniff` to the plaintext error pages so in case this issue pops up again for some reason. Forbidding the browser to "guess" the content type (even though we have always specified it as plain text) seems to prevent the gz downloads.
