### ISSUE TITLE
Support mmark markdown parser as a middleware

### ISSUE THREAD

**Issue by xlab** [mholt/caddy#624]
Hi Matt, thanks for this great project you've built.

I have an idea to build a static blog using Caddy, there is pretty much everything to do that well and it's not bloated in any way. However, the standard blackfriday Markdown parser has a vanilla set of Markdown features, I'd like to use much powerful (in terms of set of features included) implementations such as https://github.com/miekg/mmark by @miekg. Since it's a fork of blackfriday, I could merge it into Caddy just in a few hours, even the tests are pretty much the same.

https://github.com/xlab/caddy/tree/f/mmark — this branch works perfectly and along with built-in markdown middleware there is the mmark middleware. An example of `Caddyfile`:

```
http://localhost:8080

internal /templates

mmark /blog {
    ext     .md
    template blog /templates/blog.html
}
```

However, I've got some concerns about merging this branch into Caddy and sending a pull-request. This, in fact, should be a perfect case when it's better to have MMark separated as an add-on. But I can't figure out how to build such an add-on while keeping it integrated well as the original markdown middleware is. I'd like to have an advice :)

Or somebody could volunteer and separate this thing out into an add-on. I'll keep forked version until then. **By the way, I can send a pull-request, if this is OK to have two integrated markdown implementations.**

**Comment by mholt** [comment]
Thanks for your comments Maxim! And thanks for opening an issue before a PR for something like this.

Mmark looks neat, I hadn't seen it before. I can definitely see its utility, but I feel like it's more of an edge use case, and would make a better add-on than built into the web server.

Add-ons can't change built-in middleware, so the duplicated code (given that it's a blackfriday fork) would be unfortunate, and maintaining it will be your responsibility. But if you think more people than just yourself would really need/use mmark with Caddy, you can make it an add-on and add it to the website. https://github.com/mholt/caddy/wiki/Extending-Caddy

However, keep in mind that you can also just keep using your fork locally. [Caddyext](https://github.com/caddyserver/caddyext) makes it easy to manage plugins on your local installation. This way there's no maintenance burden since it only has to work for you, and if this feature gets requested enough, we can point them to you.

Hopefully that makes sense :smile: I'll close this now but let me know if you have any other questions!
