### ISSUE TITLE
how to set up your server to run caddy?

### ISSUE THREAD

**Issue by goldalworming** [mholt/caddy#629]
Hi, I don't understand how to run caddy as proxy server like nginx
in nginx I can access localhost port 8080 with domain dpe.com through /etc/hosts
the scenario is there is static site dpe.com and admin.dpe.com
can't I testing caddy in my local computer? or I have to use real domain to get autohttps?

lmvm@lm17 ~/go/caddy_linux_ $ sudo ./caddy 
[sudo] password for lmvm: 
2016/02/23 09:12:57 Caddyfile:2 - Parse error: Unknown directive 'localhost'
lmvm@lm17 ~/go/caddy_linux_ $ sudo ./caddy 
2016/02/23 09:13:11 Caddyfile:2 - Parse error: Unknown directive 'dpe.com'

this is my Caddyfile

	:2015
	localhost
	dpe.com
	gzip
	root /home/lmvm/assets/

	admin.dpe.com {
		proxy / localhost:8081
	}

**Comment by mholt** [comment]
If you want automatic HTTPS, you have to use a real domain name (/etc/hosts doesn't count).

And if you specify more than one host in your Caddyfile you need to enclose them both in curly braces, just like the [documentation says](https://caddyserver.com/docs/caddyfile). I'm not really sure what you're doing with yours, since you have host names where directives are expected.

**Comment by xrl** [comment]
This explanation isn't clear enough. No host is "enclosed" in curly braces. The host name should be followed by curly braces, inside of which host-specific directives are provided. Correct? What would a proper config look like?

**Comment by tobya** [comment]
The following should work for your caddyfile

    :2015 localhost dpe.com {
      gzip
      root /home/lmvm/assets/
    }

    admin.dpe.com {
      proxy / localhost:8081
    }

The first three hosts will all be gzipped and served from the same dir.

If you have details for more than 1 host in your caddyfile you need to enclose any directives in braces.
