### ISSUE TITLE
middleware.Path /test matches /test2.

### ISSUE THREAD

**Issue by jordic** [mholt/caddy#63]
At least at basicauth the behaviour for Path.Matches should be different.

/test matches /test2 .. But I think is not the desired behaviour. 

https://github.com/jordic/caddy/blob/path_matcher_bug/middleware/basicauth/basicauth_test.go#L13-L59

For the basicauth middleware, /test should not match /test2 because they can be distinct folders.  I don't know if this must be fixed, inside the auth module, or inside the middleware path. 

I think that a better aprouch should be, to consider some possible paths, like... 

/test matches /test /test/1 /test/ but it don't matches /test2 neither /test.txt

**Comment by mholt** [comment]
This is expected. Use /test/ to match just the /test/ folder and /test2/ to match the /test2/ folder.

**Comment by jordic** [comment]
Substring the non overlapping part: 
/test, /test/1 -> /1 (Contains a "/", is a subfolder)   MATCH
/test, /test/ -> / MATCH
/test, /test2 -> ( Dosen't contains a "/" is a distinc file) DON'T MATCH
/test, /test.txt -> ( Dosen't contains a "/" is a distinc file) DON'T MATCH

This is a first aproach, but i will need to try it and write tests for it.. just to ensure that it works, and I'm not missing something else.

**Comment by mholt** [comment]
I see, so basically, if the user didn't end the "from" argument with a `/` then do it for them and *then* do the matching. (Did I get it right?)

**Comment by jordic** [comment]
No, because if you do it for them, and the user wants to match a file not ended with /, it will fail.
Better to substring and check if substring begins with "/"

**Comment by mholt** [comment]
As per our discussion in Slack, we decided to leave it the same for now because of the flexibility in matching multiple files/directories at the same level that may be related (e.g. "/foo" matches "/foo", "/foobar", and "/foobaz") - but the user can exclude those and specify a particular directory by suffixing the path with `/` - in other words, `/foo/` will only match things inside the "/foo" directory because URLs to a directory (and within) must have a `/` after the directory name.

The solution for now will be to add documentation to the website about path matching, which I will do shortly.
