### ISSUE TITLE
A hard time to implement a RESTful API in a middleware

### ISSUE THREAD

**Issue by SchumacherFM** [mholt/caddy#637]
This is the extend of our discussion on [Twitter](https://twitter.com/mholt6/status/702756361851940864) in relation to https://github.com/SchumacherFM/mailout/commit/d31087daef8179639cdf5153ab3225fe87e00dc8

I'm having a hard time to implement a RESTful API design for the new caddy middleware https://github.com/SchumacherFM/mailout

Especially this line https://github.com/mholt/caddy/blob/master/server%2Fserver.go#L322 

```go
		// Fallback error response in case error handling wasn't chained in
		if status >= 400 && w.Header().Get("Content-Length") == "" {
			DefaultErrorFunc(w, r, status)
		}
```

breaks everything when I use HTTP status >= 400 codes in the middleware return argument as suggested like [here](http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#http-status).

My fix is now to always return a 200 Status Code to Caddy and call WriteHeader(anyCode) before returning. That was never in the mind of the inventor.

I'm not that into the internal API design of Caddy and I hope we can find a solution ... or leave it as it is because my hack works now ;-)

**Comment by mholt** [comment]
Suggestion -- I know this may feel a little hacky, but it's actually correct, I think.

Write the >=400 status code to the response (`WriteHeader()`), but *return* 0 for the status code (the first return value). You should still be able to return an error if you want it logged, for example, and it shouldn't affect the response.

That should preserve your API design. (Right now you're returning 200 instead of 0. I think that's fine, but it might be slightly misleading, semantically.)

**Comment by SchumacherFM** [comment]
Perfect! The mailout ServeHTTP handler returns now zero or a real error to Caddy, all other status gets written directly to the client.!

Thank you!

**Comment by mholt** [comment]
FWIW I brainstormed ways to improve the design last night, and I think I have an idea, although it needs a little more work. Will probably post an issue for it soon.

**Comment by SchumacherFM** [comment]
Cool! 

Maybe please refer me in the issue that I can get a notification :-)

**Comment by mholt** [comment]
So, thinking now that the signature won't change much because it actually is effective, I think, even for REST APIs. After re-reading my godoc, I realize I could make it clearer in the documentation. I want your feedback.

How about this revised godoc for middleware.Handler:

> Handler is like http.Handler except ServeHTTP may return a status
code and/or error.

> If ServeHTTP writes to the response body, it should return a status
code of 0. This signals to other handlers above it that the response
body is already written, and that they should not write to it also.

> If ServeHTTP encounters an error, it should return the error value
so it can be logged by designated error-handling middleware.

> If writing a response after calling another ServeHTTP method, the
returned status code SHOULD be used when writing the response.

> If handling errors after calling another ServeHTTP method, the
returned error value SHOULD be logged or handled accordingly.

> Otherwise, return values should be propagated down the middleware
chain by returning them unchanged.


Does this make sense? Is it clear?

**Comment by SchumacherFM** [comment]
I do feel better and my ServerHTTP function already uses this behaviour. 😀

Thank you!

**Comment by mholt** [comment]
Cool, thanks. I've updated the wiki too, with a better description of the return values.
