### ISSUE TITLE
Caddy should not fail if tls/acme returns error but other non-https ports are defined

### ISSUE THREAD

**Issue by jfchevrette** [mholt/caddy#638]
I'm fairly new to Caddy and I found that if I have a both TLS config and a non-TLS config Caddy will fail even though it would still be possible to continue serving only the non-TLS entries.

```
0.0.0.0:80 {
    root /data/www
    browse
}

0.0.0.0:443 {
    root /data/www
    browse
    tls {
        max_certs 10
    }
}
```

For instance running the above on my local machine, tls/acme will error out because it won't issue certificates for RFC 1918 (local) IP addresses. However in this case I would still like Caddy to not fail completely and still serve the non-TLS config. This would make sense for when I want to have a single config that works on both development and production for instance.

An idea would be for tls/acme configuration to work like the git addon where it would retry at specific intervals and soft-fail after X failed attempts. This would also cover the case where the acme API server is temporarily unreachable. This should be a toggle that defaults to hard-fail since IMO it is a better default security-wise.

Thoughts?

**Comment by mholt** [comment]
This actually has to do with the fact that on-demand TLS is enabled for `0.0.0.0:443` - you can work around this for now by using the address `:443` instead of `0.0.0.0:443`.

As for retrying, I'm not sure that starting the server if HTTPS activation fails is a good idea, although we may be forced to revisit this in the future if Let's Encrypt takes 15 minutes to issue a certificate.
