### ISSUE TITLE
White space substitution in URL by pluses (+) compatibility

### ISSUE THREAD

**Issue by albertdb** [mholt/caddy#655]
The are some cases of existing software (VLC media player, for example) that given a URL containing white spaces in the path, they substitute the white spaces by pluses (+), so `http://mysite/some file` is converted to  `http://mysite/some+file` when doing the HTTP request.

Caddy is currently unaware of this and instead of serving the corresponding files, it replies `404 Not Found`.

Could you please fix this?

Thank you very much.

**Comment by mholt** [comment]
No, since + is not valid in the path portion of a URI; it is not a valid replacement for space. Using `+` as space is only valid in application/x-www-form-urlencoded strings (like query strings). To request a URL like `http://mysite/some+file` is the client's error.

For more info, see https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1.

Thanks for raising the question! You probably won't be the only one.
