### ISSUE TITLE
Markdown variables not accessible in Included templates

### ISSUE THREAD

**Issue by cork** [mholt/caddy#660]
The following fails cause .Doc, .Docflags or .Links is not available in ".Included" templates:

Caddyfile:
```
ext .md

markdown {
	ext .md
	template template.tmpl
}
```

template.tmpl:
```
...
{{.Include "header.tmpl"}}
...
```

header.tmpl:
```
...
<title>{{.Doc.title}}</title>
...
```

index.md:
```
---
title: Example title
---
Index page
```

index.md:
```
[ERROR 500 /] template: :1:2: executing "" at <.Include>: error calling Include: template: header.tmpl:1:13: executing "header.tmpl" at <.Doc.title>: Doc is not a field of struct type middleware.Context
```

**Comment by mholt** [comment]
Ah, this is because the templates of included files aren't executed with the same context as the original markdown file. Will work on a fix for this...

**Comment by mholt** [comment]
So, I have a really hacky fix committed at 5dd9818. I don't really like it, though, since it's kind of a circular reference. Basically, the context used by Include in the case of markdown needs to be not the middleware.Context type itself, but the markdown.Data type instead. That's the only type that has Doc and DocFlags fields.

Would anyone else have a cleaner solution?

**Comment by mholt** [comment]
Nevermind. Took care of it. Thanks @tw4452852 for the feedback on my PR! @cork, this should be working now on master.

**Comment by cork** [comment]
Sorry for the late response. Just wanted to verify that this works nicely. Thx for super quick response and a very nice server!
