### ISSUE TITLE
XSS and SQL Injection Protection

### ISSUE THREAD

**Issue by aek** [mholt/caddy#674]
It would be great to have protection from XSS and SQL Injection attacks built into Caddy. Similar as the project [NAXSI](https://github.com/nbs-system/naxsi) is doing for Nginx with a rule based system.
I open this ticket to track this feature in Caddy. I don't know yet how to code in Go but I will jump into that lang to know how to built more features to Caddy if is need it. Perhaps someone could do this before I pass the learning curve necessary to get this done

**Comment by mholt** [comment]
Cool idea, could be related to #312.

**Comment by captncraig** [comment]
SQL injection is really difficult to do anything about at the webserver level, due to differing dialects and so forth. Best practice is to not put user input into queries except by the parameterization mechanisms in your sql driver, which should protect you to some degree. 

XSS is a much wider attack surface and yeah, perhaps there is more a plugin could do to stop it.

**Comment by juliuse** [comment]
to improve protection against xss on some browsers, add following into your Caddyfile:

header / {
  X-XSS-Protection "1; mode=block"
}

**Comment by mholt** [comment]
Closing since, I guess that header does the trick?

I am also thinking there's not a whole lot the web server can do to stop SQL injection.
