### ISSUE TITLE
Sourcing multiple Caddyfiles

### ISSUE THREAD

**Issue by alexpearce** [mholt/caddy#704]
For automated deployments, it would be useful to be able to either source other Caddyfiles or to specify a directory where all Caddyfiles within it are picked up. I've had a look in the docs and can't find a directive for this.

Rather than having a single Caddyfile, such as
```
example.com {
	root /www/example.com
}

sub.example.com {
	root /www/sub.example.com
}
```
One would have three Caddyfiles:
```
# Master
source *.caddy
```
and
```
# mysite.caddy
mysite.com {
	root /www/mysite.com
}
```
and
```
# sub.mysite.caddy
sub.mysite.com {
	root /www/sub.mysite.com
	gzip
	log ../access.log
}
```

## Rationale

If I deploy several sites to my server in automated way, I have to edit a single Caddyfile when I want to add or remove a site. This requires parsing the file in some way.

If I'm able to source Caddyfiles, I can just copy/move/symlink each individual Caddyfile in to a folder when the corresponding site is deployed, and have something like `source_dir /path/to/caddyfiles/*.caddy`.

## Implementation

I don't think anything fancy should happen, the `source`'d file can be substituted in to the location of the `source` directive in the master file (this is what I'm doing at the moment with a Python script). If there's a syntax error in the `source`'d file, `caddy` should behave as if there was a syntax error in a single Caddyfile.

**Comment by hubertbanas** [comment]
Check https://caddyserver.com/docs/import

**Comment by alexpearce** [comment]
:dizzy_face: I am blind. Awesome, thank you!

**Comment by mholt** [comment]
Just curious... if I did implement support for loading multiple Caddyfiles, like, from the command line, what would your preferred syntax be? Or what would make it easiest? Just specify each file or would you want Caddy to crawl a folder and its subfolders looking for files called "Caddyfile"?

Asking because I'm currently working on a big restructuring that could allow this. It's kinda "ugly" though so I'd prefer not to... does import do what you need?

**Comment by alexpearce** [comment]
It does exactly what I need already :smile: sorry I can't be more helpful…

**Comment by mholt** [comment]
Okay! No problem, that is still helpful. Maybe I don't need to implement this after all.

**Comment by davidak** [comment]
@mholt i want to deploy multiple sites on a server but don't set the root every time. so maybe if caddy uses multiple Caddyfiles (syntax could be multiple paths or gob like /var/www/*/web/Caddyfile in my case) it uses the folder the Caddyfile is in as root.
it would also help me if import works this way.

**Comment by hubertbanas** [comment]
@davidak could you please show few examples how you do it now and how you would prefer to do it?

**Comment by davidak** [comment]
@hubertbanas here is my current NixOS configuration with caddy: https://github.com/davidak/nixos-config/blob/f8b2e9f589272d11548e3f58d6cd3c5e2f351c15/binary/configuration.nix#L115

relevant part: `import /var/www/*/web/Caddyfile`

then i have the file `/var/www/test/web/Caddyfile` with the the content:

test.xxx.de
**root /var/www/test/web**
[...]

i want to delete the `root` line since the information is redundant. (the VHost should use the directory the imported Caddyfile is in, `/var/www/test/web`). so i'm able to have the website in a git repo, clone it somewhere and just use it, for example on my laptop for development.

**Comment by mholt** [comment]
@davidak Okay, this actually makes sense. Let me take an unofficial survey and see what we can do.
