### ISSUE TITLE
WWW-Authenticate: Basic authentication requires a realm

### ISSUE THREAD

**Issue by ntauthority** [mholt/caddy#708]
I'm using Caddy to provide a service with the 'basicauth' option, and trying to consume it through libavformat's HTTP client. The latter client [expects](http://git.videolan.org/?p=ffmpeg.git;a=blob;f=libavformat/httpauth.c;h=18cf36bcfece25c4f86117f444212c2608fd4bce;hb=HEAD#l95) 'WWW-Authenticate: Basic' be followed by a space, containing a realm - Caddy currently only [sends](https://github.com/mholt/caddy/blob/47c5b6c9c40200cb7483bb890ac3a0e092771021/middleware/basicauth/basicauth.go#L61) the string 'Basic', without any trailing parameter.

As RFC 7617 says:

```
   The Basic authentication scheme utilizes the Authentication Framework
   as follows.

   In challenges:

   o  The scheme name is "Basic".

   o  The authentication parameter 'realm' is REQUIRED ([RFC7235],
      Section 2.2).
```

it seems to be Caddy not adhering to the specification, and libavformat not handling 'broken' (according to the RFC) web servers properly.

**Comment by mholt** [comment]
Right, thanks for pointing this out. Let's get this fixed. How should realm be defined in a way that is both useful and user-friendly (configuration-friendly)? Can we just use the base path argument or should it be something else?

FWIW I think the basicauth middleware could use an upgrade all-around to make it easier to add multiple users or multiple paths per user, and even to load users/passwords from a file (NOT htpasswd) rather than listing it right in the Caddyfile would be cool. But that's another topic for another day.

**Comment by Tsaukpaetra** [comment]
Perhaps a sane default with configurable parameter in Advanced Settings?
(Not a Caddy user, just followed a link)

**Comment by ntauthority** [comment]
> How should realm be defined in a way that is both useful and user-friendly (configuration-friendly)? Can we just use the base path argument or should it be something else?

RFC 7235 states the realm is meant as a sub-namespace of the scheme and authority components (i.e. 'components up to the path'), so I'd assume the base path is a sufficient parameter for this purpose - outside, of course, of vanity/potential-rare-legacy purposes of specifying a custom realm (which could be done in a parameter in to the basicauth option in the configuration).

**Comment by jupiter** [comment]
The realm indicates to the browser whether it can use a previously entered password for a particular area (realm) of the site. Should you have only one realm string, but you define multiple sets of resources with different sets of credentials, the browser would try to use previously entered credentials for parts of the site that could not be authorized by those credentials, which would just mean an extra 'Unauthorized' roundtrip.

Therefore, if we use the base path of the request, the browser would not attempt a re-use of entered credentials as soon as the base path changes. To use the path of the resource(s) as defined in the Caddyfile also does not make sense, since we can have multiple resources per rule.

The only straightforward option is to say that we only support a single realm per Caddy server and assume the client will know when to provide which set of credentials. This realm could have a fixed/default string such as 'Protected' or 'Restricted area' as I've seen done before. The alternative would be to change the way Basic Auth is configured in the Caddyfile.

**Comment by wmark** [comment]
IMHO this belongs in a plugin of its own.

I understand that some users must due to legacy software, but nobody should deploy this scheme these days anymore.

**Comment by weingart** [comment]
The string "default" is as good as any, make it overridable in the Caddyfile.

**Comment by ntauthority** [comment]
Is this going to get resolved whatsoever? I'm kind of hesitant making a simple pull request that provides a default string just in order to please client implementations like libavformat for fear of rejection because of it 'not being properly fleshed out', and I'm not a Go developer so wouldn't know how to implement configurability...

**Comment by mholt** [comment]
@ntauthority It's okay to be new. A PR will undergo some scrutiny before it gets merged, so you needn't worry about doing some of it wrong. Ideally it should be tested with browsers and libavformat both to make sure things still work. If relevant, try adding a test in the basicauth_test.go file, that will help ensure it is working. :smile:

**Comment by wmark** [comment]
We will do our best to provide you hints and examples how to improve your PR should it need work. If you need anything don't hesitate to ask, annotate accordingly, and/or provide a link to the code in question.

**Comment by skorokithakis** [comment]
Can we make this bug a priority? It seems to be causing [this apache HTTP client issue](https://issues.apache.org/jira/browse/HTTPCLIENT-1604) which breaks many Android applications that use it. I'm going to recompile Caddy setting the realm to some value just as a workaround, but it would be nice if this could be fixed.

**Comment by mholt** [comment]
Thanks for making a push on this, @skorokithakis! We'll get this taken care of much more quickly with your help. :)

**Comment by skorokithakis** [comment]
Thanks for being so responsive, @mholt! I'll try the PR now and see if I can get it to build.
