### ISSUE TITLE
Caddy rebuilds content for each host alias

### ISSUE THREAD

**Issue by serussell** [mholt/caddy#710]
Caddy is generating the site content for each host alias for a single site definition.  For example, with:

```
foo.com` bar.com {
    hugo foobar.dir
}
```

Caddy will run hugo once for foo.com, and once for bar.com.  I have a large-ish site (it takes about 10 seconds to generate the hugo content) with 5 domain names pointing at it(*), meaning that refreshing the content can take up to a minute, most of which is redundant work as generation for later hosts overwrite previous hosts.

I don't know if this is me misusing Caddy, or a bug in Caddy, or a bug in the hugo plugin, or expected and correct behavior.  I'm getting around it now by redirecting all domains to a single domain, but this is less than optimal.

#### 6. What did you see instead (give full error messages and/or log)?

```
ser1% ./caddy -agree        
Activating privacy features... done.
Started building site
0 of 16 drafts rendered
0 future content
227 pages created
0 non-page files copied
82 paginator pages created
50 tags created
5 categories created
in 10785 ms
Started building site
0 of 16 drafts rendered
0 future content
227 pages created
0 non-page files copied
82 paginator pages created
50 tags created
5 categories created
in 11594 ms
Started building site
0 of 16 drafts rendered
0 future content
227 pages created
0 non-page files copied
82 paginator pages created
5 categories created
50 tags created
in 11281 ms
Started building site
0 of 16 drafts rendered
0 future content
227 pages created
0 non-page files copied
82 paginator pages created
50 tags created
5 categories created
in 11147 ms
Started building site
0 of 16 drafts rendered
0 future content
227 pages created
0 non-page files copied
82 paginator pages created
50 tags created
5 categories created
in 11181 ms
```

(and then the site list)

(*) I'm using vhosts to do things like getting "www.ser1.net" and "ser1.net" to point to the same site.  I have two TLDs, but each has a couple of subdomains that I want to direct here -- hence the number of vhost aliases for the site.

**Comment by mholt** [comment]
I am not familiar with the internals of the hugo plugin, but my guess is that it should only be setting itself up once per appearance in the Caddyfile (once per site block) rather than once per site, similar to the `git` plugin, for example. /cc @hacdias Based on our experience with debugging the git plugin, it requires a change in the plugin to use something like `c.OncePerServerBlock()` in its setup function.

But I'm going to close this issue here, please discuss it here instead: https://github.com/hacdias/caddy-hugo

Thanks for the question!
