### ISSUE TITLE
Production readiness and lego

### ISSUE THREAD

**Issue by boppreh** [mholt/caddy#716]
[`lego`](https://github.com/xenolf/lego) includes a fairly strong disclaimer:

> This is a work in progress. Please do NOT run this on a production server and please report any bugs you find!

Caddy's automatic HTTPS seems to rely heavily on lego, but does not include such disclaimers. How's Caddy's production readiness? Can I expose a Caddy server to the internet?

PS: Love the project, thanks a lot for the work so far.

**Comment by mholt** [comment]
Hey @boppreh, good question. Caddy's "production readiness" is an important discussion to have. In short, you can use Caddy on the Internet. Lots of people do, and it serves tens of thousands of domains today.

That disclaimer is there because the library is still new and is likely to experience breaking changes before it reaches 1.0.

A brief history: @xenolf first [contributed to Caddy](https://github.com/mholt/caddy/pull/99) last June. We got talking about the upcoming Let's Encrypt integration, and he wanted to take on the task of writing the first unofficial ACME client. We both knew it would be immensely valuable to a broad audience since it would be written in Go, and thus would be fast, cross-platform compatible, and free of dependencies. The goal was to make a package that other Go programs could import and use, as well as a simple CLI tool mainly to test the underlying package (but nothing too elaborate). So lego was originally written *for* Caddy to use, and indeed, it's how lego made its debut.

And it has performed well so far, serving over 50,000 certificates, ~10,000 of them through Caddy (although I have reason to believe it has generated at least 10,000 more by now, since my latest stats are about a month old).

Remember, the lego CLI tool and its underlying acme package are two different things. The underlying acme package is saturated with tests (with more on the way). The most difficult part are the ACME challenges. The http and tls-sni challenges are fairly straightforward and easy to test; these implementations are already quite mature and robust. The dns challenge is harder, but a ~dozen developers have been pouring over the code recently and all the DNS challenge providers are under test. All the remaining work is basically focused on fixing edge cases.

The ACME spec is still not finalized, so that disclaimer on lego will probably remain until after ACME stops changing.

So while lego is actively under development, Caddy releases only use lego at commits that are not known to have major outstanding issues. There may be a release where we make a mistake, but we always try to be careful here. :innocent: 

Also, consider that the Go standard library (which Caddy uses heavily) has been worked on by hundreds of developers over the last ~7 years, including being authored by such developers as Rob Pike (Plan 9), Ken Thompson (Unix + UTF-8), Brad Fitzpatrick (memcached, LiveJournal).

Here's a recent writeup (that I did not solicit -- it was independent!) about @DenBeke's experience using Caddy in production: https://denbeke.be/blog/servers/two-months-ago-i-started-to-serve-the-web-like-its-2016-and-im-still-loving-caddy-migrating-from-nginx-to-caddy-server/

Anyway, that was a long answer. Hopefully informative.

**Comment by boppreh** [comment]
Amazing answer. I did not know about lego's history.

I already had high respect for this project, and it just doubled. I'm definitely migrating everything I have over to Caddy and recommending to everyone with a ear to spare.

Thank you

**Comment by mholt** [comment]
Great! I will add that Caddy is still pre-1.0, so it may have some breaking changes along the way or some buggy edge cases, but there hasn't been a severe bug that in Caddy that I can think of that took down whole sites.

Let us know how it goes! Lots of people are asking this question, so if you blog about it, it's sure to get some traffic over time.
