### ISSUE TITLE
Feature request: daemonise caddy

### ISSUE THREAD

**Issue by mnzt** [mholt/caddy#732]
It would be really useful in my opinion if Caddy could daemonise itself (automatically run in the background), being launched in the daemon via a `-d` flag, or similar. 

What're other people's thoughts on this?

**Adding to top for exposure:**
If not a native feature, how about an addon?

**Comment by mholt** [comment]
@kardianos was actually working on this before. I closed the PR because I think it needs a lot more testing and docs, since this is not a "light" change to make: https://github.com/mholt/caddy/pull/588

I also might need to be convinced that daemonizing is the job of the web server instead of the system/sysadmin. :wink:

**Comment by tehscorpion** [comment]
Modern systems with for example systemd require that services are running in foreground, docker does that too

**Comment by kardianos** [comment]
I agree that modern job systems have the service run in the foreground.

On Unix type system, no special change is needed except to obey signals and have correct service files placed.

On Windows, participation is required for the service callback and registration is even more arcane.

-------------------------------------

I could revive that PR if interest, I just kinda ran out of time then. If there are a few others who could help test, I could work on it again.

**Comment by kardianos** [comment]
Lastly, I will note for the average user creating a service (systemd, upstart) file on linux is often beyond what they want to research and create.

**Comment by mholt** [comment]
@kardianos You're right, which is why I support the change overall, but it will require a lot of testing for potential "gotchas" since there's a lot riding on a feature like that. Right now if Caddy goes down in production it's not Caddy's fault, but if we integrate this capability, we incur a heavy responsibility. And possible maintenance burden. It will have to be tested on many platforms over the course of a long time, I think.

**Comment by kardianos** [comment]
I agree with you in idea I think, but you may be overstating the effect of this change. I think more then anything this is a potential mindset change that you are now "endorsing" then a technical change.

You could add a disclaimer above the flag and in the help message :).

**Comment by tehscorpion** [comment]
@mholt also consider making deb/rpm packages for easier updating

**Comment by tpng** [comment]
On Windows, I prefer to use something like [nssm](https://nssm.cc/) to turn my Go binary into service since I don't have to implement the service logic in my source code.
I believe leaving the service logic to another tool (e.g. systemd, upstart, supervisord, etc) that do it well is the way to go.

**Comment by tpng** [comment]
If we are going to implement this, I think we need to clarify the use cases and whether there are better solutions.

If we just want Caddy to run in the background, why not just `caddy &` or `start /b caddy` to send it to background and forget about it?
We probably also want to keep Caddy running, so what happens when Caddy crashes?
At this point we would need something else to monitor our process and what would that be?
If we end up requiring a 3rd party to keep us alive, do we really need our own service logic?

**Comment by kardianos** [comment]
@tpng I don't have a dog in this, however as a windows user I don't see a reason to use nssm. If I run a program as a service it supports windows callbacks.

**Comment by captncraig** [comment]
Maybe a good first step would be adding documentation for adding a caddy
service via nssm. People may still want a native service mode, but that
will are least show people how it could be done without it.

**Comment by tpng** [comment]
@kardianos Yes, that's just my use case and how I am deploying Go binary to Windows Server.

@captncraig I think we can add a section in the User Guide for deployment recipes on different platform.

**Comment by kardianos** [comment]
Nssm and a native service don't mix. Do one or another. Such a first step
is the step.

**Comment by tpng** [comment]
I see. Is the native service implemented only for Windows or for all platforms? If it is only for Windows, will it affect other platforms?

**Comment by mnzt** [comment]
@tpng From a Go perspective, you can easily check the architecture and adjust depending on that.

**Comment by tpng** [comment]
From the previous PR https://github.com/mholt/caddy/pull/588, it seems to support most platforms, so I have no further concerns in this case.

**Comment by mholt** [comment]
Been looking into this quite a bit and talking some friends with more experience than I on the matter. I don't think Caddy is in the business of daemonizing.

To run Caddy in the background, use `&`. This is how I run all my sites on DigitalOcean. I've found that on AWS you have to use `nohup` as well because for some reason the AMI sends Caddy a SIGHUP randomly... anyway, Caddy (core -- can't speak for plugins) doesn't crash in production on its own, so & is a pretty good way to go, honestly.

To make Caddy a service on Linux/BSD, use something like systemd, upstart, or another process/service manager.

To make Caddy a service on Windows, well:

> If you’re a developer who wants to release a Windows Service that users can install and uninstall you should use InstallShield.

&mdash;[MSDN](https://msdn.microsoft.com/en-us/library/sd8zc8ha(v=vs.110).aspx)

@kardianos 
> I agree with you in idea I think, but you may be overstating the effect of this change.

I don't think so. Remember, I'm the one who's liable if somebody's site goes down. :smile: If we don't even attempt this integration (which I still feel is out of scope for Caddy) then the responsibility rests with the sysadmin, which I believe is where it should be.

@mnzt I just now saw your addendum to the original post about it being an add-on. I'm working on restructuring Caddy so plugins (no longer to be called "add-ons" -- finally!) can have a lot more power and flexibility, including the ability to manage the process. Well, I can't promise that yet, but it's what I'm hoping for. (Already some things I was hoping for out of this aren't going to be happening due to technical complications. :disappointed:) But if it works out, add-ons could certainly integrate with the system more than Caddy core is willing to do.

If you'd like to share a way to run Caddy as a service/daemon, you can contribute to the [dist/init folder](https://github.com/mholt/caddy/tree/master/dist/init) in this repo, as it will be going out with all Caddy releases in the future, starting with the next release.

Thanks for the discussion! Going to close this now but not to shut down the discussion, just to dequeue it from my "todo" list.

**Comment by mnzt** [comment]
Sounds good @mholt! Looking forward to the new plugin system. 

Is there a way we can get entries added into the docs? Personally I think it'll be beneficial to have a **How to run Caddy in the background** on the FAQ

**Comment by mholt** [comment]
Sure, submit a PR to https://github.com/caddyserver/caddyserver.com
