### ISSUE TITLE
Remove gzip from default config in quick start guide

### ISSUE THREAD

**Issue by Immortalin** [mholt/caddy#74]
Hi, it would be prudent to remove gzip from the default quick start guide as it is vulnerable to [this](breachattack.com/), more information and discussion [here](https://news.ycombinator.com/item?id=9532978).

**Comment by mholt** [comment]
I appreciate the abundance of caution, so thanks for the suggestion. CRIME exploits TLS compression which Caddy does not use, and neither do most major browsers. [It is not likely that Caddy servers are vulnerable to CRIME](https://community.qualys.com/blogs/securitylabs/2012/09/14/crime-information-leakage-attack-against-ssltls) At least, I have yet to discover otherwise.
