### ISSUE TITLE
Feature: Setting context for various options

### ISSUE THREAD

**Issue by sNuuFix** [mholt/caddy#796]
Hello. It would be awesome if there would be something like nginx location block or conditionals with regex support, because then it would be much easier to set headers for static assets and much more.

Example from nginx:
`location ~* \.(ico|css|js|gif|jpe?g|png)(\?[0-9]+)?$ {
    expires max;
}`

I've worked around this by setting header location to my assets folder, but there are some assets that are at root, favicon.ico for example. (yes, I know I can place them elsewhere, but that's not the point) Changing expires header on root affects php files also and that's not good in most cases.

**Comment by mholt** [comment]
We've kind of gone back and forth on this in #619. Basically, the complexity of regular expressions and pattern matching and other complex rules aren't really in the best interest of Caddy's users, since Caddy aims to be easier to use than other web servers.

We don't yet know of a good way to implement more complex request matching without vast complications to the code and/or the Caddyfile syntax (which we're not going to change drastically). If you have any suggestions then we're all ears!

**Comment by sNuuFix** [comment]
Thanks for information. Now I understand the philosophy of Caddy. I agree that simple syntax is better from speed perspective and I'm a speed freak myself. Regular expressions are slow in any language and should be avoided. My way of seeing things was too broad.

Then I guess it would be cool to add extension filter option to header config syntax. That should meet the needs of most real world caching configurations.

**Comment by mholt** [comment]
I will close this in favor of the other issue but feel free to comment there if you have more feedback about how we can balance usability (and Caddy philosophy) with capability!
