### ISSUE TITLE
proxy: Caddy hangs with max_fails 0 and a unresolved host

### ISSUE THREAD

**Issue by princemaple** [mholt/caddy#812]
As suggested by @wmark , reporting [this issue](https://github.com/mholt/caddy/issues/808#issuecomment-217547624) here

#### 1. What version of Caddy are you running (`caddy -version`)?
0.8.3

#### 2. What are you trying to do?
using caddy as a reverse proxy

#### 3. What is your entire Caddyfile?
```text
http://localhost {
  log / stdout "{host} {upstream}"
  errors stdout

  proxy / web:8080 {
    fail_timeout 2s
    max_fails 0
    proxy_header Host {host}
    proxy_header X-Real-IP {remote}
    proxy_header X-Forwarded-Proto {scheme}
  }
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
docker-compose

#### 5. What did you expect to see?
Caddy should spit out an error or something, it should not hang.

#### 6. What did you see instead (give full error messages and/or log)?
`curl -v localhost:8080`

```
* Rebuilt URL to: localhost:8080/
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
>
♥
```
had to `ctrl+c` there

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
One could use my setup in [this comment](https://github.com/mholt/caddy/issues/808#issuecomment-217609545) or simply setup a Caddy server with a proxy directive pointing to some non-existent hostname.

**Comment by mholt** [comment]
So by "hang" you mean it just doesn't do anything? Or do you mean the CPU is spinning?

**Comment by princemaple** [comment]
I went back to test again to get the stats.
some update:

- the cpu is spinning, taking about 40-70% of CPU on a scaleway.com VC1S machine
- it actually doesn't hang forever, after exactly 1 minute, curl gets a 502 back

**Comment by mholt** [comment]
Okay, the spinning is expected, as I mentioned in the other issue. By setting max_fails to 0, you're telling the proxy to never mark the backend as down, no matter how many requests fail. Caddy's proxy middleware is designed to loop over "up" hosts until a request succeeds. Most requests go over a network and because they block, they don't spin the CPU so fast, but localhost requests are nearly instant, so it keeps the CPU busy. There's also the (reasonable?) assumption that a 

Anyway, I guess the pragmatic answer right now is, "Don't do that." (There's a hilarious Rob Pike reference here.) Set max_fails to > 0 or use the default.

We could probably handle this better but that's out the scope of this issue, and is already open in #754. I do think we should just ask someone to own the issue and fix it in a way that is in the best interest of all Caddy users, to just resolve these edge cases.

**Comment by princemaple** [comment]
:+1:
