### ISSUE TITLE
Not able to use HTTPS as www-data user in systemd caddy.service (permission problem)

### ISSUE THREAD

**Issue by suiluj** [mholt/caddy#833]
#### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.8.3 on a Raspberry Pi 3

#### 2. What are you trying to do?
Enable HTTPS via systemd autostart

#### 3. What is your entire Caddyfile?
```
https://youlius.dynu.com {
        root /home/pi/caddyserver/website
        fastcgi / /var/run/php5-fpm.sock php
}
```
#### 4. How did you run Caddy (give the full command and describe the execution environment)?
Caddy autostarts after boot with systemd service

#### 5. What did you expect to see?
Enabled Webserver with HTTPS

#### 6. What did you see instead (give full error messages and/or log)?
The Server is not able to start with a HTTPS Domain in the caddyfile.
(if i change the Caddyfile to normal http everything is fine)

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
I followed the tutorial for systemd described [here] (https://github.com/mholt/caddy/tree/master/dist/init/linux-systemd)

I think my www-data user is not able to create folders and files for the ssl certificates because of wrong permissions.
**The .caddy folder was not created in the home directory** when i followed the tutorial. I created it myself and set permissions for the www-data user but nothing happend.
When start caddy manually with my pi user everythings works as expected and certificates were created in my /home/pi/.caddy folder but of course i want to start caddy from systemd with the www-data user instead of the pi user.

I did not set any environment variables because i did not understand how to set this for the wdata-user.

Thank you for your help, I really appreciate it.
Regards Julius

**Comment by abiosoft** [comment]
This is not a Caddy issue as stated [here](https://github.com/mholt/caddy/blob/master/dist/init/README.md). 

Consider posting a message on https://gitter.im/caddyserver/support and hopefully one of the maintainers will be available to help you out.

**Comment by suiluj** [comment]
okay.
now i just use a simple rc.local command...

**Comment by wmark** [comment]
FYI, reports of errors with *init* daemons are useless and **cannot be properly diagnosed without the accompanying log output.** It's like saying »Caddy didn't start« and then omitting the error message.

Chances are that something helpful had been logged.

My first guess with *systemd* is that you have an older version which does not understand one or more directives I have used in the provided *systemd unit file*. For example, latest *Debian* comes with a very old (more than 15 months) *systemd* that does not understand `AmbientCapabilities`, which then result in *Caddy* not being able to open port `443`.

**Comment by wmark** [comment]
In the course of the tutorial you create `/etc/ssl/caddy` and set permissions `rwx` for its owner, `www-data`. Subsequently *Caddy* will be able to create files and directories there; *systemd* will retain those `rwx` rights due to directive `ReadWriteDirectories=/etc/ssl/caddy` having been set.

What fails is binding to port 443, which is a *privileged port* (0–1023; rarely ≤ 2000). Only processes with capability `CAP_NET_BIND_SERVICE` can listen on those ports on Linux (see `net.inet.ip.portrange.reserved{low,high}` on *BSD). On most, not all, GNU/Linux distributions that capability is granted to `UID=0` (»root«) only. (It's `UID≤999` on some old Unix.)

To avoid `UID=0` we use directive `AmbientCapabilities=CAP_NET_BIND_SERVICE` in the *systemd unit file.* It is safer to grant that capability this way, for one context, than setting it for all users allowed to run `caddy` by the now *with systemd* deprecated `setcap`.

On a server, if you don't have *systemd* then consider utilizing a *loader*: A program with the sole purpose of starting *caddy* with that capability. (Take a look on *chpst* and friends!)

I guess the logfiles—displayed using `journalctl --boot -u caddy.service`—did contain a line like `AmbientCapabilities: unknown lvalue` which tells that checking the version of *systemd* is in order, to the end of upgrading the package.

**Comment by suiluj** [comment]
@wmark Thank you for your detailed explanation.
The systemd **version** hint was useful i think because currently i am no able to use the `systemctl edit`
 command for example.
I'm happy with my result at first but will try systemd in the next time. For now it's enough to have a running server for some tests.
But really thank you for your help and your systemd tutorial. I think I made a stupid beginner mistake somewhere but as long as autostart works now everything is fine. 
So this issue can be closed

**Comment by wmark** [comment]
I've been so verbose and locked this ticket to use it for later reference. That is, if someone stumbles upon this or similar behaviour I would just mark the issue as duplicate of this one. Not having a particular operator in mind.
