### ISSUE TITLE
Suggestion: better handling of common site configuration

### ISSUE THREAD

**Issue by dteoh** [mholt/caddy#878]
I misunderstood the docs about sharing configuration, so I made a Caddyfile like this:

```
foo.com {
  root /www/foo
}

bar.com {
  root /www/bar
}

foo.com,
bar.com {
  tls admin@example.org
  gzip
}
```

But this doesn't work, the server will complain about not being able to serve `foo.com:443` and `bar.com:443`. The fix is to put the `tls` and `gzip` configuration into each site block.

I propose that one of these alternatives be allowed to work:

```
tls admin@example.org
gzip

foo.com {
  root /www/foo
}

bar.com {
  root /www/bar
}
```

```
_defaults {
  tls admin@example.org
  gzip
}

foo.com {
  root /www/foo
}

bar.com {
  root /www/bar
}
```

What do you think?

**Comment by mholt** [comment]
Hi @dteoh, thanks for the feedback!

The Caddyfile is actually very simple and people tend to overthink it, usually because they're programmers or they're coming from server software that requires more complex configurations.

The first token (or word) in the Caddyfile must be a site address. So in your example:

```
tls admin@example.org
gzip

foo.com {
  root /www/foo
}
```

How does Caddy know that `tls` is not a site address? It's a perfectly valid hostname.

Because of this, and for the sake of clarity and consistency, all directives must go in a site block, or under a site address. The revised docs coming after version 0.9 will clarify this more visually so users can see at a glance how it works.

> But this doesn't work, the server will complain about not being able to serve foo.com:443 and bar.com:443

This error occurs because site addresses act like keys and must be unique. It also keeps things simple for the site maintainer so they have only one place to look for that site's configuration.

As for this proposal:

```
_defaults {
  tls admin@example.org
  gzip
}
```

We've looked at this before in #619. We want to avoid making exceptions as much as possible and inheritance into multiple server blocks gets very confusing and complicated very quickly. (If you're an OOP programmer you'll understand this.)

You are allowed to copy and paste in the Caddyfile. :smile: It's okay to have the word `gzip` multiple times. I do not think it is too hard to type. You can also use the `-email` flag to set the email address for all sites at once.

Hope that is helpful.

**Comment by dteoh** [comment]
Thanks for replying. You are right, coming from Nginx or other web servers, there are more avenues to specify configuration.

> How does Caddy know that tls is not a site address? It's a perfectly valid hostname.

Fair point, allowing hostnames as a free-standing token makes this unsolvable (or at least not in a clean way) for the time being.

> You are allowed to copy and paste in the Caddyfile. 😄 It's okay to have the word gzip multiple times. I do not think it is too hard to type. 

Sure, I have no problem with copy-pasting when there are only a few sites to manage. But I think for larger deployments that use more detailed configuration, this just invites problems. The simplicity of the config format ends up getting bogged with boilerplate. Updating becomes a mess.

I don't think there is a need to result to multiple inheritance or mixins or other equivalent programming language facility to solve this, but I do think there needs to be a mechanism to turn on a list of configured features that is the default for all sites, whatever form it may take. For now, I will just get my configuration management tool to manage the Caddyfile as a template.

**Comment by mholt** [comment]
That's fine. And after 0.9 is said and done, I'll begin work on Caddy's API which should make it easier to automate more advanced configurations.
