### ISSUE TITLE
the caddy logger should be passed from main

### ISSUE THREAD

**Issue by groob** [mholt/caddy#879]
Hello, 

I would like to be able to configure and pass a logger from a custom `main.go` and have the log format be consistent across plugins. Currently, there are a lot of cases where packages `log.Printf(...)` directly instead of using the logger from main. 

Would you consider making such a change in caddy for v0.9 or v0.10? 
I'd like to avoid multiple log levels and provide a structured key=value log through the application.

**Comment by mholt** [comment]
Hey groob, thanks for the question!

Have you considered calling `log.SetOutput()`? This will let you use any io.Writer you want.

Note that the standard library (net/http, for example) uses the default logger quite heavily and AFAIK there is not a way to change that, other than calling `log.SetOutput()`.

(Calling `caddymain.Run()` will override what you set, though, since it also calls log.SetOutput -- maybe we could figure out another way to set the output if you need to use Run, or you can just call caddy.Start() directly instead...)

**Comment by groob** [comment]
I'm actually writing my own main instead of using `caddymain` package. 
I'm using caddy because of it's support for tls, the fileserver and some of the plugins like `caddy-git` but the bulk of the application is a REST api written using `go-kit`. This might be an unusual way to package caddy, but, at least for now, it's a quick way to avoid rewriting a lot of code.

I wasn't aware of `log.SetOutput()` but I'll try to find a way to use that to set my preferred output.

**Comment by groob** [comment]
That worked out for the most part! Turns out the go-kit project provides a writer that I can pass to SetOutput. 

```
	var logger kitlog.Logger
	{
		logger = kitlog.NewLogfmtLogger(os.Stderr)
		logger = kitlog.NewContext(logger).With("ts", log.DefaultTimestampUTC)
		logger = kitlog.NewContext(logger).With("caller", log.DefaultCaller)
	}
	kitWriter := kitlog.NewStdlibAdapter(logger)
	log.SetOutput(kitwriter)
```

````
ts=2016-06-11T16:42:26Z caller=stdlib.go:89 ts="2016/06/11 12:42:26" msg="[INFO] SIGINT: Shutting down"
```

**Comment by mholt** [comment]
Cool, that works nicely :)
