### ISSUE TITLE
ratelimit plugin

### ISSUE THREAD

**Issue by xuqingfeng** [mholt/caddy#922]
Working on a `ratelimit` plugin for caddy: https://github.com/xuqingfeng/caddy-rate-limit

Want to hear your thoughts 🙇

**Comment by mholt** [comment]
That's awesome! Looking forward to seeing it completed. We'll get that on the download page. I hope others will chime in with feedback.

**Comment by k0nsl** [comment]
This is exactly what I need. Thank you!

**Comment by mholt** [comment]
See #79 for a previous discussion of rate limiting, maybe it will have some ideas/suggestions!

**Comment by mholt** [comment]
@xuqingfeng Let me know when you're ready to put this on the download page for others to use! I'll help you out with that since we're still transitioning to 0.9.

Going to close this for now, though, since there's nothing actionable for the Caddy developers to do here.

Really looking forward to it! Again, take a look at that issue I linked to ^ and see if that gives you some ideas.

**Comment by xuqingfeng** [comment]
The link is really helpful 😄 ,I will do more tests on it, will let you know when I'm ready.

**Comment by abiosoft** [comment]
Is this useful ? https://godoc.org/golang.org/x/time/rate

**Comment by xuqingfeng** [comment]
@abiosoft Yes! The implementation of `token bucket` is pretty convenient.

**Comment by xuqingfeng** [comment]
Just setup a demo site: https://caddy-rate-limit.gohack.xyz/

**Comment by mholt** [comment]
That's cool! I saw the 429 response after holding Cmd+R for a few seconds.

**Comment by mholt** [comment]
@xuqingfeng So FYI, this is already available on the download page of the Caddy website but it wasn't built into Caddy 0.9's list of directives (d'oh) but 0.9.1 will have it working fully.
