### ISSUE TITLE
Downloads at mysite.tld/user1/xxx resolving to mysite.tld/xxx

### ISSUE THREAD

**Issue by MSF-Jarvis** [mholt/caddy#969]
#### 1. What version of Caddy are you running (`caddy -version`)?

0.9.0

#### 2. What are you trying to do?

Trying to serve a downloads index powered by `browse` at mysite.tld/user1

#### 3. What is your entire Caddyfile?
```text
mysite.tld/user1 {
    root /var/www/user1
    browse
    tls msfjarvis@gmail.com
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

Used the systemd unit from the caddyserver.com/examples repo

#### 5. What did you expect to see?

When downloading a file from there, expected it to download properly.

#### 6. What did you see instead (give full error messages and/or log)?

```
Jul 29 12:37:06 kreiger caddy[20713]: 2016/07/29 12:37:06 [INFO] mysite.tld - No such site at :443 (Remote: 112.196.146....trek852)
```

The download at `mysite.tld/user1/file.zip`, when clicked on, resolved automatically to `mysite.tld/file.zip` and gave the `No such site at :443` error message on the browser window and the caddy log

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Use the Caddyfile above and place a file in your specified root. Try downloading it, If all goes wrong you will hit the bug.

#### 8.  Additional Info

I can reproduce this bug locally by serving at :2015 with `tls off` too.

**Comment by mholt** [comment]
That's weird, links to files in the default browse template are relative URLs, i.e. "./file". I would not expect the browser to make that an absolute path...

**Comment by tw4452852** [comment]
Hi @mholt , I think the reason is that we trim the site address from the URL.
Assume the origin the URL is `http://localhost/user1/1.txt` and the site address is `localhost/user1`,
the URL is changed to `http://1.txt` finally

**Comment by MSF-Jarvis** [comment]
I don't see any logic behind this, sounds like a regression to me. 0.9 has
already been loads of work so I'm not blaming anyone for this oversight,
just a minor inconvenience.

**Comment by tw4452852** [comment]
Dismiss my previous comment. I did a test to show the problem:
At first, let's assume the current directory struct like this:
```
.
..
test.txt
p1/
Caddyfile
```
And Caddyfile's content:

```
127.0.0.1:2015/u1
browse
```
We start caddy at current directory.
At first let's request a URL `http://127.0.0.1:12345/u1`, 
and we find the generate links are wrong, e.g. the `p1` directory is `http://127.0.0.1:12345/p1`.
let's request a subtle different URL `http://127.0.0.1:12345/u1/`(add a slash at tail)
and we find the generate links are right.

**Comment by MSF-Jarvis** [comment]
@tw4452852 interesting observation! This indeed works though I don't think `localhost/user1/extras.zip/` is an ideal URL to share

**Comment by tw4452852** [comment]
Hi @MSF-Jarvis , could you please try with my patch to check if it fixes your problem? Thanks.

**Comment by MSF-Jarvis** [comment]
@tw4452852 I'm having errors with `go get github.com/mholt/caddy/caddy`

```
# github.com/aead/poly1305
.go/src/github.com/aead/poly1305/poly1305_amd64.s:8 6a: No such file or directory: textflag.h
# github.com/aead/chacha20/chacha
.go/src/github.com/aead/chacha20/chacha/chachaSSE_amd64.s:8 6a: No such file or directory: textflag.h
# github.com/lucas-clemente/aes12
.go/src/github.com/lucas-clemente/aes12/asm_amd64.s:6 6a: No such file or directory: textflag.h
# golang.org/x/crypto/ocsp
.go/src/golang.org/x/crypto/ocsp/ocsp.go:574: undefined: crypto.Signer
# golang.org/x/net/http2
.go/src/golang.org/x/net/http2/transport.go:216: req.Cancel undefined (type *http.Request has no field or method Cancel)
.go/src/golang.org/x/net/http2/transport.go:220: req.Cancel undefined (type *http.Request has no field or method Cancel)
.go/src/golang.org/x/net/http2/transport.go:801: req.Cancel undefined (type *http.Request has no field or method Cancel)
# github.com/miekg/dns
.go/src/github.com/miekg/dns/dnssec.go:256: undefined: crypto.Signer
.go/src/github.com/miekg/dns/dnssec.go:320: undefined: crypto.Signer
.go/src/github.com/miekg/dns/sig0.go:17: undefined: crypto.Signer
# github.com/gorilla/websocket
.go/src/github.com/gorilla/websocket/client.go:361: unknown tls.Config field 'GetCertificate' in struct literal
```

But I guess this discussion is off-topic for this issue, can you hit me up on Hangouts (`msfjarvis@gmail.com`) or Telegram(`@MSFJarvis`) ?

**Comment by tw4452852** [comment]
@MSF-Jarvis Try `go get -u -v github.com/mhot/caddy/caddy` ?

**Comment by MSF-Jarvis** [comment]
same old, but I did manage to see a couple of downloads. And you have a typo at `mhot` :p

**Comment by mholt** [comment]
So wait, a browser rendering a page at `http://127.0.0.1:2015/u1` with a link on that page `href="./p1"` should result in `http://127.0.0.1:2015/u1/p1`, not `http://127.0.0.1:2015/p1` - right?

**Comment by mholt** [comment]
This sounds more like a browser bug than a Caddy problem.

Trailing slashes shouldn't have anything to do with whether the path is relative or not.

**Comment by MSF-Jarvis** [comment]
I can reproduce it on multiple platforms with different browsers. Doesn't
sound like a browser bug to me.

**Comment by mholt** [comment]
Sure, I can too, but I'm still baffled that "./p1" is not treated as a relative path. Isn't that supposed to be relative to the current page's path?

**Comment by MSF-Jarvis** [comment]
If it wasn't, this issue wouldn't have been created :)

Can you please test Tw's patch, I am having errors on `go get -u -v
github.com/mholt/caddy/caddy`

**Comment by mholt** [comment]
Okay, I follow now. I was confused by "trailing slash" since I thought for some reason we were talking about adding a trailing slash to the link instead of the page's path in the URL.

So, to recap the problem:

```
localhost/a
browse
```

If the site root (cwd) has no index file, it will serve the directory listing, which [normally gets redirected to have a trailing slash](https://github.com/mholt/caddy/blob/7157bdc79d38e203386d7e12d7065d884166c431/caddyhttp/staticfiles/fileserver.go#L79-L93) because it is a directory. But in this case, the path is trimmed to `/` because of the new logic in the server to handle site addresses with a base path of something like `/a`. Because the middleware chain then sees a path of `/`, it doesn't see a need to do a redirect.

But this Caddyfile:

```
localhost/a/
browse
```

Will render the site properly at `http://localhost:2015/a/` and links will work! However, it does not redirect `http://localhost:2015/a` to `http://localhost:2015/a/` because there is no site defined for `/a`, only `/a/` (which `/a` does not match, of course).

I agree this is not expected behavior, but it's hard-pressed to call it an actual bug.

I'll look at @tw4452852's pull request next, we have to make sure there are no negative consequences of doing that blanket redirect.

**Comment by mholt** [comment]
Here's one workaround I came up with, but I'm not sure I like it (I'm not sure if it's worth the complexity).

In the first ServeHTTP method, when we trim the path for the  middleware chain, I add this line:

```go
r.Header.Set("Caddy-Original-Request-Path", r.URL.Path)
```

So that, when performing redirects, the full, original URI can be preserved and used when needed.

Then, where the `browse` middleware redirects directory paths to their canonical path (which means adding a trailing `/`):

```go
path := r.URL.Path
if origPath := r.Header.Get("Caddy-Original-Request-Path"); origPath != "" {
	path = origPath
}
if !strings.HasSuffix(path, "/") {
	http.Redirect(w, r, path+"/", http.StatusTemporaryRedirect)
	return http.StatusTemporaryRedirect, nil
}
```

The same logic (checking that header field) would be used in the `fileserver.go` file to redirect to canonical path.

Now this is kind of hacky and I'm not sure I like it. The best alternative to this might just be to set your Caddyfile to use `localhost/a/` (with trailing slash) as the site address instead of `localhost/a` with the obvious downside being that you have to type the trailing slash in the browser since it won't redirect for you.

Thoughts?

**Comment by MSF-Jarvis** [comment]
I'm not seeing any common user out there doing it. I can remember to add
the slash, can't say so about the hundreds or thousands that'll visit the
site. And plus the issue is not that `localhost/a` is borked.
`localhost/a/file.zip` is broken because it gets mapped to
`localhost/file.zip` which is ridiculously annoying. Adding a `/` to the
end of `localhost/a/file.zip` to make it `localhost/a/file.zip/` fixes the
wrong mapping. I do not feel that this solution is good enough for a long
term perspective, simply because it's hacky.

**Comment by mholt** [comment]
> Adding a `/` to the
end of `localhost/a/file.zip` to make it `localhost/a/file.zip/` fixes the
wrong mapping.

No, I mean add the `/` to the end of `localhost/a` in your Caddyfile.

> I do not feel that this solution is good enough for a long
term perspective, simply because it's hacky.

I do agree with you.

Maybe the best thing is to add a line to the docs that say, "If your base path is a directory, be sure to suffix it with `/` or relative links may not work."

**Comment by MSF-Jarvis** [comment]
Definitely, a line that will be ignored by most simply because no one expects caveats in a feature that basic (in their opinion)

**Comment by mholt** [comment]
Bah, I hate this one. I can't think of a good solution. I don't think redirecting all base path matches to have the trailing slash is a good idea because not all base paths will be directories; we really only match a prefix here, so `localhost/a` could match `localhost/asdf`... so redirecting to `localhost/a/` would not be desired.

I've updated the docs locally and they'll go out with the next update. For now, I think this is something site owners will just have to be aware of. This feature of the Caddyfile is a sharp blade.

But I'm marking this issue as deferred so we can come back to it later. Thanks!
